rule elf_mirai_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects elf.mirai."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.mirai"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "linux"
		filetype = "executable"

	strings:
		$sequence_0 = { 6689432a e8???????? c7433400000000 894330 }
		$sequence_1 = { 89d0 c1e005 01d0 89ca }
		$sequence_2 = { 894330 c6433801 c6433903 c6433a03 c6433b06 }
		$sequence_3 = { 66c1e808 d0e8 8d04c0 28c2 }
		$sequence_4 = { 3c19 7705 8d42e0 8801 }
		$sequence_5 = { 807c242b00 66894304 7406 66c743064000 c643092f }
		$sequence_6 = { 66894104 7406 66c741064000 c6410911 }
		$sequence_7 = { 8b1408 895310 8b54080c 66895314 }

	condition:
		7 of them and filesize <2228224
}
