rule elf_blackcat_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects elf.blackcat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.blackcat"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "linux"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 0f0b 90 90 90 90 53 }
		$sequence_1 = { 69c0???????? c1e811 6bf064 29f2 0fb7d2 }
		$sequence_2 = { e8???????? 0f0b 90 53 }
		$sequence_3 = { 89c1 3d???????? 7319 c1e906 }
		$sequence_4 = { 660f7f8424f0010000 660f7f8424e0010000 660f7f8424d0010000 660f7f8424c0010000 660f7f8424b0010000 }
		$sequence_5 = { d1e9 01d1 c1e902 8d14cd00000000 }
		$sequence_6 = { b801000000 81f9???????? 0f823fffffff b802000000 }
		$sequence_7 = { 69c0???????? c1e810 29c2 0fb7d2 d1ea }
		$sequence_8 = { 762a 0fb6c8 8d1489 8d0cd1 }
		$sequence_9 = { e8???????? 0f0b e8???????? 0f0b 90 90 90 }

	condition:
		7 of them and filesize <8011776
}
