rule win_leouncia_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.leouncia."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.leouncia"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { f3ab 8d442408 50 56 }
		$sequence_1 = { 52 50 a1???????? 8d8c248c050000 }
		$sequence_2 = { 83c208 8908 8b4e04 894804 8a0d???????? }
		$sequence_3 = { ff15???????? 5f b801000000 5e 81c438040000 c3 83c9ff }
		$sequence_4 = { c3 55 56 57 8d542410 6a10 }
		$sequence_5 = { 83c424 33d2 33ff 85c0 7e31 }
		$sequence_6 = { c3 8bc8 83e01f c1f905 8b0c8d60c14000 }
		$sequence_7 = { ff2485ba504000 834df0ff 8955cc 8955d8 8955e0 8955e4 8955fc }
		$sequence_8 = { c744241c00000000 c744241400040000 c7450000000000 e8???????? 83c404 8bf0 8d442410 }
		$sequence_9 = { ff2485ba504000 834df0ff 8955cc 8955d8 8955e0 8955e4 }

	condition:
		7 of them and filesize <114688
}
