rule win_sykipot_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.sykipot."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sykipot"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b94242c060000 56 8d842498000000 57 50 8b84243c060000 }
		$sequence_1 = { 8d442410 83e103 f3a4 5f 5e 5b }
		$sequence_2 = { 5f 5e 5d b80b000000 5b 81c45c180000 }
		$sequence_3 = { 8911 8b94244c060000 894104 895108 8bcd e8???????? 8b942440060000 }
		$sequence_4 = { eb58 397c241c 7518 a1???????? 8bd0 c1e20a 81c2???????? }
		$sequence_5 = { 8944240c a0???????? 894c2410 88442418 }
		$sequence_6 = { 740d 8b442424 6aff 50 ff15???????? 8b442410 8b0d???????? }
		$sequence_7 = { 8d84248c000000 f3a4 8d8c2490010000 50 51 }
		$sequence_8 = { c744241000000000 85c0 0f8e77010000 8b2d???????? 8b1d???????? be???????? }
		$sequence_9 = { 83e103 8844243c f3a4 b907000000 33c0 8d7c243d }

	condition:
		7 of them and filesize <286720
}
