rule win_paladin_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.paladin."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.paladin"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ffd3 8b17 8b4e10 2bc2 3bc1 7317 8b2d???????? }
		$sequence_1 = { 57 a3???????? ff15???????? 85c0 752b 8b3f }
		$sequence_2 = { ffd3 8d55ef 6a01 52 8d8de8feffff 8bf8 c645ef2b }
		$sequence_3 = { 56 ffd7 68???????? 56 ffd7 8bd8 }
		$sequence_4 = { c744241430a80010 8b7c2414 8b2d???????? 57 56 8d842478020000 68???????? }
		$sequence_5 = { 50 c705????????01000000 ff15???????? 8b2d???????? 8d8c249c010000 }
		$sequence_6 = { 8d8db8feffff 51 56 ffd3 85c0 }
		$sequence_7 = { e8???????? 8b4c2440 83c438 894614 8bc6 5e 64890d00000000 }
		$sequence_8 = { 6a05 57 8bcb e8???????? 8d6e7c 8bcd }
		$sequence_9 = { e8???????? 84c0 0f84bf000000 ffd3 }

	condition:
		7 of them and filesize <106496
}
