rule win_graftor_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.graftor."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.graftor"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d742434 c684245803000069 e8???????? 8b54241c 53 e8???????? 59 }
		$sequence_1 = { 55 8bec 51 8365fc00 56 0528010000 }
		$sequence_2 = { ff750c 8d7de0 ff7508 e8???????? 8b45e8 8945f0 8b45ec }
		$sequence_3 = { 8d44247c 50 c684245c03000070 e8???????? 83c40c c684245003000071 8b4c241c }
		$sequence_4 = { 6a00 eb8b 8b7d0c 8b0f 8b4514 394810 7641 }
		$sequence_5 = { 55 8bec 83e4f8 6aff 687e634c00 64a100000000 }
		$sequence_6 = { 8901 33c0 40 e9???????? 8365d800 c745dc34ad4800 a1???????? }
		$sequence_7 = { ff75ec 8d45e0 53 50 8bc6 e8???????? 8b18 }
		$sequence_8 = { eb05 a1???????? 8b4dfc 33cd e8???????? c9 c3 }
		$sequence_9 = { 3bc3 0f8686010000 8b87d0000000 6a64 99 5e f7fe }

	condition:
		7 of them and filesize <294912
}
