rule win_powersniff_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.powersniff."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.powersniff"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 720c c705????????02000000 eb11 3d00400000 720a c705????????03000000 }
		$sequence_1 = { 83ec5c a1???????? 56 57 33f6 6a44 8945f8 }
		$sequence_2 = { e9???????? 51 53 55 57 }
		$sequence_3 = { ff7614 ff15???????? 5f 5e 5d c21400 }
		$sequence_4 = { 897c2410 393d???????? 7578 8b35???????? }
		$sequence_5 = { 0fb6f3 8b5df4 c1ea18 8b149590780010 3314b5907c0010 c1eb08 }
		$sequence_6 = { 7f36 03ce 813950450000 752c }
		$sequence_7 = { 8b75f0 33349d90840010 8bda 3330 c1eb08 8975f0 }
		$sequence_8 = { 8d442410 50 8d442418 50 8974241c }
		$sequence_9 = { eb51 6a00 68424d5352 8d45fc 50 }

	condition:
		7 of them and filesize <90112
}
