rule win_unidentified_053_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_053."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_053"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 753c ff75e4 68???????? e8???????? 85c0 59 }
		$sequence_1 = { c1c603 81ea584dff93 8915???????? e8???????? 42 }
		$sequence_2 = { 8d3c85a8914100 833f00 bb00100000 7520 53 e8???????? }
		$sequence_3 = { ff75f0 50 ff91c4010000 8945f4 85c0 }
		$sequence_4 = { f7d7 c1c30e ffd0 890d???????? 87c7 2bc3 f7da }
		$sequence_5 = { f7db c1c017 e8???????? f7d1 }
		$sequence_6 = { 03f7 46 f7d8 81ebd4b243e9 c1c80c }
		$sequence_7 = { 3b8e50894100 0f8515010000 a1???????? 83f801 0f84df000000 3bc2 }
		$sequence_8 = { 81f669d8509c f7d2 686c6c6f63 e8???????? 4e 03c1 890d???????? }
		$sequence_9 = { 8b048588814100 234508 8b4e14 8d04c1 0fb64801 8b5004 83fa10 }

	condition:
		7 of them and filesize <294912
}
