rule win_disk_knight_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.disk_knight."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.disk_knight"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 897d8c 897d88 ff15???????? 8b1d???????? 8d4dc4 51 }
		$sequence_1 = { c745f0e01b4000 33c0 8945f4 8945f8 8845e0 6a01 ff15???????? }
		$sequence_2 = { ff15???????? f7d8 1bc0 23f0 8d45b0 50 8d4dc0 }
		$sequence_3 = { 8d8d7cffffff 51 56 ff5220 dbe2 85c0 7d0f }
		$sequence_4 = { 8b4710 8d5594 52 50 8b08 ff9138010000 85c0 }
		$sequence_5 = { 895004 8b8d48ffffff 894808 8b954cffffff 89500c 8b85e0feffff 8b08 }
		$sequence_6 = { 3bc8 7d7d 8d9574ffffff 52 6a01 56 e8???????? }
		$sequence_7 = { ff15???????? 8b3d???????? 83c40c 85f6 0f84d1010000 a1???????? 85c0 }
		$sequence_8 = { e8???????? 8bf0 ff15???????? 8d54240c 8d8424a0000000 52 50 }
		$sequence_9 = { 8b45d0 0f80ea060000 69db00010000 99 0f80dd060000 2bc2 899d10ffffff }

	condition:
		7 of them and filesize <868352
}
