rule win_microcin_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.microcin."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.microcin"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 488bcb ff15???????? 488b8db0010000 4833cc e8???????? 488b9c24d8020000 4881c4c0020000 }
		$sequence_1 = { ff15???????? 85c0 7426 8b400c }
		$sequence_2 = { 50 6805100000 68ffff0000 56 8b35???????? ffd6 6a04 }
		$sequence_3 = { 48895c2410 55 488dac2440feffff 4881ecc0020000 }
		$sequence_4 = { ff15???????? 8b3d???????? 8d85e0feffff 50 }
		$sequence_5 = { 488903 48894308 488b0d???????? ff15???????? 4885c0 }
		$sequence_6 = { ff15???????? 8b1d???????? 8d85a8feffff 50 ffd3 }
		$sequence_7 = { ff15???????? 488d4d90 ff15???????? 4863c8 807c0d8f5c 7412 488d4d90 }
		$sequence_8 = { ff15???????? 4863c8 c6840d8002000076 488d8d80020000 }
		$sequence_9 = { 41c7868400000004000000 4533c9 33d2 498d4e70 ff15???????? 85c0 }
		$sequence_10 = { 488d4d71 4803c8 e8???????? 418907 }
		$sequence_11 = { 56 ff15???????? 85c0 0f45f7 }
		$sequence_12 = { 8d45ac 50 6801000080 ff15???????? 85c0 }
		$sequence_13 = { c744244c7246316b e8???????? 488bc6 488b8df0040000 4833cc e8???????? 4881c400060000 }
		$sequence_14 = { 50 ffd3 85c0 7e18 }
		$sequence_15 = { 8d85f8feffff 6804010000 50 ff15???????? 8d85f8feffff 50 }
		$sequence_16 = { 636373 7673 6873742e65 7865 }
		$sequence_17 = { 8b8578dfffff 8bb578dfffff 0faf3481 03d6 }
		$sequence_18 = { 6828010000 8d85ccfeffff 6a00 50 }
		$sequence_19 = { 83c104 8b957cffffff 898c9578feffff 8b857cffffff 8b4c8584 }
		$sequence_20 = { 488bcd e8???????? 85c0 751a 488d15f8110100 41b810200100 }
		$sequence_21 = { 488d15730c0100 488bc8 ff15???????? 4885c0 7404 }
		$sequence_22 = { ff15???????? 418d7c24e7 85c0 752a 4c8d0502130100 }
		$sequence_23 = { fa fa fa fa }
		$sequence_24 = { 7669 726f 6e 6d 656e 7400 }
		$sequence_25 = { 53 53 56 43 }
		$sequence_26 = { 3d01010000 7d0d 8a4c181c 888818384100 40 ebe9 }
		$sequence_27 = { 7370 696465726167656e 742e 657865 }
		$sequence_28 = { 488d15f8110100 41b810200100 488bcd e8???????? e9???????? 4533c9 }
		$sequence_29 = { 4c8d0502130100 8bd7 498bcd e8???????? 85c0 7415 }
		$sequence_30 = { e8???????? 4c8d05b7120100 41b903000000 488d4c45bc 488bc1 492bc5 }
		$sequence_31 = { 0fb645fb 99 b903000000 f7f9 83fa01 7510 }
		$sequence_32 = { 4883ec20 8bd9 488d0d950c0100 ff15???????? 4885c0 }
		$sequence_33 = { 0f8563010000 8b5588 89957cffffff 8b8504ffffff 898574feffff 8b4d0c 8b91fc020000 }
		$sequence_34 = { 8945fc 8b4dfc 030d???????? 894dfc 8b55fc 8b450c 8a08 }
		$sequence_35 = { ff15???????? 4885c0 7419 488d15730c0100 488bc8 }
		$sequence_36 = { 8b4df8 e8???????? 68???????? 6a01 }
		$sequence_37 = { 6a00 ff15???????? 8b4df8 894128 8b55f8 837a2800 }
		$sequence_38 = { ff15???????? 8d85d4f4ffff 50 ff15???????? 6804010000 8d85f0feffff 6a00 }
		$sequence_39 = { 8b4804 0fb74906 83e902 6bc928 034808 56 }
		$sequence_40 = { ff15???????? e9???????? 68???????? 8d45dc 50 ff15???????? e9???????? }
		$sequence_41 = { c785b4feffff00000000 ff15???????? 50 56 ff15???????? }
		$sequence_42 = { 89c1 e8???????? 894510 8b4510 }
		$sequence_43 = { 895d08 52 53 41 }
		$sequence_44 = { 4c 89e9 48 89f2 4c 89b6a8000000 }
		$sequence_45 = { c744243c00000000 ff15???????? 6685c0 7441 6a00 56 }
		$sequence_46 = { 8b803c010000 56 8945f4 8d451c 50 6a04 33f6 }
		$sequence_47 = { 50 e8???????? 83c40c 8d442458 68???????? 50 }
		$sequence_48 = { 1515151515 1515151011 12????????15 1515151515 1515151515 }
		$sequence_49 = { 8bf0 85f6 0f8480000000 33c9 85f6 740a }

	condition:
		7 of them and filesize <417792
}
