rule win_slave_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.slave."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.slave"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff15???????? 85c0 0f84e0020000 6a04 6800100000 6800100000 }
		$sequence_1 = { 7514 66837b0600 7405 8a4306 }
		$sequence_2 = { 0fbf4720 33d2 50 0fb6c1 68???????? 83c008 }
		$sequence_3 = { 730d 810e00000800 808b0603000040 8b4610 808b0603000010 8a55ff }
		$sequence_4 = { c74710d5000000 eb10 c7471095000000 eb07 c7471085000000 f70700400000 742f }
		$sequence_5 = { c1c90d 33c8 8b7dd4 8b45e8 03fa c1c802 33c8 }
		$sequence_6 = { 83ec24 53 32c0 32c9 56 8b7508 }
		$sequence_7 = { 8a8e08010000 f6c210 0f8411040000 8b8610030000 0b8614030000 0f84c2000000 f6c240 }
		$sequence_8 = { 8bc6 c1c806 33c8 8bc3 3345d4 034da0 }
		$sequence_9 = { 8bd8 0b5df4 2345f4 03ca 235de0 0bd8 8b55ac }

	condition:
		7 of them and filesize <532480
}
