rule win_unidentified_095_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_095."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_095"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7572 488b4c2468 488d442450 4889442428 4c8d4c2458 488d442460 48895c2440 }
		$sequence_1 = { 4883ec20 488364243800 4c8d442438 8bd9 488d1596f30000 }
		$sequence_2 = { 75ec 8bb424d8000000 bb01000000 4533c0 }
		$sequence_3 = { 85ff 751d b957000000 ff15???????? 4883c8ff 488b6c2478 4883c440 }
		$sequence_4 = { 48896c2460 33ff 4c89742438 498bd9 4c897c2430 4c8bf9 418be8 }
		$sequence_5 = { e8???????? 498bcd e8???????? 8bcb ff15???????? }
		$sequence_6 = { 4885c9 741a 488d0554910000 483bc8 740e 83c8ff f00fc1815c010000 }
		$sequence_7 = { 4885c9 7474 33db 4c8d3d43f6feff bfe3000000 8d041f 41b855000000 }
		$sequence_8 = { 4885c0 7509 488d053b8d0100 eb04 4883c024 4883c428 c3 }
		$sequence_9 = { 4885c0 742e 488d542420 488bce e8???????? 488d542420 488bcb }

	condition:
		7 of them and filesize <339968
}
