rule win_vawtrak_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.vawtrak."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vawtrak"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a01 ff35???????? 6a04 6a01 }
		$sequence_1 = { 6a04 6a01 50 ff15???????? 85c0 }
		$sequence_2 = { 6a00 6a00 e8???????? 50 ff15???????? }
		$sequence_3 = { 33c0 b900000080 40 8901 81e900100000 75f6 }
		$sequence_4 = { c3 56 be???????? 33c0 40 8706 }
		$sequence_5 = { ba00ff0000 8bc1 23c2 3bc2 }
		$sequence_6 = { eb09 a804 7405 e8???????? 803d????????00 7405 }
		$sequence_7 = { 85c0 7516 c705????????02000000 c705????????01000000 }
		$sequence_8 = { 6a08 68???????? 56 ffd7 85c0 }
		$sequence_9 = { 7528 68???????? ff15???????? 85c0 7504 }
		$sequence_10 = { 50 ff15???????? a3???????? 85c0 74e7 }
		$sequence_11 = { e8???????? 33d2 b9ff3f0000 f7f1 }
		$sequence_12 = { 59 57 8bf0 ff15???????? 8bc6 }
		$sequence_13 = { 8bc6 8703 3bc6 74f8 }
		$sequence_14 = { 56 6a04 53 57 }
		$sequence_15 = { 8d429f 3c0f 7705 80ea61 eb0a 8d42bf 3c0f }
		$sequence_16 = { e9???????? 8ac1 c1e904 c0e004 }
		$sequence_17 = { 8ac8 240f 80e1f0 80c110 32c8 }
		$sequence_18 = { 3c41 7c11 3c46 7f0d }
		$sequence_19 = { 42881408 85f6 75de 894b0c eb03 01730c }
		$sequence_20 = { 3b4308 0f84e4000000 40883c08 ff430c e9???????? 0f86bf000000 81c7fffeffff }
		$sequence_21 = { 48397c2430 7505 bb01000000 8bc3 }
		$sequence_22 = { 3b4308 7748 85f6 742a }

	condition:
		7 of them and filesize <1027072
}
