rule win_sality_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.sality."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sality"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0302 50 6878563412 e8???????? }
		$sequence_1 = { 0255fc 8855ec 8b45ec 25ff000000 }
		$sequence_2 = { 02040a 8845fc 8b4dfc 81e1ff000000 }
		$sequence_3 = { 0302 50 6a00 e8???????? }
		$sequence_4 = { 837da000 751b 8b551c 52 8b4514 50 8b4d10 }
		$sequence_5 = { 02c8 884dec 8b55f0 83c201 }
		$sequence_6 = { 0311 52 6878563412 e8???????? }
		$sequence_7 = { 0302 8945fc 8b4d10 8b55fc }
		$sequence_8 = { 52 50 ff9539154000 58 6a00 }
		$sequence_9 = { 8b5678 0354240c 8b5a20 035c240c 33c0 8b3b }
		$sequence_10 = { 240f 3c0a 1c69 2f 8803 43 }
		$sequence_11 = { f3a6 61 7513 8bc2 83e804 8b00 }
		$sequence_12 = { eb0c 58 e8???????? b801000000 c3 }
		$sequence_13 = { 7461 8bc8 48 c6857b27400000 }
		$sequence_14 = { 8b00 0344240c eb02 33c0 }
		$sequence_15 = { ff95bc154000 85c0 7415 58 }
		$sequence_16 = { 010d???????? 83c004 5f 5e }
		$sequence_17 = { 0007 7307 c607ff 8ac1 }
		$sequence_18 = { 031e ff7608 ff7604 e8???????? }
		$sequence_19 = { 00fb fb 804880bc 280d???????? }
		$sequence_20 = { 0306 50 8d5604 e8???????? }
		$sequence_21 = { 0306 50 8b4e04 8d5608 }
		$sequence_22 = { 0202 7466 0fb77202 8b7a04 }
		$sequence_23 = { 014304 c3 53 56 }

	condition:
		7 of them and filesize <1523712
}
