rule win_doppeldridex_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.doppeldridex."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.doppeldridex"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 01501c 015020 015024 01500c }
		$sequence_1 = { 01500c 833920 751c 8bc1 }
		$sequence_2 = { 011483 40 3b06 7cf8 }
		$sequence_3 = { 010c28 8b4e04 42 8d41f8 d1e8 }
		$sequence_4 = { 017c240c 3b5c2408 0f822affffff ff74240c }
		$sequence_5 = { 33d2 3b7c2414 0f4cd3 032c24 03ee 2bea }
		$sequence_6 = { 030c24 0fbe01 88442458 85c0 }
		$sequence_7 = { 0306 894218 47 3b7c2408 }
		$sequence_8 = { 897dc4 8955c8 893424 c744240400000000 c744240864000000 898548ffffff }
		$sequence_9 = { 8945d4 0f84b3feffff e9???????? 8b45e0 }
		$sequence_10 = { eb0c 8b45dc 6683785c03 7414 eb6e 8b45ec }
		$sequence_11 = { 83fa00 89459c 8955e0 7475 e9???????? b801000000 8b4d98 }
		$sequence_12 = { 8b5df0 81f330d7a128 8b4de8 8b541104 39da }
		$sequence_13 = { 8955f8 ebe7 55 89e5 50 }
		$sequence_14 = { 8945ec 894de8 897de4 742c eb0c }
		$sequence_15 = { 83fa20 0f92c4 8a6db3 20cd 20e5 f6c501 8955b4 }

	condition:
		7 of them and filesize <360448
}
