rule win_sakula_rat_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.sakula_rat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sakula_rat"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a00 6800010000 6a00 6a00 68???????? }
		$sequence_1 = { 33c9 85f6 7e15 8a0411 84c0 7409 }
		$sequence_2 = { 742d 46 83fe03 7cd6 a1???????? 40 }
		$sequence_3 = { b803000000 eb1b e8???????? 83f801 }
		$sequence_4 = { e8???????? 83c404 5b 85c0 5f a3???????? 0f95c0 }
		$sequence_5 = { 7e0b 803c385c 7405 48 85c0 7ff5 3bc1 }
		$sequence_6 = { c3 53 e8???????? 69f6a4010000 0335???????? 8bde }
		$sequence_7 = { 6800100000 6800940100 6a00 ff15???????? 8bf0 85f6 }
		$sequence_8 = { ff75f4 ff75fc e8???????? 83c408 68???????? ff75fc }
		$sequence_9 = { 48895c2408 4889742418 57 4883ec40 ffca }
		$sequence_10 = { ff75e8 ff75e4 e8???????? 8d45dc }
		$sequence_11 = { ff15???????? 488364243800 488364243000 4c8bc6 33d2 }
		$sequence_12 = { ff7508 e8???????? 83c408 31c0 40 50 }
		$sequence_13 = { 488b4c2450 8d5340 ff15???????? 488b4c2458 8d53f1 }
		$sequence_14 = { 448d4260 e8???????? 33db 33c0 488d4de2 33d2 41b8ce070000 }
		$sequence_15 = { 0fbe02 83f85a 7f24 8b4d08 034df8 }
		$sequence_16 = { ff15???????? 488d15a4100000 488d0d05210000 ff15???????? 488d1d08230000 }
		$sequence_17 = { 3bc6 741b 488b4dc7 488b01 ff90a8000000 3bc6 }
		$sequence_18 = { 8b4508 0514010000 50 ff35???????? }
		$sequence_19 = { 488d68a1 4881ecc0000000 488365c700 488d15e90f0000 488d0d021f0000 498bf0 }
		$sequence_20 = { 8b4110 40 894304 8b410c }
		$sequence_21 = { 8364245800 ff15???????? 488d542458 488bc8 ff15???????? 488b7008 488bce }
		$sequence_22 = { 83fa00 7404 49 4a ebeb }

	condition:
		7 of them and filesize <229376
}
