rule win_icexloader_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.icexloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.icexloader"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 89e9 85ed 750b b801000000 31d2 f7f5 89c1 }
		$sequence_1 = { c3 55 89d0 89e5 57 }
		$sequence_2 = { 8907 89958cfeffff e8???????? 8b958cfeffff 8944df08 85d2 7534 }
		$sequence_3 = { b9???????? c745b400000000 e8???????? e8???????? ebd1 c9 c3 }
		$sequence_4 = { c20800 55 89e5 57 56 8d45c8 89ce }
		$sequence_5 = { 83e01f 89c1 d3ea 89d0 83e001 85c0 }
		$sequence_6 = { 5e 5f 5d e9???????? 8b07 c745e400000000 }
		$sequence_7 = { e8???????? 85c0 757e 8b4508 8d5db8 8b30 8d46e0 }
		$sequence_8 = { 8995f0feffff ba08000000 898df4feffff c785e8feffff00000000 e8???????? 8b85f4feffff 8bbdf4feffff }
		$sequence_9 = { 8b45dc 8b55d8 29d0 89c3 8b4508 8b5010 8b450c }

	condition:
		7 of them and filesize <656384
}
