rule win_winmm_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.winmm."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.winmm"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 740c 663d3000 7406 663d2000 750b 668b042e 03f5 }
		$sequence_1 = { 03ce 7504 33c0 5e }
		$sequence_2 = { 7d03 6a01 5f 85ff 0f8449ffffff }
		$sequence_3 = { 89462c ff15???????? 8bce 894604 e8???????? 85c0 }
		$sequence_4 = { 8bc8 ff5274 c3 33c0 c3 c3 56 }
		$sequence_5 = { 83c308 bf80000000 eb1d 83e86e }
		$sequence_6 = { e8???????? 59 eb1d 6a02 83c304 5f }
		$sequence_7 = { 663d2000 750b 668b042e 03f5 663bc7 75c0 397c2428 }
		$sequence_8 = { 7c02 8bfd 3b7c2428 7f5a 8b7c2428 }
		$sequence_9 = { 83c40c 85c0 752d 83c606 }

	condition:
		7 of them and filesize <278528
}
