rule win_ghole_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.ghole."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ghole"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d1410 48 8b45e8 48 8b00 48 8902 }
		$sequence_1 = { c745fcffffffff 48 8b45c8 48 89c7 e8???????? 48 }
		$sequence_2 = { e9???????? 48 8b1d???????? 48 8b55a0 48 8b45c0 }
		$sequence_3 = { 837decff 7523 48 8b05???????? ffd0 89c7 }
		$sequence_4 = { 48 83ec48 48 897dc8 8975c4 48 8955b8 }
		$sequence_5 = { 8b45e8 48 89c7 e8???????? c745f801000000 eb24 48 }
		$sequence_6 = { 8345f808 8b45b4 3b45f8 77b2 48 8b45b8 }
		$sequence_7 = { 8b00 8d5001 48 8b45e0 8910 8345f801 8b55f8 }
		$sequence_8 = { bea40f0000 48 89c7 e8???????? e9???????? 817dc49a020000 }
		$sequence_9 = { 741b 48 8b45e0 48 8b00 48 }

	condition:
		7 of them and filesize <622592
}
