rule win_danabot_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.danabot."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.danabot"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7405 83e804 8b00 83f814 7e18 8b45fc 50 }
		$sequence_1 = { c1e803 83e03f 83f838 730b ba38000000 }
		$sequence_2 = { 8b03 50 8b44242c 50 6a14 }
		$sequence_3 = { 8b45f8 85c0 7407 83e804 }
		$sequence_4 = { 8b16 e8???????? 8b07 50 8b442428 50 6a0a }
		$sequence_5 = { 50 6a14 688a4c2a8d 8bc6 8b4d00 8b17 }
		$sequence_6 = { 3b85d0feffff 7452 8b85d0feffff 50 6a00 }
		$sequence_7 = { 6a00 49 75f9 51 53 56 bb???????? }
		$sequence_8 = { 8b0f 8b16 e8???????? 8b07 50 8b442454 50 }
		$sequence_9 = { 56 57 8bf1 8955f8 8945fc 8d45fc }

	condition:
		7 of them and filesize <237568
}
