rule win_upas_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.upas."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.upas"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 68???????? ff15???????? 8bf8 85ff 7503 40 }
		$sequence_1 = { 8d4304 3bc7 0f8496000000 8b450c 397804 0f848a000000 68???????? }
		$sequence_2 = { 85c0 7441 397d18 740f 53 57 ffd6 }
		$sequence_3 = { 0f85fd000000 8d45fc 50 57 57 6a03 }
		$sequence_4 = { 68???????? ff7508 ffd7 ff7508 8b1d???????? ffd3 8d45fc }
		$sequence_5 = { 8b4508 8b403c 5d c3 8b4508 8b4008 }
		$sequence_6 = { 7507 0bcf 83fe03 7317 83fa04 7512 }
		$sequence_7 = { 55 8bec 8b450c 48 7413 48 7410 }
		$sequence_8 = { ff75fc 83e905 ff75ec c600e9 }
		$sequence_9 = { 897dfc e8???????? 59 8bc8 8945ec }

	condition:
		7 of them and filesize <114688
}
