rule win_moriya_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.moriya."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.moriya"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 48894500 e8???????? 250000ffff 488d4d80 3d00000006 0f83b4000000 }
		$sequence_1 = { 8b4f10 8d81fffeffff 83f801 7608 }
		$sequence_2 = { 488d14c500000000 4903d5 498bc9 e8???????? 4b8d0c64 0f57c0 33c0 }
		$sequence_3 = { 790c 4c8d0581100000 e9???????? 4c8d05a5100000 }
		$sequence_4 = { c785a800000000010000 f30f7f45b0 488985b0000000 e8???????? 8bd8 }
		$sequence_5 = { 4885c0 747c 4889442450 ba14000000 488928 }
		$sequence_6 = { 75f6 488b15???????? 488b4f18 e8???????? 488b05???????? }
		$sequence_7 = { 4d03cd 410fb7410c 0fb6c8 c1e108 c1e808 0bc8 }
		$sequence_8 = { 488d542458 488b4e20 ff15???????? 90 8bd3 }
		$sequence_9 = { 418bce 4885c0 7509 4c8d05b60f0000 eba3 }

	condition:
		7 of them and filesize <58368
}
