rule win_satana_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.satana."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.satana"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 52 ffd7 8b35???????? ba???????? }
		$sequence_1 = { 52 50 ff15???????? 8bc6 8d7801 8a08 40 }
		$sequence_2 = { bfff000000 f7ff 8a8258fd4000 8845fd eb04 c645fd00 84db }
		$sequence_3 = { ff15???????? 8b75dc 8975bc 8b5de0 895dc0 }
		$sequence_4 = { 56 6a08 50 ff15???????? 8bce a3???????? 85c9 }
		$sequence_5 = { 68???????? eb47 68???????? e8???????? 83c404 }
		$sequence_6 = { 668b0f 83c702 6685c9 75f5 66390f 75ad e9???????? }
		$sequence_7 = { 33c9 8b45e4 ba02000000 f7e2 0f90c1 f7d9 }
		$sequence_8 = { e8???????? 8b45fc 8b35???????? 6a30 68???????? 6a01 }
		$sequence_9 = { 0fb688a83f4100 0fb65602 884e01 0fb682a83f4100 0fb64e03 884602 0fb691a83f4100 }

	condition:
		7 of them and filesize <221184
}
