rule win_findpos_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.findpos."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.findpos"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 59 8b45f4 03c3 8945f4 }
		$sequence_1 = { 59 8b45f4 03c3 8945f4 2bfb }
		$sequence_2 = { 8b4514 40 c745ec325a4000 894df8 8945fc 64a100000000 }
		$sequence_3 = { 53 8b5d10 56 57 8b3d???????? 6a3c }
		$sequence_4 = { 8d7608 660fd60f 8d7f08 8b048d28544000 ffe0 }
		$sequence_5 = { 51 8b8de8fbffff 8d95ecfbffff e8???????? 83c40c 85c0 743c }
		$sequence_6 = { 50 50 8d85f8feffff 50 68???????? }
		$sequence_7 = { 8ac6 243f 884dfa 8845fb }
		$sequence_8 = { 6803000010 56 ff15???????? 83f8ff 0f8481000000 8b45f8 }
		$sequence_9 = { 85c0 7429 8bbdf4efffff 33f6 c1ef02 85ff 741a }

	condition:
		7 of them and filesize <286720
}
