rule win_pipemon_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.pipemon."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pipemon"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 418bf8 4903fe 85db 0f84a1000000 6690 49634e3c }
		$sequence_1 = { 7516 488d05bd360100 488b4c2430 483bc8 7405 e8???????? 488b05???????? }
		$sequence_2 = { 85c0 7427 488b4c2438 488d1526d90000 ff15???????? }
		$sequence_3 = { b906000000 48898620020000 0fb7c0 66f3ab 488d3d2c3b0100 }
		$sequence_4 = { 488d4c2438 e8???????? 4c8d4820 4889442420 4c8bc3 488d5590 488d4c2438 }
		$sequence_5 = { 4881c458010000 c3 83f801 7529 b803000000 488b8c2440010000 4833cc }
		$sequence_6 = { 458d4d02 458bc7 488d542450 488bc8 }
		$sequence_7 = { e8???????? 4881c498000000 c3 448b442430 488d1543fe0100 33c0 488d4c2440 }
		$sequence_8 = { ffc8 3d03010000 7734 488d44244c 488bd7 }
		$sequence_9 = { 80bd8008000000 0f84b6010000 4d85ed 0f84b6000000 }

	condition:
		7 of them and filesize <389120
}
