rule win_ransomlock_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.ransomlock."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ransomlock"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83c414 8dbdb0fdffff 32c0 b908020000 f3aa 8b3d???????? }
		$sequence_1 = { ffd2 8b45e8 50 ff15???????? 5f 5e 5b }
		$sequence_2 = { 85f6 0f84d1000000 6a01 53 6a03 53 53 }
		$sequence_3 = { c20400 55 8bec 8b4508 ff4850 }
		$sequence_4 = { 8b45fc 83c704 ff4dec 75c4 8b08 8b5108 50 }
		$sequence_5 = { ffd0 85c0 7822 8b45fc 3bc6 741b 8b08 }
		$sequence_6 = { a1???????? 8945fc 85c0 7450 817d0c10020000 }
		$sequence_7 = { 8bf0 85f6 7512 8d95d4fdffff 52 57 }
		$sequence_8 = { 8b45f0 3bc6 0f8418010000 8b08 8d55fc }
		$sequence_9 = { 5d c22400 b801000000 5d c22400 }

	condition:
		7 of them and filesize <360448
}
