rule win_crytox_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.crytox."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crytox"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { eb7d 85f6 7479 c645c800 e8???????? 85c0 89c3 }
		$sequence_1 = { dfe9 0f86c2e3ffff 89442410 89c1 c1fa02 db442410 c1f902 }
		$sequence_2 = { e8???????? 8b4510 3b4518 741d 0fbf45c4 c1e002 89442408 }
		$sequence_3 = { e8???????? 89c3 8b45dc 85c0 0f84adfeffff 8d65f4 89d8 }
		$sequence_4 = { eb02 d9c9 83c301 038d30ffffff 399d04ffffff 7f8e ddd9 }
		$sequence_5 = { f1 807de700 89d3 7510 6bc22c 80b84442660000 0f85ac000000 }
		$sequence_6 = { c5c5fe3d???????? c5c572e70e c5fd7f9c24000b0000 c5e572e50e c5d572e60e c5fd7f9c24e0090000 c5ddfe15???????? }
		$sequence_7 = { dee9 d95dc0 8b45e0 83c001 8d148500000000 8b4508 01d0 }
		$sequence_8 = { e9???????? 8b7d24 8b4510 85ff c70000000000 742b 8b4508 }
		$sequence_9 = { dec9 d96c2424 db5c2420 d96c2426 8b742420 d9e8 dfe9 }

	condition:
		7 of them and filesize <6156288
}
