rule win_cryptic_convo_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.cryptic_convo."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cryptic_convo"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b4588 8b08 85f6 750a 8b15???????? }
		$sequence_1 = { 53 8d4580 50 52 52 }
		$sequence_2 = { 8d85dcfaffff a5 50 8d85ecfeffff 50 a4 ff15???????? }
		$sequence_3 = { 50 ff15???????? 8dbd9c030000 83c410 4f }
		$sequence_4 = { 59 ffd6 5e c20400 0fb7442404 ff742408 50 }
		$sequence_5 = { 8bd8 8d85f8feffff 50 6a66 57 }
		$sequence_6 = { a4 8dbd70ffffff 59 4f }
		$sequence_7 = { c640fe6e c640ff6b 6808020000 8d458c 50 6aff }
		$sequence_8 = { 50 e8???????? be???????? 8d7dc8 a5 }
		$sequence_9 = { 8d84059c030000 c640fd6c c640fe6e c640ff6b 6808020000 }

	condition:
		7 of them and filesize <97280
}
