rule win_rektloader_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.rektloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rektloader"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bf0 8b4df8 e8???????? 8b10 8932 52 8bcd }
		$sequence_1 = { 68???????? 6a02 8b4510 50 8b4d0c 8b11 52 }
		$sequence_2 = { 85ff 7447 85db 7405 33c0 668903 }
		$sequence_3 = { 7609 c745c001000000 eb07 c745c000000000 8a4dc0 884dcb c645fc00 }
		$sequence_4 = { 83e102 7406 c645d601 eb04 c645d600 8a55d6 8855d4 }
		$sequence_5 = { 8b4508 8d3442 8b4dfc e8???????? 8930 b001 5e }
		$sequence_6 = { 3bf4 e8???????? 8b4df4 64890d00000000 59 5e 83c41c }
		$sequence_7 = { 8a91f8f45200 8810 8b8574ffffff 83c001 898574ffffff 8b8d6cffffff }
		$sequence_8 = { c645fc0d 8d8db4fdffff e8???????? c645fc05 8d8da8fdffff e8???????? 6a00 }
		$sequence_9 = { 8b08 8b512c 8955f4 8b4508 50 8b4df4 894df8 }

	condition:
		7 of them and filesize <3080192
}
