import "pe"

rule miner_exe_svshost
{
	meta:
		description = "exe - file svshost.exe"
		author = "The DFIR Report"
		reference = "https://thedfirreport.com"
		date = "2021-01-18"
		hash1 = "ba94d5539a4ed65ac7a94a971dbb463a469f8671c767f515d271223078983442"
		os = "windows"
		filetype = "executable"

	strings:
		$s1 = "* The error occured in hwloc %s inside process `%s', while" fullword ascii
		$s2 = "__kernel void find_shares(__global const uint64_t* hashes,uint64_t target,uint32_t start_nonce,__global uint32_t* shares)" fullword ascii
		$s3 = "lSystem.Resources.ResourceReader, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089#System.Resources.R" ascii
		$s4 = "svshost.exe" fullword wide
		$s5 = "Could not read dumped cpuid file %s, ignoring cpuiddump." fullword ascii
		$s6 = "%PROGRAMFILES%\\NVIDIA Corporation\\NVSMI\\nvml.dll" fullword ascii
		$s7 = "void blake2b_512_process_single_block(ulong *h,const ulong* m,uint blockTemplateSize)" fullword ascii
		$s8 = "* the input XML was generated by hwloc %s inside process `%s'." fullword ascii
		$s9 = "blake2b_512_process_single_block(hash,m,blockTemplateSize);" fullword ascii
		$s10 = "F:\\Apps\\cSharp\\myMinerup\\myM\\myM\\obj\\Debug\\svshost.pdb" fullword ascii
		$s11 = "|attrib +h svshost.exe" fullword ascii
		$s12 = "Found non-x86 dumped cpuid summary in %s: %s" fullword ascii
		$s13 = "GetCurrentProcessorNumberExProc || (GetCurrentProcessorNumberProc && nr_processor_groups == 1)" fullword ascii
		$s14 = "__kernel void blake2b_initial_hash(__global void *out,__global const void* blockTemplate,uint blockTemplateSize,uint start_nonce" ascii
		$s15 = "* hwloc %s received invalid information from the operating system." fullword ascii
		$s16 = "__local exec_t* execution_plan=(__local exec_t*)(execution_plan_buf+(get_local_id(0)/8)*RANDOMX_PROGRAM_SIZE*WORKERS_PER_HASH*si" ascii
		$s17 = "__kernel void execute_vm(__global void* vm_states,__global void* rounding,__global void* scratchpads,__global const void* datase" ascii
		$s18 = "__kernel void execute_vm(__global void* vm_states,__global void* rounding,__global void* scratchpads,__global const void* datase" ascii
		$s19 = "__local exec_t* execution_plan=(__local exec_t*)(execution_plan_buf+(get_local_id(0)/8)*RANDOMX_PROGRAM_SIZE*WORKERS_PER_HASH*si" ascii
		$s20 = "__kernel void blake2b_initial_hash(__global void *out,__global const void* blockTemplate,uint blockTemplateSize,uint start_nonce" ascii

	condition:
		uint16(0)==0x5a4d and filesize <19000KB and 8 of them
}
