rule win_tempedreve_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.tempedreve."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tempedreve"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 011e 015e10 015e0c 0fb75706 }
		$sequence_1 = { 011a 8b87dc000000 83c204 03c6 }
		$sequence_2 = { 01042f 034c2ff8 8d45ec 894c2ff8 }
		$sequence_3 = { 0103 a1???????? 83c004 50 ff15???????? }
		$sequence_4 = { 7546 8b75f4 8b5df8 03de 8bcb e8???????? 8bf8 }
		$sequence_5 = { 0104b7 8b8424a8000000 83c704 4d }
		$sequence_6 = { 010f 8b07 83c704 3bc1 }
		$sequence_7 = { 011a 45 8d14a9 8b02 }
		$sequence_8 = { 752a 8b542460 8b8e10040000 2b4c2450 52 8b9614040000 2b542450 }
		$sequence_9 = { 8bce 8d5c0301 e8???????? 3bd8 }
		$sequence_10 = { 894c2414 3b4c242c 0f8738010000 8b4c2410 8a1408 }
		$sequence_11 = { 7320 8d4d02 8be8 2b6c2428 8a0429 }
		$sequence_12 = { 72f3 8b4c2414 8b6c2428 3bda 0f84e1000000 3b5c2410 7647 }
		$sequence_13 = { 897c2418 899e1c040000 895c2458 3bc3 0f86eb070000 }
		$sequence_14 = { 8b6c2410 8bd3 2bd7 52 55 }
		$sequence_15 = { 3d00040000 72ed 81c200040000 83c104 2bfb }

	condition:
		7 of them and filesize <155648
}
