rule win_pipcreat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.pipcreat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pipcreat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 68d0400010 57 a3???????? e8???????? 83c418 }
		$sequence_1 = { 8945f8 ffd6 8b3d???????? 8945f0 03c0 50 53 }
		$sequence_2 = { 83c418 891d???????? 391d???????? 7450 6810270000 ffd6 c745fc03000000 }
		$sequence_3 = { 56 e8???????? 83c410 33c0 85ff 7e09 }
		$sequence_4 = { 6a02 ff35???????? ff15???????? ff35???????? ffd5 }
		$sequence_5 = { ffd6 85c0 750f 8d45f0 }
		$sequence_6 = { 53 8945f4 ffd7 50 ff15???????? }
		$sequence_7 = { 33c0 f3a5 b975000000 8d7c2448 f3ab 8b3d???????? }
		$sequence_8 = { 8d542408 68???????? 52 ff15???????? 8d442408 68???????? }
		$sequence_9 = { 6a10 ff750c ff7508 ffd0 }

	condition:
		7 of them and filesize <65536
}
