rule win_privateloader_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.privateloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.privateloader"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b4810 894de0 8b5508 8955fc }
		$sequence_1 = { 8a45ff 88040a 8b45f8 eb1f 33c9 }
		$sequence_2 = { 8b45d8 8b4ddc 8b55d0 8b75d4 }
		$sequence_3 = { 894de8 8955ec a1???????? 99 }
		$sequence_4 = { 0fb6c8 85c9 7514 c645fd00 8d4d10 e8???????? 8a45fd }
		$sequence_5 = { 8b4dec 8b5508 895110 8b4508 8945e4 }
		$sequence_6 = { 8b4810 894dd8 8b55ec 8955f8 8b45f8 8945e4 8b4df8 }
		$sequence_7 = { 8b4810 894dd8 8b55f0 8955f4 8b45f4 8945e8 8b4df4 }
		$sequence_8 = { 83e4f0 83c404 55 8b6b04 896c2404 8bec 81ec68010000 }
		$sequence_9 = { e8???????? 33d2 b93f000000 f7f1 }
		$sequence_10 = { 8b4590 8b4d94 8b5588 8b758c }
		$sequence_11 = { e8???????? 40 83ef08 a907000000 75dc }
		$sequence_12 = { d81d???????? c9 b8ffffffff 99 c3 56 }
		$sequence_13 = { a3???????? 33c0 5e c3 3b0d???????? }
		$sequence_14 = { 8b45e4 50 51 52 }
		$sequence_15 = { 13f1 83c201 8955e0 83d600 8975e4 }
		$sequence_16 = { 8b4598 03d0 8b4d9c 13f1 }
		$sequence_17 = { 7507 6800008000 eb02 6a00 6a00 }
		$sequence_18 = { 660fef4de0 0f294dc0 0f284dd0 50 }

	condition:
		7 of them and filesize <3670016
}
