rule win_cohhoc_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.cohhoc."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cohhoc"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { a3???????? ff15???????? 5f 5e 5d b801000000 5b }
		$sequence_1 = { bf???????? 33d2 f3ab 8915???????? }
		$sequence_2 = { 83c408 894500 85c0 750d }
		$sequence_3 = { 895c241c 895e24 894c2420 e8???????? }
		$sequence_4 = { 33c0 bf???????? f3ab c705????????87000000 }
		$sequence_5 = { 52 51 ff15???????? 68c8000000 }
		$sequence_6 = { 6a07 51 6a00 aa }
		$sequence_7 = { 53 89442424 53 6820000008 89442430 53 53 }
		$sequence_8 = { c7450402000000 89736c 85ff 7623 8bcf 8d442410 }
		$sequence_9 = { 8d55e0 52 50 8d043e }

	condition:
		7 of them and filesize <253952
}
