rule win_chinotto_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.chinotto."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.chinotto"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c7458035003300 c7458437002e00 c7458833003600 c7458c20002800 c745904b004800 c7459454004d00 }
		$sequence_1 = { 52 53 56 57 c7859cf6ffff00000000 ff15???????? 57 }
		$sequence_2 = { 8bd8 e8???????? 8d95e0fbffff 2bd0 8da42400000000 0fb708 66890c02 }
		$sequence_3 = { 8bcf 81e1ff0f0000 83c102 b856555555 f7e9 8bca }
		$sequence_4 = { e8???????? 8be5 5d c3 8d95bcf3ffff }
		$sequence_5 = { 83c404 85c0 7563 8b4e3c 8b7e28 8b5e2c }
		$sequence_6 = { 6a00 6a00 ff15???????? 8b35???????? 53 ffd6 68???????? }
		$sequence_7 = { 0f84b7010000 8d5603 85d2 0f84b1000000 83c606 }
		$sequence_8 = { 89463c 6a00 8bc6 895624 897e28 895e2c 894e38 }
		$sequence_9 = { eb03 8b7508 8b465c 33ff }

	condition:
		7 of them and filesize <300032
}
