rule win_locky_decryptor_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.locky_decryptor."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.locky_decryptor"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d7c2420 c684249000000001 e8???????? 6a01 33ff }
		$sequence_1 = { 56 6a5c 8bf0 e8???????? }
		$sequence_2 = { 58 33db 33c9 8945e0 }
		$sequence_3 = { 8d45e0 50 33ff 6880000000 897dc0 ff15???????? 50 }
		$sequence_4 = { 66890e 56 8d8ddcfbffff e8???????? 8bc6 }
		$sequence_5 = { 50 e8???????? 8364247800 56 50 8d442420 }
		$sequence_6 = { 68???????? 8d8504ffffff e9???????? 015ddc 6a00 5b }
		$sequence_7 = { 56 e8???????? 8b4df4 83c40c 5f 5e 8bc3 }
		$sequence_8 = { 894c2410 3bda 7e6c 33d2 c7442418f0ffffff }
		$sequence_9 = { ff15???????? c745fc0a000000 395de4 740f }

	condition:
		7 of them and filesize <278528
}
