rule win_nachocheese_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.nachocheese."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nachocheese"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d95e4fdffff 52 8d0c00 56 }
		$sequence_1 = { 2d???????? 50 68???????? 8d8df8feffff 6804010000 }
		$sequence_2 = { 2bfa 8d47fd 3901 8901 }
		$sequence_3 = { 3d9f000000 7e0d 33c0 c3 05d13fffff 83f801 77f3 }
		$sequence_4 = { 52 ff15???????? 83f801 754b 8b450c 8b4dfc 6a00 }
		$sequence_5 = { 3d2cc00000 7f18 3d2bc00000 7d1b 3d9c000000 7c07 3d9f000000 }
		$sequence_6 = { 57 8b7df4 3bfb 0f847f000000 90 8b4704 83f802 }
		$sequence_7 = { 33c0 8945fc eb58 8b0d???????? 8d4604 50 6a00 }
		$sequence_8 = { 68???????? 8d8de4faffff 6804010000 51 0fb7f0 e8???????? b8???????? }
		$sequence_9 = { 81fb80000000 7305 83c302 eb29 }
		$sequence_10 = { 7305 83c303 eb1c 81fb00000100 }
		$sequence_11 = { 02ca 8b55fc 880c3e 8a540205 32d1 }
		$sequence_12 = { ba???????? 2bd0 83c2fe 8d4813 894dec }
		$sequence_13 = { 33c8 894710 8b4708 33c1 }
		$sequence_14 = { 7305 83c304 eb0f 81fb00000001 }
		$sequence_15 = { 763a b801011000 f7e6 8bc6 }

	condition:
		7 of them and filesize <1064960
}
