rule win_swen_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.swen."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.swen"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a03 68000000c0 8d8574ffffff 50 8b1d???????? }
		$sequence_1 = { 834dfcff e9???????? e8???????? 85c0 0f8609010000 83a5388affff00 6a00 }
		$sequence_2 = { 50 ff7508 57 8d85e0feffff 50 ffd6 83c410 }
		$sequence_3 = { 85c0 0f8401030000 68???????? 68???????? 8d8574ffffff 50 8b35???????? }
		$sequence_4 = { e8???????? 8d8504fbffff 50 57 e8???????? 6a70 57 }
		$sequence_5 = { 8bf8 897dd8 85ff 7510 8b8570ffffff 8dbc0560dfffff 897dd8 }
		$sequence_6 = { 6a03 bf000000c0 57 68???????? 8d850cffffff 50 e8???????? }
		$sequence_7 = { ff15???????? 8945e0 3bc6 740e 6a01 56 }
		$sequence_8 = { 53 6a06 ff15???????? 53 ff15???????? 8b4df0 64890d00000000 }
		$sequence_9 = { ff7508 ff75e4 8d85d8feffff 50 e8???????? 83c40c }

	condition:
		7 of them and filesize <286720
}
