rule win_lazarloader_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.lazarloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.lazarloader"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 4889842440140000 488bf9 4c63d2 498bc2 418be9 48c1f806 488d0d20e00000 }
		$sequence_1 = { 488d0d10fa0000 e8???????? c705????????02000000 eb08 40b701 40887c2420 }
		$sequence_2 = { b906000000 48898620020000 0fb7c0 66f3ab 488d3d24260100 }
		$sequence_3 = { 488d1564ab0000 4c8d0561ab0000 488955df 488d054aab0000 488955e7 488945bf }
		$sequence_4 = { 448bf1 4c8d3d3682ffff 4d8be1 498be8 }
		$sequence_5 = { 488d8424b2020000 488bf8 33c0 b906020000 f3aa b864000000 }
		$sequence_6 = { 57 4883ec20 488bd9 4c8d0d28ad0000 }
		$sequence_7 = { 4c8d058baa0000 488d158caa0000 e8???????? 488bf8 4885c0 }
		$sequence_8 = { 488945f0 488d15a0bd0000 b805000000 894520 894528 }
		$sequence_9 = { e9???????? 488d0551da0000 4a8b04e8 42f644303840 }

	condition:
		7 of them and filesize <364544
}
