rule win_waterminer_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.waterminer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.waterminer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 03bc24a8000000 488bcd 4c8d0d35cb0300 83e13f }
		$sequence_1 = { 7467 8b55fc 8b0495c02b4b00 8945f8 eb09 8b4df8 }
		$sequence_2 = { 02c8 41880c18 418a03 240f }
		$sequence_3 = { 02d0 49ffc3 418d4001 881418 }
		$sequence_4 = { 02c0 0844393d 8d0412 488b5c2450 }
		$sequence_5 = { 837de040 0f8ded010000 8b4de0 833c8dc02b4b0000 0f8416010000 }
		$sequence_6 = { 50 e8???????? 83c40c c605????????00 0fb605???????? }
		$sequence_7 = { 68ce030000 68???????? 6a02 e8???????? 83c418 83f801 7501 }
		$sequence_8 = { 6821040000 68???????? 68???????? 68???????? 8b4dfc 8b51fc 52 }
		$sequence_9 = { 0344240c 4403d0 428b4405e7 418bd2 }
		$sequence_10 = { 50 e8???????? 83c418 837d0802 757f 8b4d08 8b148d24074b00 }
		$sequence_11 = { 8b1485c02b4b00 8b040a 50 ff15???????? 898594c3ffff 83bd94c3ffff00 0f84f8040000 }
		$sequence_12 = { 03c0 2bc8 0f84ec040000 8d41ff 8b848288d20600 }
		$sequence_13 = { 6bc00b 8b8880434b00 330d???????? 894dfc }
		$sequence_14 = { 03442410 4403e8 428b4405e7 418bd5 }
		$sequence_15 = { 0344240c 4403d0 488d051a560500 418b0400 }

	condition:
		7 of them and filesize <1556480
}
