rule win_gspy_auto_alt_2
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.gspy."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gspy"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 51 ff5514 46 833cb700 8d04b7 75d7 f6451001 }
		$sequence_1 = { 8d4601 85c0 741e 83c004 50 a1???????? 6a08 }
		$sequence_2 = { ffd7 85c0 7508 53 8d542410 52 }
		$sequence_3 = { 807eff00 750b 803e00 740a 03c3 3bc3 }
		$sequence_4 = { 88442424 8b442418 8b08 8d54241c 52 8b9792b04200 52 }
		$sequence_5 = { 8d542438 52 6813000020 53 c744242404000000 c744244400000000 ff15???????? }
		$sequence_6 = { 8b44246c 47 57 8d4c247c 8d7c241c c784248000000000100000 e8???????? }
		$sequence_7 = { 85ed 750f 396b08 7462 833b2c 725d }
		$sequence_8 = { 51 53 55 56 8bf0 8b4648 57 }
		$sequence_9 = { ffd5 3d02010000 750d 803d????????00 0f85fbfeffff 5f 5e }

	condition:
		7 of them and filesize <421888
}
