rule win_bernhardpos_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.bernhardpos."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bernhardpos"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0f840a010000 8d85ecfbffff 50 682a020000 68???????? 8b8df0fbffff }
		$sequence_1 = { ff15???????? 8b8d54feffff 668901 6a10 8d855cfeffff 50 }
		$sequence_2 = { 0fbe5415f8 33ca 8b4508 0345f4 8808 ebc7 5f }
		$sequence_3 = { 8945fc 8b45fc 8b4d08 03483c 894df4 }
		$sequence_4 = { 8808 ebc7 5f 5e 5b }
		$sequence_5 = { 668b0d???????? 66894dfc 8a15???????? 8855fe 8d45f8 50 ff15???????? }
		$sequence_6 = { 83e863 5f 5e 5b }
		$sequence_7 = { 51 ff15???????? 8d85ecfeffff 50 e8???????? 83c404 85c0 }
		$sequence_8 = { eb2c 33c0 eb2d 33c0 eb29 }
		$sequence_9 = { e8???????? 83c404 6a01 8d85d0feffff 50 ff15???????? }

	condition:
		7 of them and filesize <368640
}
