rule win_rovnix_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.rovnix."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rovnix"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bf8 83c335 c1e902 ad 2bc3 ab e2fa }
		$sequence_1 = { 7405 57 6a00 ffd2 89442408 }
		$sequence_2 = { 83e7f0 89542418 83c710 8bea }
		$sequence_3 = { be???????? 8b15???????? 83e7f0 89542418 }
		$sequence_4 = { 60 bf40090000 be???????? 8b15???????? }
		$sequence_5 = { ff15???????? 8b550c 884304 8bc2 c1e802 25ff000000 8d4cc324 }
		$sequence_6 = { 83c220 85c0 7404 3bc2 }
		$sequence_7 = { 7405 8d4e1c 8908 8b4508 }
		$sequence_8 = { 7511 ff4e18 7505 e8???????? }
		$sequence_9 = { 85c0 e8???????? 8be5 5d }
		$sequence_10 = { 894804 8b4608 8b4e0c 8901 894804 8b4718 }
		$sequence_11 = { 8936 8d7e08 897f04 893f 894e14 895e10 }
		$sequence_12 = { 83f919 7703 83c220 85c0 }
		$sequence_13 = { 8975d0 c745d800020000 8975d4 8975dc 8975e0 }
		$sequence_14 = { 8b7e10 eb06 8b5d0c 8b7d08 8bcf ff15???????? }
		$sequence_15 = { 7521 8bc3 c1e802 25ff000000 8d4cc724 8b01 }
		$sequence_16 = { 5d c3 85c9 e8???????? }
		$sequence_17 = { 5d c3 85c0 e8???????? }
		$sequence_18 = { 16 85c9 23d2 59 }
		$sequence_19 = { 55 8bec 85db 85c9 }
		$sequence_20 = { 23db 81e1ff000000 23c9 83440c0404 }
		$sequence_21 = { 23c9 81e1ffff0000 85c0 51 85c9 e8???????? 8be5 }
		$sequence_22 = { 8b4d08 85d2 81e1ff000000 85db 83440c0404 23d2 }
		$sequence_23 = { 45 7d58 95 08c1 a3???????? 5c 46 }
		$sequence_24 = { 59 23db 23d2 81e1ffff0000 85c0 85c0 51 }
		$sequence_25 = { 20a8261ce0dc 3d6235c121 652572f7a5a7 ce }
		$sequence_26 = { 7e27 0cc7 8e610b 69f8d60e5ca1 2e08450d }
		$sequence_27 = { 03ea 680c000000 012c24 8b0d???????? }
		$sequence_28 = { 17 d3fb 7127 49 ee }
		$sequence_29 = { 4c8bdc 49895b08 49897310 57 4883ec30 33c0 }
		$sequence_30 = { 4b af 7dce 98 }
		$sequence_31 = { 498be8 488bfa 7429 498d4320 488bd1 498d4bc8 }
		$sequence_32 = { 498b5b38 498b6b40 498b7348 8bc7 498be3 415f }
		$sequence_33 = { 61 54 99 46 45 e7f2 0ad7 }
		$sequence_34 = { 807bf9f3 53 56 b88302010b 92 090468 }
		$sequence_35 = { 59 85c0 85c0 81e1ffff0000 23d2 85db 51 }
		$sequence_36 = { ff15???????? 4c8d5c2460 498b5b18 498b6b20 }
		$sequence_37 = { 488364245800 488364247000 488364247800 488d442430 4c8d4c2440 }
		$sequence_38 = { 46 92 c55151 a2???????? d24b46 }
		$sequence_39 = { ff15???????? b8feff0000 483bf0 480f47f0 }
		$sequence_40 = { 23d2 85db 8b4d08 85db }
		$sequence_41 = { 81e1ffff0000 23d2 23c9 51 85c0 e8???????? }
		$sequence_42 = { e19b 06 6d 99 }
		$sequence_43 = { 61 c0390e 60 da57b2 }

	condition:
		7 of them and filesize <548864
}
