rule win_boldmove_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.boldmove."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.boldmove"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 894c242c 8d4aff 66894c243a 8b4c242c 09e9 0f8435010000 0fb74c243a }
		$sequence_1 = { 5d c3 55 89e5 83ec18 8b4508 89442404 }
		$sequence_2 = { e9???????? 8d4c2470 0fb64601 c744247000000000 89de 894c2430 }
		$sequence_3 = { 8b742418 8d56fd 83e2fd 0f84cf060000 8b4c2460 8b7c2440 }
		$sequence_4 = { 8d5870 895da4 8b75c0 397510 0f869b020000 8378403f 0f8677020000 }
		$sequence_5 = { 8b4304 89442408 0fb64301 89442404 0fb603 890424 e8???????? }
		$sequence_6 = { 0fb64901 0fb691608a4100 89d1 83e901 80f918 7744 }
		$sequence_7 = { 85db 0f84561d0000 81fe00040000 b800040000 0f4ec6 890424 89442440 }
		$sequence_8 = { e9???????? 85c9 0f85a4030000 0fb64601 814c246800040000 89de e9???????? }
		$sequence_9 = { 31ff 3c54 754d 83bcbe8800000000 0f84e1000000 47 83ff10 }

	condition:
		7 of them and filesize <242688
}
