rule win_lambert_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.lambert."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.lambert"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 33f2 8b55e8 33ce 33d1 }
		$sequence_1 = { 4e 8b1f 8919 2bf0 }
		$sequence_2 = { 3bd8 0f826f010000 8a07 8801 41 47 }
		$sequence_3 = { 3bd8 0f82a4000000 83fe06 0f822cffffff }
		$sequence_4 = { 55 8bec 56 8b7510 c1fe04 }
		$sequence_5 = { 2bc1 3bc7 0f82e5010000 8b4508 2bc2 8d7701 }
		$sequence_6 = { 33f1 8b4de4 33ce 314de8 }
		$sequence_7 = { 3b7d10 724d 3bf9 7349 8bc3 2bc1 }
		$sequence_8 = { 6a00 e8???????? 8945fc 8b45fc 8945f4 8b4df4 8b55f4 }
		$sequence_9 = { 50 e8???????? 8945e8 8b4de8 3b4d10 750f }
		$sequence_10 = { 83ec18 8b450c 8b4814 894df0 8b550c 8b4508 }
		$sequence_11 = { 741f 8b4df8 c1e90d 8b55f8 }
		$sequence_12 = { ebce 8b45f8 8be5 5d c20400 55 8bec }
		$sequence_13 = { 8b510c 8b421c 8945f4 8b4df4 894df0 }
		$sequence_14 = { 3b5118 7334 8b45fc 8b4dec }
		$sequence_15 = { e8???????? 8945f8 8b4df8 3b4d08 7508 8b55f4 }

	condition:
		7 of them and filesize <1212416
}
