rule win_ghostsocks_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.ghostsocks."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ghostsocks"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 8b4c2408 8d41ff 8b542404 31db }
		$sequence_1 = { e8???????? 8b4c240c 8401 8b442450 }
		$sequence_2 = { e8???????? 8b4c2408 8b9424a0050000 8b1a }
		$sequence_3 = { e8???????? 8b4c2408 8b942490000000 8d5a4c 895c2474 }
		$sequence_4 = { e8???????? 8b4c240c 890f 8908 }
		$sequence_5 = { e8???????? 8b4c240c 83f9ff 740d }
		$sequence_6 = { e8???????? 8b4c240c 81f900ac0000 7416 }
		$sequence_7 = { e8???????? 8b4c240c 85c9 0f842c010000 }
		$sequence_8 = { e8???????? 89856068fcff 89956468fcff 8d8d1bc3faff }
		$sequence_9 = { e8???????? 89856074fbff 89956474fbff a1???????? }
		$sequence_10 = { e8???????? 8985605ffdff 8995645ffdff 0fb6856fd5faff }
		$sequence_11 = { e8???????? 89856076fcff 89956476fcff 8b85d0adfdff }
		$sequence_12 = { e8???????? 89856078fbff 89956478fbff 8b0d???????? }
		$sequence_13 = { e8???????? 89856071fcff 89956471fcff a1???????? }
		$sequence_14 = { e8???????? 89856059fcff 89956459fcff 8b851481fbff }
		$sequence_15 = { e8???????? 89856077feff 89956477feff 8b8d647ffeff }

	condition:
		7 of them and filesize <25016320
}
