rule win_unidentified_003_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_003."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_003"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 74b5 837df800 7512 8b45fc 85c0 }
		$sequence_1 = { 0f85b2000000 8b7df4 81ff00003000 0f83a3000000 0fb645ff 50 8d85cafeffff }
		$sequence_2 = { 8bc3 03c0 8d44c410 e8???????? 85c0 }
		$sequence_3 = { 33d2 8bc6 f7742418 8b442414 8d0c3e 8a0402 }
		$sequence_4 = { 53 68???????? e8???????? 59 59 eb3d 33f6 }
		$sequence_5 = { ff45fc 8b45fc 3b4618 72c0 eb3d 8b55fc 0fb70451 }
		$sequence_6 = { 6a0c bb???????? 53 6a01 }
		$sequence_7 = { 57 a3???????? e8???????? 83c40c 68???????? 53 8d742430 }
		$sequence_8 = { 0f8513030000 395dfc 0f840a030000 8d45dc 50 68???????? 57 }
		$sequence_9 = { 895de8 8b45ec 8b08 8d55f0 }

	condition:
		7 of them and filesize <57344
}
