rule win_purplefox_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.purplefox."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.purplefox"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7471 33c0 89442418 8944241c 52 }
		$sequence_1 = { 488d6c24b9 4881ecd0000000 33d2 488bd9 }
		$sequence_2 = { 85c0 7507 b802000000 eb1a 8b4704 68???????? 50 }
		$sequence_3 = { 488d545c20 0f1f00 0fb702 4883c102 4883c202 668941fe }
		$sequence_4 = { 33c9 ff15???????? 488d0d3f860000 ff15???????? 833d????????00 }
		$sequence_5 = { 50 ff15???????? 8bf0 85f6 7918 56 68???????? }
		$sequence_6 = { a977e11230 32df a7 bb3dcebff7 }
		$sequence_7 = { 0f8594000000 488d5114 48897c2458 e8???????? 894310 85c0 }
		$sequence_8 = { 8bff 8b38 8b87b0000000 83c018 }
		$sequence_9 = { 53 7973 52 6541 6c 6c 6f }
		$sequence_10 = { 488d4158 41b806000000 488d15da8f0000 483950f0 740c 488b10 }
		$sequence_11 = { 8b0485000c4100 8d44380c 50 ff15???????? }
		$sequence_12 = { 8d442418 50 8d4c2410 51 ffd7 8b3d???????? }
		$sequence_13 = { 827357ab a90f1ff9c7 96 bb2a3086e8 0867ee }
		$sequence_14 = { 4c89442448 4889442430 4889542440 448d4b10 4c8d442440 ba04202200 895c2428 }
		$sequence_15 = { f8 28c3 66f7c46baa 68c9efaa5a }
		$sequence_16 = { c6042439 ff3424 8d642440 e9???????? }
		$sequence_17 = { 488d0dfb460000 ff15???????? 488bf0 4885c0 0f8493010000 }
		$sequence_18 = { 8945f0 8945f8 8b450c 897dfc }
		$sequence_19 = { 9c 0fbedb 8b5c2404 9c }
		$sequence_20 = { bf01000000 56 ff15???????? 53 ff15???????? }
		$sequence_21 = { 895608 ff15???????? 894704 5b 85c0 }
		$sequence_22 = { 488bce e8???????? 488bcb e8???????? 8bc7 eb0a }
		$sequence_23 = { 8955f8 8d55fc 52 50 }
		$sequence_24 = { 5e 5b 8be5 5d c3 8b0d???????? 8b11 }
		$sequence_25 = { 8d642430 0f847cfdffff 660fb3e1 f8 }
		$sequence_26 = { ff15???????? 488b4c2460 ff15???????? 488d0d730f0000 eb07 488d0d7a0f0000 }
		$sequence_27 = { 8d442448 50 e8???????? 8b1d???????? 83c40c }
		$sequence_28 = { 4889752f 48897537 ff15???????? 8bd8 85c0 791a }
		$sequence_29 = { 03c6 6d a4 46 56 01a3ec941e56 a0???????? }
		$sequence_30 = { 51 8d542410 52 ffd7 }
		$sequence_31 = { c1f805 8bf7 83e61f c1e606 033485000c4100 c745e401000000 33db }
		$sequence_32 = { 6a00 010e 8b45f0 50 6a04 }
		$sequence_33 = { 488bcd 48c744242000000000 ff15???????? 48894308 }
		$sequence_34 = { 4889442430 488b05???????? c644242800 488b08 ba00020000 48894c2420 488b8d90010000 }
		$sequence_35 = { 488d158f200000 488d4c2440 ff15???????? 488b13 }
		$sequence_36 = { 57 4883ec20 488d0dfdad0000 488bf2 }
		$sequence_37 = { 488d0d14200000 ff15???????? 488d4c2430 e8???????? e9???????? }
		$sequence_38 = { 488bd9 48c744243000000000 488d0d27b10000 4533c9 4533c0 ba000000c0 c744242880000000 }
		$sequence_39 = { 895dc4 897dcc 895dd0 895dd4 ffd6 8bf0 3bf3 }

	condition:
		7 of them and filesize <1983488
}
