rule win_zeoticus_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.zeoticus."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeoticus"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 660f62f9 660fd4bc2400010000 0f284c2430 660fd4f8 660f3a0f4c241008 660fefdf 8b942414010000 }
		$sequence_1 = { 6a15 ba???????? b90b7a9652 e8???????? 83c408 a3???????? 680c0e0000 }
		$sequence_2 = { 33c9 66c787701110000001 90 8a8100674300 88840f90101000 41 }
		$sequence_3 = { 2b9d74ffffff 898568ffffff 8b8544ffffff 2b4594 8b7dc8 2bbd78ffffff }
		$sequence_4 = { 660f62ca 660f6e9424a4000000 0f295c2430 0f28442430 660f6e5c2444 660f62c1 660f6e4c2440 }
		$sequence_5 = { 8b74240c ba???????? 680f8ed51c 6a16 b932347982 c744241801000000 c744242402000000 }
		$sequence_6 = { 8d4901 83ea01 75f5 8bcb 2bf3 ba20000000 0f1f8000000000 }
		$sequence_7 = { 6a03 68???????? 6a0a 68???????? e8???????? 685d0b4077 6a0a }
		$sequence_8 = { 660f72d00e 660f72f412 660fefa590feffff 660fefe0 0f28c5 660ffec7 0f29a530ffffff }
		$sequence_9 = { 2b9d78ffffff 2bbd7cffffff 2b7580 2b5584 898524ffffff 8b8534ffffff 8945b4 }

	condition:
		7 of them and filesize <468992
}
