rule win_hdmr_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.hdmr."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hdmr"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b4514 8b16 8b527c 50 57 }
		$sequence_1 = { 7511 8b4d0c 8b5018 51 8bce }
		$sequence_2 = { 8b048540d04100 83e61f c1e606 59 c644300400 85ff }
		$sequence_3 = { 83c40c 33f6 e8???????? 25ff000080 7907 48 0d00ffffff }
		$sequence_4 = { be00000000 7454 f6c301 7445 8d8df0f5ffff }
		$sequence_5 = { 0f84e1030000 6a00 6a00 6a00 }
		$sequence_6 = { 5e 8bc8 8b929c000000 5d }
		$sequence_7 = { 53 ff15???????? 85c0 7451 57 e8???????? 83c404 }
		$sequence_8 = { 33cb 33480c 8bdf c1eb08 894df0 8b4d08 81e3ff000000 }
		$sequence_9 = { 33c0 68fe070000 50 8d8c2472020000 51 8974241c 6689842474020000 }

	condition:
		7 of them and filesize <284672
}
