rule win_parallax_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.parallax."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.parallax"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 837e3000 740c 8b5630 8d424c 50 e8???????? e9???????? }
		$sequence_1 = { 6a00 ff35???????? ff5260 837f3400 7413 }
		$sequence_2 = { 56 ff7508 e8???????? eb5e 3de9030000 7557 }
		$sequence_3 = { 50 8d45f8 50 ff75fc ff96a4000000 85c0 0f850a010000 }
		$sequence_4 = { e8???????? 96 5f 5e 5d c20400 55 }
		$sequence_5 = { c7474000200000 eb18 ff7640 8f45fc 8b35???????? 8b55fc }
		$sequence_6 = { 3b35???????? 72d0 58 8b1d???????? 6bdb04 03c3 8b7d0c }
		$sequence_7 = { 7530 6a01 68ff1f0000 e8???????? }
		$sequence_8 = { 8975e4 8d55f0 8b0e 890a }
		$sequence_9 = { c7421c00000000 6a06 ff750c e8???????? }

	condition:
		7 of them and filesize <352256
}
