rule win_yanluowang_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.yanluowang."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.yanluowang"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83e901 7419 83e901 0f8559feffff 0fbe46ff 8d04c508974400 e9???????? }
		$sequence_1 = { 8bf1 8b4508 8d5101 c745bc00000000 8945ec c745cc00000000 c745d00f000000 }
		$sequence_2 = { 8bd6 c645fc0e 8d8db4eeffff e8???????? 83c438 c645fc12 8d8d78eeffff }
		$sequence_3 = { 8d04c5f0984400 50 e8???????? eb14 3c40 7420 41 }
		$sequence_4 = { c745e4d8a24400 c745e804000000 eba1 83fb5f 7469 8d41ff a3???????? }
		$sequence_5 = { 3bf8 7424 2bdf 8bf0 0fb707 50 }
		$sequence_6 = { 8bd7 c1fa06 8bc7 83e03f 6bc830 8b049538034600 f644082801 }
		$sequence_7 = { 8d50ec 0f1040ec 0f1101 f30f7e40fc 660fd64110 c740fc00000000 }
		$sequence_8 = { 8b7d10 8b4d08 8d1db0874400 8bf4 83e4f0 81ec10030000 56 }
		$sequence_9 = { 337dc8 8b4514 85c0 7402 8938 8d7904 33d2 }

	condition:
		7 of them and filesize <834560
}
