rule win_xfilesstealer_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.xfilesstealer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.xfilesstealer"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7505 488b1b ebc7 c707bd0000c0 e9???????? 8907 e9???????? }
		$sequence_1 = { f30f7f4510 48897d20 4533c9 448d4703 488d5510 488d8df0010000 e8???????? }
		$sequence_2 = { e8???????? 488bd0 4c8bc3 488d8dd0030000 e8???????? 488d15210a3200 488d4da0 }
		$sequence_3 = { e8???????? 90 837c244800 7424 488b742440 4885f6 7415 }
		$sequence_4 = { e8???????? 85c0 784b 8b05???????? 83f82d 0f83a6e81c00 8b4c8320 }
		$sequence_5 = { e8???????? 89442474 448b45d8 4533d2 488bcf e8???????? f7d8 }
		$sequence_6 = { e8???????? 8bd8 85c0 791e e9???????? ff15???????? cc }
		$sequence_7 = { ffd3 85c0 0f8868010000 498b9630020000 488b4de0 4883c203 e8???????? }
		$sequence_8 = { 83ea2f 7422 83ea01 0f8486fa2e00 83fa01 0f8427120600 498d48fe }
		$sequence_9 = { e8???????? 8bf8 85c0 781d 498bce 395d50 7409 }

	condition:
		7 of them and filesize <20821780
}
