rule win_tidepool_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.tidepool."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tidepool"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a00 50 8b08 ff91a4000000 }
		$sequence_1 = { 8b4df4 64890d00000000 59 5f 5e 5b 8b8d00030000 }
		$sequence_2 = { 8b8d00030000 33cd e8???????? 81c504030000 }
		$sequence_3 = { 83c404 8bc6 5e c20400 80790800 }
		$sequence_4 = { 53 6a02 8bf1 e8???????? }
		$sequence_5 = { 6800000040 8d4500 50 ff15???????? }
		$sequence_6 = { 2bc8 83e906 51 83c006 50 }
		$sequence_7 = { e8???????? 83c40c 803d????????37 7518 68???????? }
		$sequence_8 = { 8b4654 8d9698000000 52 8d5678 8b08 }
		$sequence_9 = { 52 50 8b08 ff91f8000000 85c0 }
		$sequence_10 = { 8b4654 50 8b08 ff5138 }
		$sequence_11 = { 8d5658 52 50 ff91d0000000 33ff }
		$sequence_12 = { c3 56 8bf1 e8???????? 8b4654 }
		$sequence_13 = { 8d45ec 50 681f000200 53 }
		$sequence_14 = { 6810270000 ff15???????? 8b45ec 8b08 }
		$sequence_15 = { 681f000200 56 68???????? 6801000080 }
		$sequence_16 = { 75f9 b8???????? b900000400 c60000 40 49 }
		$sequence_17 = { e8???????? 68???????? 68???????? 68???????? 8d4500 }
		$sequence_18 = { 57 50 6802020000 ff15???????? 68???????? ff15???????? }
		$sequence_19 = { 8bc6 5e 5b c20400 6a14 68???????? }
		$sequence_20 = { 6805400080 e8???????? 8b542424 52 53 }
		$sequence_21 = { 33c9 8aea 83c003 83c504 }
		$sequence_22 = { ff75ec ff15???????? 8b35???????? 6a04 }
		$sequence_23 = { 83651400 8b07 83c40c 837d0c00 0f8ed1000000 8b4d08 41 }
		$sequence_24 = { 8bec 8b4508 56 833c850811011000 }
		$sequence_25 = { 50 ff7508 ff15???????? 395dfc 53 }
		$sequence_26 = { 50 8d4604 50 e8???????? 8d45e0 6a04 }
		$sequence_27 = { 50 89450c ff15???????? 53 ff75fc ff75f8 }
		$sequence_28 = { 8365ec00 8945f4 8d3dd8e30010 8b45f4 d1e0 03f8 }

	condition:
		7 of them and filesize <1998848
}
