rule win_breach_rat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.breach_rat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.breach_rat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 807dbc00 7515 33c9 8d45bc 51 50 }
		$sequence_1 = { 770f 0fbec2 0fb680a0974300 83e00f eb02 33c0 8bbdc8fdffff }
		$sequence_2 = { 8906 0fb6c1 84c9 7446 83f8ff 75ae eb3f }
		$sequence_3 = { 8bb534ffffff 8b4db4 8955ec 8b55dc 39540e10 8b55e4 8b8d7cffffff }
		$sequence_4 = { 33f6 57 8d81ac000000 8d7a3c 0fb748fc 8d4008 03d1 }
		$sequence_5 = { c745d800000000 c645c800 e8???????? 6a04 68???????? 8d4de0 c645fc01 }
		$sequence_6 = { 0f85f4feffff c74720ffffffff 33c0 5f 5e 5b 8be5 }
		$sequence_7 = { 56 33f6 8945ec 57 33ff c745e80f000000 }
		$sequence_8 = { 50 64892500000000 83ec78 53 8b5d10 56 }
		$sequence_9 = { 50 e8???????? 8b4664 83c408 8b0e 894654 e8???????? }

	condition:
		7 of them and filesize <645120
}
