rule win_iconic_stealer_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.iconic_stealer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.iconic_stealer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 488bd0 4885c0 7450 85db 7e32 488bc8 }
		$sequence_1 = { bab4000000 e8???????? 4c8bc0 e9???????? 4533c9 4533c0 bab4000000 }
		$sequence_2 = { 8bd7 488bcb e8???????? eb0d 488b4328 668363142d 48894308 }
		$sequence_3 = { c744c80805000000 448944c80c 4c894cc810 488b03 8b9390000000 80786700 7409 }
		$sequence_4 = { bf05000000 8bc7 488b8d60010000 4833cc e8???????? 4c8d9c2470020000 498b5b18 }
		$sequence_5 = { e8???????? 488bf8 4885c0 0f8411010000 0f57c0 33c0 0f1107 }
		$sequence_6 = { c3 48f7da 781d 4d85c0 7e33 48b8ffffffffffffff7f 492bc0 }
		$sequence_7 = { c60741 e9???????? 6685c2 0f854c010000 488b01 488b6818 6644854912 }
		$sequence_8 = { eb38 4885f6 740f ba40000000 488bce e8???????? eb0a }
		$sequence_9 = { c7452801000000 e9???????? ba48000000 498bcc e8???????? 488bf8 4885c0 }

	condition:
		7 of them and filesize <2401280
}
