rule win_portdoor_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.portdoor."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.portdoor"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 51 56 8b35???????? 807e0400 7504 32c0 eb3f }
		$sequence_1 = { 890d???????? ff15???????? 8b4618 8bd7 }
		$sequence_2 = { 8d7f08 8b048d38ef0010 ffe0 f7c703000000 7515 c1e902 83e203 }
		$sequence_3 = { 8d7a28 f3ab 6a08 8d7272 59 }
		$sequence_4 = { c745e4a00f0210 a1???????? 33db 43 }
		$sequence_5 = { e8???????? 8be5 5d c3 e8???????? cc 6a08 }
		$sequence_6 = { 3c58 770f 0fbec2 0fbe80e0940110 }
		$sequence_7 = { 807e0400 0f8564ffffff eb0c ff36 ff15???????? c6460400 5f }
		$sequence_8 = { 8bf9 8b4f08 83c110 e8???????? 8b5708 }
		$sequence_9 = { 56 57 6a08 8bf1 e8???????? 8bf8 }

	condition:
		7 of them and filesize <297984
}
