rule win_hive_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.hive."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hive"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 31c0 b91d000000 31d2 31db }
		$sequence_1 = { b807000000 b9d4000000 31d2 31db }
		$sequence_2 = { 31c9 31d2 bb8b000000 31f6 }
		$sequence_3 = { 89d1 e8???????? b802000000 e8???????? }
		$sequence_4 = { 31f6 f00fb132 0f94c2 84d2 0f852bffffff be01000000 e9???????? }
		$sequence_5 = { 39b100000000 750a e8???????? e8???????? }
		$sequence_6 = { 89d1 e8???????? e8???????? e8???????? }
		$sequence_7 = { 89d1 e8???????? 89f0 e8???????? }
		$sequence_8 = { 89c2 e8???????? b801000000 e8???????? 90 }
		$sequence_9 = { 31c9 31d2 bb8e000000 31f6 }
		$sequence_10 = { 31c0 e9???????? 8d4201 83f841 }
		$sequence_11 = { 31c9 31d2 bb8a000000 31f6 bfd0000000 eb0e }
		$sequence_12 = { 31c9 31d2 bbda000000 31f6 }
		$sequence_13 = { 89d1 e8???????? b901000000 e8???????? }
		$sequence_14 = { 01c1 c1e106 400fb6d6 01ca }
		$sequence_15 = { 01c0 4000f8 0fb6c0 48898424b0000000 }
		$sequence_16 = { 01c8 89c1 c1e91f ffc9 }
		$sequence_17 = { 01c8 c1e006 400fb6cf 01c1 }
		$sequence_18 = { 01c1 83c101 83f90c 0f820fffffff }
		$sequence_19 = { 01c2 b8ffffff03 21c5 21c3 }
		$sequence_20 = { 01ca c1e206 0fb6c3 01d0 }
		$sequence_21 = { 01c1 c1e106 0fb6c2 01c8 }

	condition:
		7 of them and filesize <7946240
}
