rule win_pickpocket_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.pickpocket."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pickpocket"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { eb0c b96ccb0000 eb05 b960cb0000 e8???????? }
		$sequence_1 = { b97dcb0000 eb0c b96ccb0000 eb05 b960cb0000 e8???????? eb02 }
		$sequence_2 = { 750f b962890100 e8???????? e9???????? }
		$sequence_3 = { 750f b93eaf0000 e8???????? e9???????? }
		$sequence_4 = { eb05 b960cb0000 e8???????? eb02 33c0 }
		$sequence_5 = { 750e b958de0100 e8???????? 8bc8 }
		$sequence_6 = { 750f b91f220100 e8???????? e9???????? }
		$sequence_7 = { 741a b97dcb0000 eb0c b96ccb0000 eb05 }
		$sequence_8 = { 33c0 eb0a b952ca0000 e8???????? }
		$sequence_9 = { 3bc7 760a b988d30000 e9???????? }

	condition:
		7 of them and filesize <1458176
}
