rule win_winordll64_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.winordll64."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.winordll64"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 488d4dbc ff15???????? 488d15ae1c0100 488bc8 e8???????? 85c0 }
		$sequence_1 = { 4833c4 488985581d0000 488bd9 b838070000 48ffc8 c6040100 75f7 }
		$sequence_2 = { 48897c2420 ff15???????? 85c0 7426 448b842490000000 4c8d4c2430 }
		$sequence_3 = { e9???????? ba12000000 ebf0 48897c2440 897c2448 488d442448 4889442420 }
		$sequence_4 = { e8???????? 4c8d0513c50000 41b903000000 488d4c45bc 488bc1 492bc5 }
		$sequence_5 = { 488bcf c744243001000000 448be8 ff15???????? }
		$sequence_6 = { 663918 75f5 4c8d4da0 48837db808 4c0f434da0 486307 }
		$sequence_7 = { 7423 83fefe 741e 488bce 488bc6 488d1554370100 83e11f }
		$sequence_8 = { 7767 488d4d98 482bcb 48b8abaaaaaaaaaaaa2a 48f7e9 488bf2 }
		$sequence_9 = { 0f84bd010000 488b4c2450 4533c0 418bd5 ff15???????? 85c0 0f847b010000 }

	condition:
		7 of them and filesize <278528
}
