rule win_unidentified_044_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_044."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_044"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 56 ff15???????? eb4a 6a04 8d44242c }
		$sequence_1 = { eb50 e8???????? 8bf0 83feff }
		$sequence_2 = { 56 68???????? 6a00 6a00 ff15???????? 85c0 751b }
		$sequence_3 = { 85c0 740f 833d????????00 7406 b801000000 c3 }
		$sequence_4 = { 750d 8a4a05 80f90f 7605 80f920 }
		$sequence_5 = { e8???????? 83c404 8bf0 e8???????? 45 }
		$sequence_6 = { ff15???????? 85c0 750f 8b1424 52 ff15???????? }
		$sequence_7 = { 6a04 8d542408 52 8d442410 50 c644241005 c644241200 }
		$sequence_8 = { 41 3bcf 72b9 8b7c2418 }
		$sequence_9 = { 85c0 74c7 6a04 55 50 e8???????? 8b0d???????? }

	condition:
		7 of them and filesize <90112
}
