rule win_rokrat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.rokrat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rokrat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 50 e8???????? 6a04 33c0 }
		$sequence_1 = { 56 50 8d45f4 64a300000000 c745fc00000000 33c0 }
		$sequence_2 = { 50 e8???????? 8d8e0c010000 8d4550 3bc8 }
		$sequence_3 = { 0fb7c1 50 0fb74208 c1e910 }
		$sequence_4 = { 8ad0 8d4dd8 e8???????? c745fc06000000 }
		$sequence_5 = { 56 8d4dc0 c745d000000000 668945c0 e8???????? c645fc03 8b45bc }
		$sequence_6 = { 50 e8???????? 8d4568 8d4e60 }
		$sequence_7 = { 50 ff15???????? e8???????? 40 }
		$sequence_8 = { 50 e8???????? 6a10 33c0 }
		$sequence_9 = { ff15???????? 50 e8???????? 59 6a64 }
		$sequence_10 = { 897dfc e8???????? 68???????? 8d4dd8 }
		$sequence_11 = { bf???????? c744243401000000 8b4e58 3b8174030000 }
		$sequence_12 = { bfc0010000 eb0d 33c0 68???????? }
		$sequence_13 = { bf???????? 8b4c2424 8d41ff 83f81d 0f87b6030000 0fb680e4664b00 }
		$sequence_14 = { bf???????? c7442410102c5000 7504 897c2410 }
		$sequence_15 = { bf???????? 833cf56c4c540001 751e 8d04f5684c5400 8938 68a00f0000 }

	condition:
		7 of them and filesize <2932736
}
