rule win_friedex_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.friedex."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.friedex"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a26 8bc8 e8???????? 57 8bc8 e8???????? 6a65 }
		$sequence_1 = { 03cd 0fb711 6685d2 75c1 6a2a 5f eb06 }
		$sequence_2 = { eb16 0fb730 663bf7 7416 663bf2 7405 }
		$sequence_3 = { eb0f 03c5 663938 74f9 33c9 }
		$sequence_4 = { 85c0 740d ff742408 6a00 6a00 }
		$sequence_5 = { 8b442408 53 55 56 57 6a2a 5f }
		$sequence_6 = { 03f5 eb04 03c5 03cd }
		$sequence_7 = { 6a3f 5a 663bfa 7408 8bce 8bc3 }
		$sequence_8 = { c744240400000000 8955e8 e8???????? 8d0dbc30a500 890424 894c2404 }
		$sequence_9 = { 891424 894c2404 8945f8 e8???????? 8d0d4430a500 }
		$sequence_10 = { c3 55 89e5 83ec10 8b4508 8d0d4430a500 }
		$sequence_11 = { 83c404 5d c3 55 89e5 8d055a23a500 }
		$sequence_12 = { 894608 890c24 c744240400000000 8955ec e8???????? 8d0dad30a500 890424 }
		$sequence_13 = { c7424800100100 8b7de4 c787cc00000000000000 c787c800000000000000 8945dc }
		$sequence_14 = { 8945d0 74e4 31c0 8d0d5a23a500 }
		$sequence_15 = { e8???????? 8d0d4430a500 31d2 8b75f8 89460c 890c24 }

	condition:
		7 of them and filesize <204800
}
