rule win_darktequila_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.darktequila."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.darktequila"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 742e a1???????? 8d5001 8a08 40 }
		$sequence_1 = { e8???????? 50 57 ffd6 a3???????? 85c0 7407 }
		$sequence_2 = { 2bd0 7425 4a 7419 83ea02 753c 8b4508 }
		$sequence_3 = { 52 ffd7 8bf0 85f6 743f 83c603 b901000000 }
		$sequence_4 = { 8b0d???????? 8b15???????? 51 52 bb???????? e8???????? }
		$sequence_5 = { 83e803 7408 48 7527 8d4301 }
		$sequence_6 = { ff15???????? 85c0 740a c705????????01000000 b80b000000 }
		$sequence_7 = { 51 8b4b10 2bd0 52 03c8 }
		$sequence_8 = { b808000000 e8???????? 50 57 }
		$sequence_9 = { 3b7b04 7660 837b1000 740b 8bf3 e8???????? }

	condition:
		7 of them and filesize <1827840
}
