rule win_karagany_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.karagany."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.karagany"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { bb???????? 8bc7 e8???????? 85c0 }
		$sequence_1 = { 8b35???????? 57 8bf8 6a03 57 ffd6 }
		$sequence_2 = { 56 8b35???????? 57 8bf8 6a03 }
		$sequence_3 = { 57 8bf8 6a03 57 }
		$sequence_4 = { 6a64 ff15???????? 5f 5e 33c0 5b 8be5 }
		$sequence_5 = { c745a444000000 e8???????? 83c40c 8d45ec }
		$sequence_6 = { 55 8bec 81ec60060000 53 56 57 33c0 }
		$sequence_7 = { 6a03 57 ffd6 85c0 }
		$sequence_8 = { 894ddc 894de4 894df0 894df8 }
		$sequence_9 = { 8945d0 8945d8 8945e0 8945e8 8945ec 8945f4 }

	condition:
		7 of them and filesize <180224
}
