rule win_usbferry_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.usbferry."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.usbferry"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c685abfaffff6b c685acfaffff6b c685adfaffff69 c685aefaffff6c c685affaffff6c }
		$sequence_1 = { 75a5 8b4dfc 8b45f8 8b5718 2bd0 84db }
		$sequence_2 = { 3c2d 7501 42 33c0 eb11 80fb39 }
		$sequence_3 = { 83c40c 6a00 6a00 8d8da4f5ffff 51 }
		$sequence_4 = { c645ec66 c645ed6c c645ee61 c645ef73 }
		$sequence_5 = { 742c 8b4de0 51 ff15???????? c745c000000000 }
		$sequence_6 = { 8bc7 5f 99 f7ff }
		$sequence_7 = { 898154010000 8b09 e8???????? 8b0d???????? ff7110 8b9160010000 }
		$sequence_8 = { 8b5d08 56 57 8bf9 0fb637 47 8d46bf }
		$sequence_9 = { 8a02 8b742414 84c0 7407 8807 e9???????? }
		$sequence_10 = { e8???????? 8b0d???????? 83c440 ff7110 8b91d0000000 }
		$sequence_11 = { ff5060 ff75e0 8b0d???????? ff514c c3 }
		$sequence_12 = { 6a01 8d85a8faffff 50 e8???????? 83c408 }
		$sequence_13 = { 85c0 7422 c745d000000000 6afe 8d55f0 52 }
		$sequence_14 = { 8b8588f5ffff 89857cf5ffff 899578f5ffff 8d8da8faffff }
		$sequence_15 = { 6a00 8d85f5f7ffff 50 e8???????? 83c40c }

	condition:
		7 of them and filesize <638976
}
