rule win_romcom_rat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.romcom_rat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.romcom_rat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 4183fd04 0f8508010000 41bd03000000 e9???????? 418d45ff 4c897c2430 448bc9 }
		$sequence_1 = { 488d157f510200 e8???????? 4c8d0db3510200 b908000000 4c8d059f510200 488d15a0510200 e8???????? }
		$sequence_2 = { 488b5c2460 488bc6 488b742470 488b6c2468 4883c430 }
		$sequence_3 = { 884709 eb04 48832700 c6470801 0fb64f09 498b4718 0fbf1448 }
		$sequence_4 = { 488d55f0 498bce ff15???????? 413bc4 0f85e6000000 41bf00100000 448beb }
		$sequence_5 = { 66393c41 75f7 488d1c43 4883c302 eb03 48ffc3 f6c301 }
		$sequence_6 = { 488d1533e60500 498bca ff15???????? 4d8be5 4c896d8f 498bd7 488bcf }
		$sequence_7 = { 4489642428 4489642420 4533c9 4533c0 488d9560110000 33c9 ff15???????? }
		$sequence_8 = { 5f c3 48895c2418 55 56 57 4881ecd0000000 }
		$sequence_9 = { 48ffc3 c60300 493bfa 7403 48ffcf 410fb6d3 4c8d0d27790200 }

	condition:
		7 of them and filesize <1211392
}
