rule win_iisniff_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.iisniff."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.iisniff"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d7dd4 e8???????? 8b45e8 8d5d9c 8bf7 8945bc e8???????? }
		$sequence_1 = { 8b4c240c 51 53 8d8424b4000000 e8???????? }
		$sequence_2 = { 56 83c710 e8???????? 59 }
		$sequence_3 = { 8d742434 e8???????? 33db 6aff }
		$sequence_4 = { 83c404 39bc24d8000000 7210 8b8424c4000000 }
		$sequence_5 = { 59 59 e9???????? 33ff eb90 56 }
		$sequence_6 = { 56 8bcf e8???????? 8b442460 3bf0 770c 6aff }
		$sequence_7 = { 8d4c0c50 6a02 e8???????? 397c2414 0f8db1feffff }
		$sequence_8 = { ff704c e8???????? 59 83f8ff 0f852cffffff }
		$sequence_9 = { e8???????? 3bf0 7429 8b542418 4e ebd9 837c240c10 }
		$sequence_10 = { 6a03 68000000c0 68???????? ff15???????? 6a02 }
		$sequence_11 = { 889c24c4000000 39bc24f4000000 7210 8b8424e0000000 50 e8???????? 83c404 }
		$sequence_12 = { e8???????? 8b442414 8b4004 6a0a 8d440418 50 }
		$sequence_13 = { 50 8975ec e8???????? 8975fc 807de800 7507 be04000000 }
		$sequence_14 = { 51 8d842434010000 50 894c2418 }

	condition:
		7 of them and filesize <1441792
}
