rule win_unidentified_041_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_041."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_041"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 50 53 e8???????? 83c430 33f6 eb24 837c245408 }
		$sequence_1 = { 7415 8d4710 50 ff750c e8???????? 84c0 7505 }
		$sequence_2 = { 59 85db 7429 6a06 33c0 8bfb 33f6 }
		$sequence_3 = { 7406 8b11 51 ff5208 8bc6 e8???????? c3 }
		$sequence_4 = { 58 668906 83c602 8b0c9590234800 8a45f8 6a0a 88441905 }
		$sequence_5 = { d1e9 f3ab 13c9 66f3ab 8b550c 8b4df8 33f6 }
		$sequence_6 = { ff75e0 e8???????? 8b45f0 83c418 2b06 8bce c1f802 }
		$sequence_7 = { ff5748 85c0 0f889e050000 8b8540fdffff 6aff 50 8b08 }
		$sequence_8 = { 8945f4 668b440da4 6633840d78ffffff 6689440dd0 83c102 83f92a 72e6 }
		$sequence_9 = { 0fbec2 0fbe80e8be4600 83e00f eb02 33c0 8bbdbcfdffff 0fbebcc708bf4600 }

	condition:
		7 of them and filesize <1097728
}
