rule win_windealer_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.windealer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.windealer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff15???????? 85c0 7407 50 ff15???????? 6a01 }
		$sequence_1 = { 668b91d2070000 8a89d0070000 52 51 }
		$sequence_2 = { 53 56 57 68da070000 }
		$sequence_3 = { 56 e8???????? 83c410 8b4610 }
		$sequence_4 = { 6a04 50 6a04 68???????? 68???????? }
		$sequence_5 = { 6a00 ff15???????? 85c0 7407 50 ff15???????? 6a01 }
		$sequence_6 = { 8b4d08 668b91d2070000 8a89d0070000 52 }
		$sequence_7 = { 6a01 50 56 e8???????? 83c410 8bc7 }
		$sequence_8 = { 50 56 e8???????? 83c410 8b4618 }
		$sequence_9 = { 56 57 68da070000 e8???????? }

	condition:
		7 of them and filesize <770048
}
