rule win_coinminer_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.coinminer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.coinminer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff742420 ff15???????? 83c604 83fe0c }
		$sequence_1 = { 8b04c50c509000 5d c3 55 }
		$sequence_2 = { 897c240c 8bcf 89442408 0bc8 0f84c7000000 8d4c2430 }
		$sequence_3 = { f3a5 f30f7f442460 c644243f00 33c0 }
		$sequence_4 = { 8944242c 85c0 0f849c000000 8d4c2438 51 6800100000 }
		$sequence_5 = { 33c0 0f57c0 6689842450070000 33f6 660f13442440 }
		$sequence_6 = { 897de4 85ff 750d 0f57c0 660f1345f8 e9???????? }
		$sequence_7 = { 6a00 ff15???????? 8bf0 85f6 7420 6a00 8d45f8 }
		$sequence_8 = { 83ec0c 57 6a00 6a00 6a03 6a00 6a01 }
		$sequence_9 = { 50 ff742420 ff15???????? 8b7c242c 33f6 }

	condition:
		7 of them and filesize <1523712
}
