rule win_cloudeye_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.cloudeye."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cloudeye"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83c002 668b1c08 668b140e 6639d3 75e4 83e902 83f900 }
		$sequence_1 = { 7545 66f7c14179 685595db6d e8???????? }
		$sequence_2 = { e8???????? 5f 59 83c628 41 3b8f04080000 75a8 }
		$sequence_3 = { 7408 0185f4000000 eba4 85d8 }
		$sequence_4 = { 89f8 0500080000 50 6aff }
		$sequence_5 = { 6685d2 e8???????? 84ef 80fd37 57 e8???????? 58 }
		$sequence_6 = { c3 38ed 817e24200000e0 7473 }
		$sequence_7 = { 668b00 6631c8 39c8 6631c3 6681fb4d5a 7407 6639c1 }
		$sequence_8 = { 0fbae11f 0f82d63c0000 61 0faee8 0f31 0faee8 c1e220 }
		$sequence_9 = { 75e4 83e902 83f900 7deb ff742404 }

	condition:
		7 of them and filesize <90112
}
