rule win_devopt_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.devopt."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.devopt"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff75f0 ff15???????? 8b45e8 8b55e0 29d0 8b55f4 894258 }
		$sequence_1 = { e8???????? c705????????00000000 807d8800 7502 eb2a 833d????????00 7502 }
		$sequence_2 = { ff75f8 ff75fc ff15???????? 8945f0 eb07 c745f001000000 8b45f0 }
		$sequence_3 = { eb2c 8b45fc 8b55fc 8b12 ff92bc040000 83f800 7d02 }
		$sequence_4 = { ff13 8975fc 89f2 89827c010000 ba???????? 8910 ba???????? }
		$sequence_5 = { f68574ffffffff 751a 8b45e8 8b55ec 83e001 31d2 750d }
		$sequence_6 = { 8b45e4 8d4001 8945e4 8d7600 8b45e4 8d40ff 8945e4 }
		$sequence_7 = { ff91dc000000 8b45f8 8b90f0000000 8b45fc 8b4dfc 8b09 ff91f4000000 }
		$sequence_8 = { 8d4584 ba00000000 e8???????? 8d4588 50 8b4d84 85c9 }
		$sequence_9 = { ff9284010000 89c3 ba01000000 89d8 ff5368 8945e4 31c0 }

	condition:
		7 of them and filesize <4645888
}
