rule win_prestige_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.prestige."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.prestige"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bf9 8b4d10 3bd0 7f2c 7c04 3bc8 7326 }
		$sequence_1 = { 5e c9 c20400 8b01 ff5018 8bd0 8b0a }
		$sequence_2 = { c706???????? c74604???????? 894664 c7466805000000 e8???????? 83c414 85c0 }
		$sequence_3 = { c60006 66894808 eb48 8b4508 c60007 ebaa 8b4508 }
		$sequence_4 = { 0f454540 034558 51 50 8d4504 50 e8???????? }
		$sequence_5 = { 8b4df4 64890d00000000 8be5 5d c3 8bf0 c745c000000000 }
		$sequence_6 = { 8b01 56 ff5020 8b07 8bcf ff90a8000000 6a01 }
		$sequence_7 = { 57 8d1c85a00c4b00 8b03 90 8b15???????? 83cfff 8bca }
		$sequence_8 = { 3b4314 7744 6a06 59 8bf3 f3a5 8b7de8 }
		$sequence_9 = { 803d????????00 750d e8???????? c605????????01 90 6a08 c705????????04ce4600 }

	condition:
		7 of them and filesize <1518592
}
