rule win_xorist_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.xorist."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.xorist"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7529 663bc3 751e 0fb7447dfe }
		$sequence_1 = { 6a04 ff7654 ff7650 e8???????? }
		$sequence_2 = { 8d48f9 8954241c 83e10f c1c205 }
		$sequence_3 = { 57 8d7c240c 8907 33c0 }
		$sequence_4 = { 034c241c 2bc3 1b4c2424 2b442420 }
		$sequence_5 = { 117e04 5f 5e 5b }
		$sequence_6 = { 8b4c2418 d1c2 8914ae 8b6c2420 }
		$sequence_7 = { 6a08 58 6838030000 89461c }

	condition:
		7 of them and filesize <1402880
}
