rule win_miragefox_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.miragefox."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.miragefox"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 50 e8???????? 83c424 8d85f877ffff b9???????? 8975fc }
		$sequence_1 = { ffd6 ff750c 8bf0 57 }
		$sequence_2 = { 68???????? 50 e8???????? 8bf8 33db 59 3bfb }
		$sequence_3 = { 89b5087cffff 50 e8???????? 03bd187cffff e9???????? }
		$sequence_4 = { c1f905 83e01f 8b0c8d20f52a00 8d04c0 f644810401 741d }
		$sequence_5 = { 33c0 85db 7e08 000438 40 }
		$sequence_6 = { 8945e8 53 8d85a873ffff 56 50 e8???????? 53 }
		$sequence_7 = { 8b45f0 6808880000 2b45ec 53 }
		$sequence_8 = { 83f8ff 8945fc 0f84e1000000 bf14410000 8d85d4beffff 57 53 }
		$sequence_9 = { 2900 55 8bec 81ec48030000 53 }

	condition:
		7 of them and filesize <286720
}
