rule win_vidar_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.vidar."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vidar"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 05c39e2600 894114 c1e810 25ff7f0000 c3 e8???????? 8b486c }
		$sequence_1 = { 7202 8b00 8d8d68fdffff 51 50 }
		$sequence_2 = { 8b7508 33db 895dd0 c746140f000000 895e10 8975cc }
		$sequence_3 = { 8b8648af0100 c1e803 038644af0100 5e 5d c3 }
		$sequence_4 = { 5f c6043300 8bc6 5e 5b c20400 }
		$sequence_5 = { 89b55cfdffff 89bd60fdffff 8d450c 50 }
		$sequence_6 = { d9e0 d99d00ffffff d98500ffffff d91c24 }
		$sequence_7 = { 740a b800000500 e9???????? 57 }
		$sequence_8 = { 895dfc e8???????? 83781408 c645fc01 }
		$sequence_9 = { 8b7508 33ff 89b55cfdffff 89bd60fdffff }
		$sequence_10 = { 56 8b742408 8b865caf0100 57 }
		$sequence_11 = { 5e c20400 ff742408 e8???????? 59 83f8ff 7503 }
		$sequence_12 = { c9 c3 8b542408 85d2 7503 33c0 c3 }
		$sequence_13 = { 83781410 7202 8b00 50 8b45a0 }
		$sequence_14 = { 50 ff15???????? 8b4da0 8901 }
		$sequence_15 = { 53 68???????? 6802000080 ff15???????? 85c0 751b }
		$sequence_16 = { c1e004 8bf0 0fbe4301 50 }
		$sequence_17 = { 68???????? e8???????? 59 83f820 }
		$sequence_18 = { 50 6a09 53 68???????? }
		$sequence_19 = { 50 0fb605???????? 50 6a01 }
		$sequence_20 = { 399e70af0600 7514 c78678af060001000000 c78670af060000000100 68fcff0100 8d8670af0400 }
		$sequence_21 = { 53 50 899e6caf0600 e8???????? }
		$sequence_22 = { 895df0 8d45f0 50 6a09 }
		$sequence_23 = { 0fbe4301 50 8bc1 50 }
		$sequence_24 = { 53 68???????? 8d8da8000000 e8???????? }
		$sequence_25 = { 741d ff75f0 ff15???????? 895df0 395df0 740c }
		$sequence_26 = { 68fcff0100 8d8670af0400 53 50 }
		$sequence_27 = { c3 55 8bec 83ec0c 8365fc00 8365f400 8365f800 }
		$sequence_28 = { 8910 8b4120 8910 8b4130 8910 c3 56 }
		$sequence_29 = { 8d852cffffff 50 8d459c 50 }
		$sequence_30 = { c20400 56 8bf1 e8???????? 6a00 ff74240c 8bce }
		$sequence_31 = { 0faf450c 50 e8???????? 59 }
		$sequence_32 = { 8b4508 8906 8b450c 894608 8b4510 }
		$sequence_33 = { e8???????? c9 c3 55 8bec 83ec18 8b450c }
		$sequence_34 = { 50 ff15???????? 6a1a e8???????? }
		$sequence_35 = { 6860ea0000 6a00 ff15???????? 50 ff15???????? }
		$sequence_36 = { ff15???????? 59 59 50 6a06 }
		$sequence_37 = { 5f c21000 8bff 55 8bec 6a0a 6a00 }
		$sequence_38 = { e8???????? 83c410 85c0 7404 6a99 ebcc }
		$sequence_39 = { 83e03f 03d2 897110 894104 8911 5e c3 }
		$sequence_40 = { 80780800 7404 33c0 40 c3 33c0 }
		$sequence_41 = { dd1c24 83ec08 dd4508 dd1c24 6a0b 6a10 e8???????? }
		$sequence_42 = { dd4508 dd1c24 6a0b 6a08 e8???????? 83c41c }
		$sequence_43 = { eb0b 8b45f4 0500040000 8945f4 }
		$sequence_44 = { 8bc6 5e c3 56 8bf1 6a08 }
		$sequence_45 = { 8bc6 5e c20800 8b3f 85ff 7426 }
		$sequence_46 = { 8bc6 5e c3 8b0a 80790d00 750c }

	condition:
		7 of them and filesize <4751360
}
