rule win_herpes_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.herpes."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.herpes"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7731 0fb690f87b4000 ff2495e07b4000 68???????? eb21 68???????? eb1a }
		$sequence_1 = { 50 51 8d95fcfbffff 52 ff15???????? 8d85fcfbffff 8d5001 }
		$sequence_2 = { 8bb57cffffff e9???????? 8bb578ffffff e9???????? 8b542408 8d420c }
		$sequence_3 = { ff7594 c745905a000000 ff15???????? 85c0 751d }
		$sequence_4 = { 8b95e8fcffff 8b3d???????? 8d8decfcffff 51 6a00 6a00 6a04 }
		$sequence_5 = { e8???????? 8d8424b0090000 50 e8???????? 83c404 ff15???????? 85c0 }
		$sequence_6 = { e9???????? 8db5c0fcffff e9???????? 8db5c0fcffff e9???????? 8bb580fcffff }
		$sequence_7 = { 83c404 5e 5d c20400 83ff72 7512 }
		$sequence_8 = { 720d 8b442410 50 e8???????? 83c404 8bce }
		$sequence_9 = { 57 ff15???????? 83c410 81c668100000 56 8d95f8feffff 68???????? }

	condition:
		7 of them and filesize <319488
}
