rule win_synflooder_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.synflooder."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.synflooder"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff35???????? ff15???????? 85c0 7442 8b7df4 85ff }
		$sequence_1 = { 83e61f 8d3c8520fc4000 8b07 c1e606 }
		$sequence_2 = { 750b 56 e8???????? 59 85c0 7407 }
		$sequence_3 = { e8???????? 83c408 8b542420 52 68???????? e8???????? }
		$sequence_4 = { 53 56 57 7408 33c0 40 e9???????? }
		$sequence_5 = { c7465c20b04000 83660800 33ff 47 }
		$sequence_6 = { 55 8bec 81ec98050000 a1???????? 33c5 8945fc 8d8568faffff }
		$sequence_7 = { 8bf0 89742414 83feff 7524 68???????? e8???????? 83c404 }
		$sequence_8 = { ff15???????? 83f8ff 7524 68???????? e8???????? 83c404 }
		$sequence_9 = { 33db 85db 7466 8d45f4 50 ff75f8 53 }

	condition:
		7 of them and filesize <163840
}
