rule win_bhunt_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.bhunt."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bhunt"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 1dcd1e66b1 1dcc7bc13d e23c 37 5d c81d949f a4 }
		$sequence_1 = { a2???????? 9a05fcd0c3ff9b 2f a4 6940287c3c0e30 6448 8c28 }
		$sequence_2 = { 3bcb 0f8210010000 83f80f 0f8707010000 7209 83f9e0 0f87fc000000 }
		$sequence_3 = { 0f85b4010000 68???????? ebba 8b4510 5f e8???????? }
		$sequence_4 = { ff7508 e8???????? 3bf3 59 59 7d0f 68???????? }
		$sequence_5 = { f6d5 40 0f9cc7 4d 0fb7ef 5f 41 }
		$sequence_6 = { 85c0 7c0b 8b490c 6bc018 8b0408 eb05 b8???????? }
		$sequence_7 = { d4d1 f779f9 4a 350802d56a 1e 085f44 41 }
		$sequence_8 = { ff75f4 6a33 53 e8???????? 6afe 68???????? 6a02 }
		$sequence_9 = { 7e7b eb03 8b458c 3b4590 8b854cffffff 0f83ff000000 8b5594 }

	condition:
		7 of them and filesize <19161088
}
