rule win_unidentified_037_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.unidentified_037."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_037"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 85c0 a3???????? 740c 8b4c2408 8b542404 51 52 }
		$sequence_1 = { 33c0 33d2 33ff 8a0c1f 80f920 7405 80f930 }
		$sequence_2 = { 7506 8b15???????? 8d8424b8040000 52 50 ff15???????? }
		$sequence_3 = { 8a56ff 83e23f 41 4d 8a82d00c0110 8841ff 759c }
		$sequence_4 = { 8b4d20 8b5500 8b4504 8bb424f0040000 51 52 50 }
		$sequence_5 = { ff15???????? 84c0 742d 8b4608 8b5604 8d8dccfcffff }
		$sequence_6 = { 8841ff 759c 5d eb04 8b742410 85ff 7667 }
		$sequence_7 = { 743e 80f920 7439 80f930 7c0d 80f937 7f08 }
		$sequence_8 = { 8b5c2408 8b4314 83f8ff 0f84b1000000 c1e005 8bd0 a1???????? }
		$sequence_9 = { 5e 8b8c241c100000 64890d00000000 81c428100000 c3 83c1fe }

	condition:
		7 of them and filesize <167936
}
