rule win_vawtrak_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.vawtrak."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vawtrak"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a01 ff35???????? 6a04 6a01 }
		$sequence_1 = { 6a04 6a01 50 ff15???????? 85c0 }
		$sequence_2 = { 6a00 6a00 e8???????? 50 ff15???????? }
		$sequence_3 = { 40 8901 81e900100000 75f6 }
		$sequence_4 = { ba00ff0000 8bc1 23c2 3bc2 }
		$sequence_5 = { c3 56 be???????? 33c0 }
		$sequence_6 = { 56 ff15???????? eb01 47 }
		$sequence_7 = { 85c0 7516 c705????????02000000 c705????????03000000 eb14 c705????????01000000 }
		$sequence_8 = { 7515 2105???????? c705????????04000000 e9???????? }
		$sequence_9 = { a802 7407 e8???????? eb09 a804 7405 }
		$sequence_10 = { ff15???????? a3???????? 85c0 74e7 }
		$sequence_11 = { 7528 68???????? ff15???????? 85c0 7504 33c0 }
		$sequence_12 = { 6a08 68???????? 56 ffd7 85c0 }
		$sequence_13 = { 59 57 8bf0 ff15???????? 8bc6 }
		$sequence_14 = { e8???????? 33d2 b9ff3f0000 f7f1 }
		$sequence_15 = { 8bc6 8703 3bc6 74f8 }
		$sequence_16 = { 56 6a04 53 57 }
		$sequence_17 = { 80ea61 eb0a 8d42bf 3c0f }
		$sequence_18 = { c1e910 e9???????? 8ac1 c1e904 c0e004 }
		$sequence_19 = { 8ac8 240f 80e1f0 80c110 32c8 }
		$sequence_20 = { 3c41 7c11 3c46 7f0d }
		$sequence_21 = { 2bca 3bcf 7c2e 03fa 4883c602 03ea 03ff }
		$sequence_22 = { 488905???????? 4885c0 74dd 488bd3 }
		$sequence_23 = { 4883ec30 488bf9 e8???????? b910000000 488bf0 e8???????? 488bd8 }
		$sequence_24 = { 4885c0 74e3 448bce 4c8bc7 }

	condition:
		7 of them and filesize <1027072
}
