rule win_gophe_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.gophe."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gophe"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 833902 0f94c0 84c0 7407 }
		$sequence_1 = { 6685c0 75f4 a1???????? 8907 6a20 }
		$sequence_2 = { 894108 418b4104 89410c 4983f801 }
		$sequence_3 = { 55 8bec 8b4508 85c0 7509 b803000000 }
		$sequence_4 = { c744242880000000 c744242003000000 4533c9 4533c0 ba00000080 ff15???????? 488bf8 }
		$sequence_5 = { 8b05???????? 85c0 0f85a9000000 4533c9 }
		$sequence_6 = { 83781408 7202 8b00 51 6a00 }
		$sequence_7 = { 6a00 68???????? 6a00 c605????????01 }
		$sequence_8 = { 68c8000000 e8???????? 68c8000000 6a00 50 8986dc000000 e8???????? }
		$sequence_9 = { 68e0000000 e8???????? 83c404 8945f0 }
		$sequence_10 = { c744242880000008 c744242003000000 4533c9 ba00000080 }
		$sequence_11 = { 90 4c8b45b8 4d8bc8 4d8b00 }
		$sequence_12 = { 68???????? 8d85fcfdffff 68f4010000 50 }
		$sequence_13 = { 894104 418b01 894108 418b4104 }
		$sequence_14 = { 5d c3 8b07 85c0 7506 }
		$sequence_15 = { 85c0 7522 8b4528 c1e008 }

	condition:
		7 of them and filesize <1582080
}
