rule win_advisorsbot_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.advisorsbot."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.advisorsbot"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bc1 2bc2 d1e8 03c2 c1e808 }
		$sequence_1 = { 8bc2 33d2 c1e809 f7f1 }
		$sequence_2 = { 8bc2 33d2 c1e808 f7f1 }
		$sequence_3 = { b809384519 f7e1 2bca d1e9 03ca }
		$sequence_4 = { d1e8 03c2 33d2 c1e809 }
		$sequence_5 = { 8bc2 c1e809 33d2 f7f1 }
		$sequence_6 = { 8b442408 8b4c2408 33d2 f7f1 }
		$sequence_7 = { 8bca f7e2 2bca d1e9 }
		$sequence_8 = { b839811338 f7e1 8bc1 2bc2 }
		$sequence_9 = { d1e9 03ca c1e907 2bc1 }
		$sequence_10 = { d1e9 03ca c1e909 33c8 }
		$sequence_11 = { 8bc2 33d2 c1e804 f7f1 }
		$sequence_12 = { 8bca f7e2 8bc1 2bc2 }
		$sequence_13 = { 5e 5d 0fb7c1 5b }
		$sequence_14 = { 5f 5e 5d 0fb7c2 5b }
		$sequence_15 = { 8b442414 8b4c2414 33d2 f7f1 }
		$sequence_16 = { 0fb7c1 0fb7ca 33d2 f7f1 }
		$sequence_17 = { 0fb6c0 0fb6c9 33d2 f7f1 }
		$sequence_18 = { 0fb6c1 0fb6ca 33d2 f7f1 }

	condition:
		7 of them and filesize <434176
}
