rule win_backswap_auto_alt_2
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.backswap."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.backswap"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { eb1c 85c9 7508 3bdf }
		$sequence_1 = { c21000 83f0ff 5e 5f 5a }
		$sequence_2 = { 4b eb1c 85c9 7508 3bdf }
		$sequence_3 = { 33c9 e9???????? b32a 397d14 7412 47 8a07 }
		$sequence_4 = { 33c9 33d2 8bdf 4b eb1c 85c9 }
		$sequence_5 = { ff4508 8bfb 3bd3 0f8572ffffff 33c9 }
		$sequence_6 = { 3c3f 74c4 3c2a 7508 8bdf 897508 4e }
		$sequence_7 = { f366a5 59 5f 5e c9 c20c00 55 }
		$sequence_8 = { 7404 8bce 8bd3 397d14 0f8e99000000 39750c 7e7b }
		$sequence_9 = { ff4508 8bfb 3bd3 0f8572ffffff 33c9 e9???????? }

	condition:
		7 of them and filesize <122880
}
