rule win_murkytop_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.murkytop."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.murkytop"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ffd6 8b4dec 51 ffd6 5f 5e }
		$sequence_1 = { 3dea000000 7544 68???????? e8???????? }
		$sequence_2 = { 50 68???????? e8???????? 83c408 83ff06 7c3d 8b4614 }
		$sequence_3 = { e8???????? 47 3b7d08 0f8c55ffffff 83fb05 7511 6a01 }
		$sequence_4 = { 33ff 56 e8???????? 8bc6 c1f805 8b0485e0f54100 83e61f }
		$sequence_5 = { 51 e8???????? 83c404 8945e8 c645ff01 eb17 395dec }
		$sequence_6 = { 6a01 51 ff15???????? 3bc6 743f 50 ff15???????? }
		$sequence_7 = { 51 ff15???????? 85c0 7405 395df4 7541 ff15???????? }
		$sequence_8 = { eb08 8b4608 e8???????? 47 3b7d08 0f8c55ffffff 83fb05 }
		$sequence_9 = { 3dfeffff3f 0f87d6020000 2bce 40 c1f902 }

	condition:
		7 of them and filesize <294912
}
