rule win_virdetdoor_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.virdetdoor."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.virdetdoor"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8a0407 47 3c7c 0f8583000000 c70645000000 }
		$sequence_1 = { 85c0 75ef 8b5df4 8b45ec 897e04 8a1407 47 }
		$sequence_2 = { 66ab 58 668945f0 0fb786f4010000 50 ff15???????? 668945f2 }
		$sequence_3 = { 837d1c00 8b4514 751a 6a00 ff7508 52 99 }
		$sequence_4 = { 740b c70648000000 e9???????? 6a00 }
		$sequence_5 = { c6410100 0fb64210 83f83a 0f87ce010000 ff24859e414000 c60102 e9???????? }
		$sequence_6 = { 5d c3 53 56 8bf1 832600 c7460401000000 }
		$sequence_7 = { ff15???????? 83c40c 66c70645cc 33c0 66c7460840ff 40 66894604 }
		$sequence_8 = { 83c410 66894606 6685c0 7532 b8ffff0000 eb27 }
		$sequence_9 = { 6bc009 0fb68410a8724000 c1e804 8985c0fdffff 83f808 0f8464ffffff 6a07 }

	condition:
		7 of them and filesize <106496
}
