rule win_cmstar_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.cmstar."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cmstar"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 56 bb04010000 57 53 }
		$sequence_1 = { ff15???????? 8bc6 e9???????? 6a10 8d45d0 }
		$sequence_2 = { 85c0 7504 6a03 eb0d 803b4d }
		$sequence_3 = { 8b45d8 836dfc10 ff75fc 8945e0 8b45dc }
		$sequence_4 = { 8b4dec c1e802 6a04 52 8d0481 50 e8???????? }
		$sequence_5 = { ff15???????? 6a04 e8???????? be00040000 }
		$sequence_6 = { ff15???????? 6a03 58 5f 5e 5b c9 }
		$sequence_7 = { ff75e0 ff30 e8???????? 8b4df8 }
		$sequence_8 = { 50 8b44242c 55 50 ff15???????? 8bf0 }
		$sequence_9 = { 5d 0bc0 5b 81c408060000 c3 }
		$sequence_10 = { ff15???????? 3db7000000 7505 33c0 c20c00 6a00 }
		$sequence_11 = { bf???????? be???????? 88540c18 83c9ff }
		$sequence_12 = { 53 ff15???????? 68???????? 57 ff15???????? 8bf0 83c408 }
		$sequence_13 = { 52 e8???????? 83c40c 8b0d???????? c68424cc12000002 8b11 b9???????? }
		$sequence_14 = { 741e 8a441420 bf???????? 888278420010 83c9ff 33c0 }
		$sequence_15 = { 8bc8 53 83e103 6800000080 f3a4 53 68???????? }

	condition:
		7 of them and filesize <4268032
}
