rule win_mars_stealer_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.mars_stealer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mars_stealer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b15???????? 52 e8???????? 83c40c e8???????? }
		$sequence_1 = { e8???????? 83c40c 6888130000 8d95f0d8ffff 52 e8???????? }
		$sequence_2 = { 8b45f8 c7404800000000 8b4df8 c7417c00000000 837d0800 0f848f000000 8b5508 }
		$sequence_3 = { ff15???????? 83c404 8945e8 8b55e8 8955fc 8b4508 8945e4 }
		$sequence_4 = { 8b148d68654100 8955fc 837dfc00 7427 8b45f4 8b4d08 8b55ec }
		$sequence_5 = { 55 8bec c705????????ac304100 c705????????c4304100 c705????????d4304100 c705????????e4304100 }
		$sequence_6 = { 8bb540fbffff 33c0 f3a7 0f851c020000 6a00 }
		$sequence_7 = { a1???????? 50 8b0d???????? 51 ff15???????? 68???????? 8b15???????? }
		$sequence_8 = { c745dc00000000 c745e000000000 c745e400000000 8d55c4 52 ff15???????? 6a3c }
		$sequence_9 = { e9???????? 6804010000 8d9550e9ffff 52 e8???????? }

	condition:
		7 of them and filesize <219136
}
