rule win_hotwax_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.hotwax."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hotwax"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 4883ec20 488bd9 488d0de0b60000 483bd9 }
		$sequence_1 = { 33c9 33d2 41ff5500 448bd8 85c0 0f85ef020000 8b4500 }
		$sequence_2 = { 8945a0 496344243c 33d2 428b4c2050 41b900300000 c744242040000000 }
		$sequence_3 = { 4885c0 7467 33d2 488bc8 }
		$sequence_4 = { 85c0 0f8596000000 397ddc 0f848d000000 4c8d05247bffff }
		$sequence_5 = { 4885c8 7507 8b0b 4803ca eb11 483bca 7245 }
		$sequence_6 = { c6850205000000 c785e004000043726561 c785e404000074655468 c785e804000072656164 c685ec04000000 }
		$sequence_7 = { 7343 8b471c 458b4d44 4d8b4530 4803c5 }
		$sequence_8 = { ff15???????? 488d4c2468 33d2 41b868050000 83cbff }
		$sequence_9 = { 4c8d0dac7fffff 4c8bd8 4b8b84f9a04b0100 4c895c3040 4b8b84f9a04b0100 498bd6 }

	condition:
		7 of them and filesize <198656
}
