rule win_radrat_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.radrat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.radrat"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d8d1cffffff e8???????? c685f0feffff00 c645fc00 8d4dcc e8???????? c745fcffffffff }
		$sequence_1 = { c6855497ffff01 c645fc01 8d8d58ffffff e8???????? c745fcffffffff 8d4d80 e8???????? }
		$sequence_2 = { 8d8d74ffffff e8???????? 68a0000000 8d8d74ffffff e8???????? 6a30 8d8d74ffffff }
		$sequence_3 = { ff15???????? 8b4df4 894168 8b45f4 837868ff 750d ff15???????? }
		$sequence_4 = { 8d8dd8feffff e8???????? 8d8d0cffffff 51 8d55c4 52 8b45ec }
		$sequence_5 = { e8???????? 8a854c98ffff e9???????? 8b8d24d6ffff 83c15c 51 8b9524d6ffff }
		$sequence_6 = { 8d8d50ffffff 51 e8???????? 83c408 8b9548ffffff 83c258 52 }
		$sequence_7 = { e9???????? 8d4d9c e8???????? c645fc01 8d8d38ffffff 51 8d4d9c }
		$sequence_8 = { 8b4dd8 8b9130010000 52 ff15???????? 8b45d8 c7803001000000000000 8b4dd8 }
		$sequence_9 = { 8d8560fbffff 50 8d8da8fdffff e8???????? 89854cf8ffff 8b8d4cf8ffff 898d48f8ffff }

	condition:
		7 of them and filesize <2080768
}
