rule win_floxif_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.floxif."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.floxif"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 8945d0 837dd0ff 7514 c645b800 8d4d08 e8???????? }
		$sequence_1 = { 2b4d08 c1f904 8b550c 2bd1 52 }
		$sequence_2 = { 8b4d08 c6410301 8b4508 83c004 5f 5e 5b }
		$sequence_3 = { e8???????? 8a4584 5f 5e }
		$sequence_4 = { 8b45fc 50 ff15???????? 85c0 7404 b001 eb04 }
		$sequence_5 = { e8???????? 68???????? e8???????? 83c404 e8???????? a2???????? c745f800000000 }
		$sequence_6 = { a0???????? 85c0 7522 8b8d70feffff 51 8d4dc4 e8???????? }
		$sequence_7 = { e8???????? 8d4d08 e8???????? 8be5 5d c3 55 }
		$sequence_8 = { e8???????? 83ec10 8bf4 6a04 83ec10 8bcc 8d55f0 }
		$sequence_9 = { c645ce13 c645cf0e c645d06b 8d45c0 50 e8???????? 83c404 }

	condition:
		7 of them and filesize <352256
}
