rule win_lightneuron_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.lightneuron."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.lightneuron"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 488b05???????? 488b15???????? 4885c0 4c8bc6 488bcf 480f45d0 }
		$sequence_1 = { b920000000 e8???????? 4889442420 48837c242000 7502 eb70 488b4c2420 }
		$sequence_2 = { eb3e 488b4808 e8???????? 488b7c2460 488bcf ff15???????? 8bf0 }
		$sequence_3 = { b8b0040000 4883c420 5b c3 488b05???????? 488b15???????? 41b802000000 }
		$sequence_4 = { 44891b eb08 488bb42450010000 488b9c2448010000 4885db 0f8498000000 488b9424e0000000 }
		$sequence_5 = { 488b4808 ff15???????? 8d4801 e8???????? 4c8be8 4885c0 740d }
		$sequence_6 = { 410fb6c3 4533b48cc0ed0300 4533b48480d50300 418bc0 45337500 c1e808 }
		$sequence_7 = { 4885c0 488bcf 480f45d8 4c89742438 ff15???????? 4863d0 488d442438 }
		$sequence_8 = { ff15???????? 8b1d???????? 488d0d8eb40300 8935???????? ff15???????? e8???????? 488d0d76b40300 }
		$sequence_9 = { 0fb6442460 8801 488b442470 4883c001 4889442470 eb19 488b842480000000 }

	condition:
		7 of them and filesize <573440
}
