rule win_doppeldridex_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.doppeldridex."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.doppeldridex"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 017c240c 3b5c2408 0f822affffff ff74240c }
		$sequence_1 = { 010c28 8b4e04 42 8d41f8 d1e8 }
		$sequence_2 = { 011483 40 3b06 7cf8 }
		$sequence_3 = { 56 8bd9 8d2c24 85d2 750b }
		$sequence_4 = { 030c24 0fbe01 88442458 85c0 }
		$sequence_5 = { 01500c 833920 751c 8bc1 }
		$sequence_6 = { 01501c 015020 015024 01500c }
		$sequence_7 = { 0306 894218 47 3b7c2408 }
		$sequence_8 = { 893402 897c0204 eb51 8b459c 83c474 5e }
		$sequence_9 = { 898570ffffff 0f840c010000 e9???????? 8b856cffffff 8b8d68ffffff 8d55cc 8d75d0 }
		$sequence_10 = { 66c780000100000b01 83c404 5d c3 55 }
		$sequence_11 = { 8b7e38 897db4 8b7e5c 897db8 8b7e2c 897dbc 8b7e18 }
		$sequence_12 = { 8b4598 8b4d94 8b5590 8b758c 8b3e 83ff00 }
		$sequence_13 = { 8b45cc 8b4dc8 8b55c4 8b75c0 83c0f8 }
		$sequence_14 = { 8b45d0 8b4828 8b5010 8b75e8 39f2 }
		$sequence_15 = { 891424 894c2404 8b4d98 894c2408 e8???????? 8b45b0 8b4804 }

	condition:
		7 of them and filesize <360448
}
