rule win_mokes_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.mokes."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mokes"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff7204 8b5004 51 8bce e8???????? c644244c04 83c40c }
		$sequence_1 = { ff37 8b4d58 e8???????? ff33 8b4d5c e8???????? 8b4d24 }
		$sequence_2 = { f30fe6c0 f20f59cb f20f584850 f20f5cc8 f20f104660 f20f59c3 f20f584650 }
		$sequence_3 = { f00fc101 ff742414 8d44242c 8bce 50 e8???????? 8d4c2428 }
		$sequence_4 = { ff15???????? 85c0 7435 8d942494000000 8d4c2454 e8???????? c68424a802000004 }
		$sequence_5 = { f6c444 7a10 f20f1025???????? f20f11642408 eb48 f20f5905???????? f20f11442408 }
		$sequence_6 = { f6c202 743b 8b442440 83e2fd 89542428 8b08 85c9 }
		$sequence_7 = { ff5014 5f 5e 8be5 5d c3 ff500c }
		$sequence_8 = { ff7610 8d8f9c000000 e8???????? 85c0 7413 8bc8 c1e104 }
		$sequence_9 = { ff5274 85c0 741b 807c241800 b820000000 b910000000 0f45c1 }

	condition:
		7 of them and filesize <18505728
}
