rule win_jupiter_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.jupiter."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.jupiter"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8a4147 884104 8a4146 884105 8b4144 c1f808 884106 }
		$sequence_1 = { c605????????01 66c705????????0101 c605????????01 c605????????01 66c705????????0101 }
		$sequence_2 = { 8b4144 c1f808 884106 8a4144 884107 }
		$sequence_3 = { 884105 8b4144 c1f808 884106 8a4144 }
		$sequence_4 = { 50 6802000000 ff35???????? ff35???????? }
		$sequence_5 = { 66c705????????0101 c605????????01 c605????????01 c605????????01 }
		$sequence_6 = { 884105 8b4144 c1f808 884106 8a4144 884107 }
		$sequence_7 = { c1f808 884106 8a4144 884107 }
		$sequence_8 = { c605????????01 66c705????????0101 c605????????01 c605????????01 }
		$sequence_9 = { 884104 8a4146 884105 8b4144 }

	condition:
		7 of them and filesize <224112
}
