rule win_rm3_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.rm3."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rm3"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { eb0a 8b4138 8b5608 8d5410ff 48 f7d0 23d0 }
		$sequence_1 = { 8b7004 897104 8b4808 ff7004 }
		$sequence_2 = { 56 57 8d740818 8b4508 3b460c }
		$sequence_3 = { 8975f8 8b45f8 83c628 ff4dfc 85c0 7505 }
		$sequence_4 = { 3945fc 759f 5f 5e 5b }
		$sequence_5 = { 3bf8 7609 8b413c 8d5418ff eb0a 8b4138 8b5608 }
		$sequence_6 = { 51 8b483c 03c8 0fb74106 }
		$sequence_7 = { 4f f7d7 23c7 8d7c13ff 4a f7d2 23fa }
		$sequence_8 = { 5f 5e 8bc3 2b45f0 c60300 }
		$sequence_9 = { 57 8bc6 8d9558feffff e8???????? 8b4d10 8984b558feffff }
		$sequence_10 = { 53 56 57 8bd8 8bf9 8db5f0feffff 8bce }
		$sequence_11 = { 5e 8bc6 5e 5b 59 5d }
		$sequence_12 = { 0fc8 8ad5 0fb7ca 51 50 56 6a27 }
		$sequence_13 = { 50 6a00 ffd7 8b45fc 85c0 }
		$sequence_14 = { 83e60b 750f 8b450c 8b4d10 }
		$sequence_15 = { ff4510 56 8bcb 8d9568ffffff }
		$sequence_16 = { 488b0d???????? 33d2 ff15???????? 4c8b842490000000 488b0d???????? 33d2 }
		$sequence_17 = { 448d440042 33d2 ff15???????? 4885c0 488bd8 7468 488bd0 }
		$sequence_18 = { 488b0d???????? 33d2 41b800100000 ff15???????? 4885c0 488bf0 0f84a9000000 }
		$sequence_19 = { 488d4c2450 498bd8 ff15???????? 4c8b1b 8364242800 4c015c2450 }
		$sequence_20 = { 448bc6 488bd7 488bc8 8bde e8???????? }
		$sequence_21 = { 4c8d4c2444 4c8d442440 8bd6 896c2444 }
		$sequence_22 = { ff15???????? 413bc5 740e 488bcf ff15???????? }
		$sequence_23 = { 488bcf ff15???????? 418bdd eb08 }
		$sequence_24 = { 898570ffffff 898d74ffffff 0f8563ffffff 8b8574ffffff 81c4a0000000 5e 5f }
		$sequence_25 = { 8985bcfbffff ffd1 8b0d???????? 8b95e8fbffff 52 8985b8fbffff }
		$sequence_26 = { 31d2 8b75f0 89462c 890c24 c744240400000000 8955d0 e8???????? }
		$sequence_27 = { 8b4db0 894c2408 e8???????? 8b45b4 8b483c }
		$sequence_28 = { 8d45d4 83c001 8945b0 8b45b0 }
		$sequence_29 = { 8955f0 8945ec 744c 8b45f8 83f800 }
		$sequence_30 = { 88d3 88df 80ef0a 89459c 894d98 897594 897d90 }
		$sequence_31 = { 8955f0 893424 c744240400000000 c744240878000000 }
		$sequence_32 = { 0f8599000000 eb00 8b45ac 8b4d94 01c8 }
		$sequence_33 = { e8???????? 8b4df0 894130 8b4154 890424 894c2404 }
		$sequence_34 = { b9ffffffff 83f800 898550fdffff 898d4cfdffff 0f849b000000 }
		$sequence_35 = { 8b75ec 01d6 83c602 89d7 }
		$sequence_36 = { 68???????? ffd0 8b0d???????? 6a00 }
		$sequence_37 = { 891424 894c2404 8945f0 e8???????? 8d0d84308702 }
		$sequence_38 = { 80e301 0fb6c3 89854cfdffff 8b854cfdffff 81c4d0020000 5f 5b }
		$sequence_39 = { 8b4588 8b4dc4 8a1401 89c6 83c601 }

	condition:
		7 of them and filesize <221184
}
