rule win_winordll64_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.winordll64."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.winordll64"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 41b803000000 488d0d205e0000 4533c9 ba00000040 4489442420 ff15???????? }
		$sequence_1 = { e8???????? 48ffcf c6841f2e03000000 75f3 }
		$sequence_2 = { 7505 498bfe eb0b 488bcb e8???????? 488bf8 }
		$sequence_3 = { 486307 48c1e006 4c8d543808 498bcf }
		$sequence_4 = { 85c0 7402 ffc3 33c9 4c8d442430 }
		$sequence_5 = { 7677 488d730c 4183fe64 7d6d 837ef802 754c 0fb70e }
		$sequence_6 = { 4983cdff 4c8be0 493bc5 0f843a010000 }
		$sequence_7 = { 4c8d4c8f04 498bce 8d441202 4863d0 85c0 740f 8a040e }
		$sequence_8 = { 4883f8ff 7507 33c0 e9???????? 488bc8 ff15???????? 4883c9ff }
		$sequence_9 = { 8918 e9???????? e8???????? 488d0dcf3f0000 4c8bcd 448b20 }

	condition:
		7 of them and filesize <278528
}
