rule win_bunitu_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.bunitu."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bunitu"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 0bc0 7415 40 7412 48 50 }
		$sequence_1 = { 6a00 68bf0a0000 ff15???????? 33c0 40 40 50 }
		$sequence_2 = { b968080000 f3aa 5f 8b4508 }
		$sequence_3 = { ff750c ff7508 ff15???????? 59 5d 5a }
		$sequence_4 = { ffb524fdffff e8???????? eb12 6a08 68???????? }
		$sequence_5 = { 8d953cfeffff b9???????? 52 6800000100 }
		$sequence_6 = { bf04000000 8b9d44feffff 56 53 ffb530feffff e8???????? }
		$sequence_7 = { 8b7d08 8b750c 8b4d10 49 ac 3c00 7405 }
		$sequence_8 = { 5e 8d953cfeffff b9???????? 52 6800000100 }
		$sequence_9 = { 50 ff75ec e8???????? 0bc0 7e18 50 }

	condition:
		7 of them and filesize <221184
}
