rule win_onhat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.onhat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.onhat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d842444020000 52 50 c68424d90000004e c68424da00000054 }
		$sequence_1 = { 68???????? e8???????? 83c404 b804000080 5f 5e 5d }
		$sequence_2 = { c684242601000052 c684242701000000 c684249400000025 c684249500000064 c684249600000000 ffd6 }
		$sequence_3 = { 896c241c f3ab 8b8c2438010000 896c2420 51 88542428 e8???????? }
		$sequence_4 = { 8dbc2481020000 c684248002000000 f3ab 8b4c2440 8d542478 }
		$sequence_5 = { 8844241f c644242056 884c2421 88442422 88542423 }
		$sequence_6 = { 85c0 7d1d 50 68???????? e8???????? 8b4c243c 51 }
		$sequence_7 = { 8b4c2464 8d942488000000 66ab aa 51 }
		$sequence_8 = { 8d7c2409 88542408 f3ab 8b8c240c200000 88542406 66ab }
		$sequence_9 = { 8b542440 52 8b542428 50 8b442464 50 }

	condition:
		7 of them and filesize <57344
}
