rule win_unidentified_099_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_099."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_099"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { f3aa 498bf8 488d05cee3ffff 488bd3 6666660f1f840000000000 0fb68c0290f00100 4883c203 }
		$sequence_1 = { e8???????? c70016000000 eb10 483bf3 }
		$sequence_2 = { c705????????01000000 b808000000 486bc000 488d0d1ab30100 8b542430 48891401 }
		$sequence_3 = { 4c8ba424c8030000 488bb424c0030000 488b8d80020000 4833cc e8???????? 488b9c24d0030000 4881c490030000 }
		$sequence_4 = { 0f8276ffffff 488b4c2460 4833cc e8???????? 4c8d5c2470 498b5b18 }
		$sequence_5 = { 498bf8 488bd3 420fb68c3ad0eb0100 4883c203 880f 488d7f01 4883fa72 }
		$sequence_6 = { 488bf9 4c8d0dace50000 33c9 4c8d059be50000 488d159ce50000 e8???????? 488bd8 }
		$sequence_7 = { 488d7b38 488d05b2100100 483947f0 741a 488b0f 4885c9 7412 }
		$sequence_8 = { 4c8d442448 488d9500030000 488d8d10040000 e8???????? 80387b 0f8403010000 }
		$sequence_9 = { 0f1f8000000000 8bd3 4c8d4c2444 4903d6 }

	condition:
		7 of them and filesize <314368
}
