rule win_moonwind_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.moonwind."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.moonwind"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b11 83c104 c1ea08 881430 8a51fc 40 881430 }
		$sequence_1 = { 8b5dfc 895de4 8b5de4 66c7030200 8b5dfc 83c308 895de4 }
		$sequence_2 = { 53 e8???????? 83c404 8b5d08 8b1b 81c390000000 895dec }
		$sequence_3 = { e8???????? 83c404 83c734 33d2 83c8ff 8917 885704 }
		$sequence_4 = { b801000000 eb05 b800000000 85c0 0f842f000000 8b5d08 8b1b }
		$sequence_5 = { bbdc090000 e8???????? 83c410 8945b8 8b5dbc 85db 7409 }
		$sequence_6 = { ff75fc 6801000000 bb68010000 e8???????? 83c410 8945f0 68???????? }
		$sequence_7 = { 8965f4 8b5d08 ff33 6801000000 ff75f8 ff15???????? }
		$sequence_8 = { 50 e8???????? 8d7c2434 83c9ff 33c0 83c40c f2ae }
		$sequence_9 = { dc25???????? dd5dc4 6801030080 6a00 682c000000 dd45c4 e8???????? }

	condition:
		7 of them and filesize <1417216
}
