rule win_void_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.void."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.void"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83ec40 a1???????? 33c4 8944243c 8b442444 53 8b5c2450 }
		$sequence_1 = { 51 52 8b5608 8bc8 c1e202 e8???????? 83c408 }
		$sequence_2 = { 8a4605 8bce 3a45e7 7505 c6032b eb0f e8???????? }
		$sequence_3 = { 50 8d4f30 c645fc11 e8???????? 8d8da4feffff e8???????? 8d8d38020000 }
		$sequence_4 = { 5f 5b 33cc e8???????? 83c430 c20400 8d4c240c }
		$sequence_5 = { 3bde 0f42de 53 8bcf e8???????? 8bd6 89442414 }
		$sequence_6 = { 68???????? eb07 6a06 68???????? 8d4dd8 e8???????? 837dec10 }
		$sequence_7 = { 7421 83fb10 8d45d8 0f43c6 0fbe4007 50 e8???????? }

	condition:
		7 of them and filesize <2744320
}
