rule win_murofet_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.murofet."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.murofet"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d461c 55 50 ff15???????? }
		$sequence_1 = { e8???????? 33c0 c20400 55 8bec 83ec68 53 }
		$sequence_2 = { a2???????? 84c0 7510 e8???????? }
		$sequence_3 = { ff15???????? c6443eff00 83f8ff 7509 56 }
		$sequence_4 = { 72e5 e8???????? a2???????? 84c0 7510 }
		$sequence_5 = { 84c0 7510 e8???????? 3c04 73ce b002 a2???????? }
		$sequence_6 = { 84c0 7510 e8???????? 3c04 73ce b002 }
		$sequence_7 = { e8???????? e8???????? 3c02 72e5 e8???????? }
		$sequence_8 = { eb43 be30750000 56 6a04 }
		$sequence_9 = { fec2 8816 e8???????? 0fb6c0 99 f7ff }

	condition:
		7 of them and filesize <622592
}
