rule win_mewsei_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.mewsei."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mewsei"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7409 50 e8???????? 83c404 46 3bf3 72eb }
		$sequence_1 = { 895df4 8b5dfc 8dbc1f4239faff 8b5df4 }
		$sequence_2 = { c1e810 33d2 25ff7f0000 f7f1 80c230 }
		$sequence_3 = { ffd6 a1???????? 85c0 7405 6aff }
		$sequence_4 = { 0bf3 0fb65804 c1e608 0bf3 8b5df8 33df 235dfc }
		$sequence_5 = { 8b7df8 337df4 8b5df0 237dfc 337df8 037de0 8dbc1f2ac68747 }
		$sequence_6 = { 85c0 750c 6a01 e8???????? 83c404 ebe7 894610 }
		$sequence_7 = { 0fb6581c 0bfb 897974 897de8 8b7df0 }
		$sequence_8 = { 03de 8dbc3b44eabea4 8b5df4 c1c704 03fb 897dfc 8b7df8 }
		$sequence_9 = { 8bf8 897df8 c70300000000 8d7701 8d4900 56 e8???????? }

	condition:
		7 of them and filesize <504832
}
