rule win_zeus_mailsniffer_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.zeus_mailsniffer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus_mailsniffer"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 57 8d85fcfaffff 50 8d8580fdffff 50 ff15???????? 85c0 }
		$sequence_1 = { 8bc7 8945e4 8b55f4 52 53 e8???????? }
		$sequence_2 = { 8975f0 83feff 0f8496000000 6a08 8d45e4 53 50 }
		$sequence_3 = { 59 7410 48 7408 48 7556 8d7dec }
		$sequence_4 = { 85ff 758c 53 e8???????? 59 ff742410 }
		$sequence_5 = { 57 e8???????? 8945ec 85c0 0f847c010000 }
		$sequence_6 = { 6804010000 8d84246c010000 50 53 ff15???????? 85c0 }
		$sequence_7 = { ff750c ff7508 ff15???????? 83c410 89442410 85c0 0f8f4affffff }
		$sequence_8 = { 83c410 3bfb 0f84d5000000 03b424dc040000 56 ffb424f8040000 89b424e0040000 }
		$sequence_9 = { 59 bf04010000 57 8d84249c050000 50 8d842434040000 }

	condition:
		7 of them and filesize <368640
}
