rule win_common_magic_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.common_magic."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.common_magic"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7235 8b95ccfeffff 8d0c4d02000000 8bc2 81f900100000 }
		$sequence_1 = { 83f908 7231 8b9588fdffff 8d0c4d02000000 8bc2 81f900100000 7210 }
		$sequence_2 = { c78570ffffff07000000 c7458c4f007600 c7459065007200 c7459461006c00 c745986c002e00 }
		$sequence_3 = { 0fb644012e 0fbe8058774100 40 8945cc 2b45dc 8945d4 3bc2 }
		$sequence_4 = { 64a300000000 8bf1 8975ac c745fc00000000 8d45e0 8975a4 c745a800000000 }
		$sequence_5 = { 8d85c4fdffff 50 56 ff15???????? 85c0 0f85a4feffff }
		$sequence_6 = { c645fc08 8b8d74ffffff 85c9 747a 8b9578ffffff 51 e8???????? }
		$sequence_7 = { 8b4e10 85c9 7414 49 8bc6 }
		$sequence_8 = { c785acfdffff00000000 668985acfdffff 8d85e8fdffff c785bcfdffff00000000 8d5002 c785c0fdffff07000000 668b08 }
		$sequence_9 = { 83f907 7726 8d3409 898d3cffffff 56 50 8d852cffffff }

	condition:
		7 of them and filesize <212992
}
