rule win_godzilla_loader_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.godzilla_loader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.godzilla_loader"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 50 a5 ff512c 85c0 756c }
		$sequence_1 = { a5 50 a5 ff512c 85c0 756c }
		$sequence_2 = { 7406 8b08 50 ff511c }
		$sequence_3 = { a5 ff512c 85c0 756c }
		$sequence_4 = { 6a00 8bf8 8d45fc 50 57 6a01 56 }
		$sequence_5 = { 51 56 57 ff7508 ff15???????? 8bf0 56 }
		$sequence_6 = { 52 50 ff91f0000000 85c0 7813 }
		$sequence_7 = { 6a00 6a00 8bf8 8d45fc 50 57 }
		$sequence_8 = { 57 6a01 56 ff7508 8975fc }
		$sequence_9 = { 8b08 50 ff11 85c0 7527 }

	condition:
		7 of them and filesize <155648
}
