rule win_ehdevel_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.ehdevel."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ehdevel"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6800040000 50 e8???????? 8d8df8f7ffff 6800040000 51 e8???????? }
		$sequence_1 = { 7520 47 83c31c 3bfe 7cd2 5f 5e }
		$sequence_2 = { 56 6a00 ffd3 50 ff15???????? 8d85fcefffff 50 }
		$sequence_3 = { 51 68???????? e8???????? 83c414 8d95f8d3ffff 52 8d85f8ebffff }
		$sequence_4 = { c686c800000043 c6864b01000043 c7466860840310 6a0d e8???????? 59 }
		$sequence_5 = { 68???????? 8d4c2420 51 e8???????? 8d8424bc000000 8d5001 }
		$sequence_6 = { e8???????? 84c0 0f8417ffffff b301 68???????? e8???????? 8b4df8 }
		$sequence_7 = { 75f2 897e10 83f908 720c }
		$sequence_8 = { e9???????? 56 ff15???????? 8b8dc08bffff 8b95e88bffff 68???????? }
		$sequence_9 = { 68???????? 8d4c2404 6800040000 51 e8???????? 83c40c }

	condition:
		7 of them and filesize <524288
}
