rule win_alma_communicator_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.alma_communicator."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alma_communicator"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8a4a1c 884807 a1???????? c6400800 e8???????? 59 }
		$sequence_1 = { 8945f0 8b450c 8945f4 8b4514 40 c745ec93f84000 894df8 }
		$sequence_2 = { 8bcb 898554f7ffff e8???????? 8bcb 898550f7ffff 6a02 5f }
		$sequence_3 = { e8???????? 83c40c 8d8d58ffffff 8d5102 }
		$sequence_4 = { 8974241c 68d0070000 832600 897c2424 }
		$sequence_5 = { 668b4f02 03fe 663bca 75f5 ffb53cf7ffff 8907 6bc328 }
		$sequence_6 = { 0f85aa010000 33c0 40 8985ccebffff }
		$sequence_7 = { 7204 3c7a 7608 3c2b 7404 3c2f }
		$sequence_8 = { 88840d20f6ffff 41 84c0 75ed 8d8d20f6ffff 49 8a4101 }
		$sequence_9 = { 8a01 41 84c0 75f9 8a442454 2bca 83f901 }

	condition:
		7 of them and filesize <245760
}
