rule win_ksl0t_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.ksl0t."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ksl0t"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 488d15a1d80000 b93d000000 e8???????? 41b806000000 488d15ded70000 }
		$sequence_1 = { 57 8d8502110000 50 e8???????? }
		$sequence_2 = { 488d15d5dd0000 488d8c24b0020000 ff15???????? 488d1554af0000 }
		$sequence_3 = { 754f 4c8d05ad2e0000 458bcd ba00010000 33c9 }
		$sequence_4 = { 57 8d9500110000 52 ff15???????? 0fb745e0 50 68???????? }
		$sequence_5 = { bd???????? b8???????? 2bf9 2bd9 83ed49 2bc1 89442418 }
		$sequence_6 = { 8b74241c 30040e 83c104 836c241001 0f8579ffffff bb23000000 }
		$sequence_7 = { 64a100000000 50 83ec1c a1???????? 3145f8 33c5 898568080000 }
		$sequence_8 = { c68424c002000012 888424c1020000 889c24c2020000 c68424c302000002 }
		$sequence_9 = { 68???????? ff15???????? 83c40c e9???????? 6a06 }
		$sequence_10 = { 33cd e8???????? 81c56c080000 8be5 }
		$sequence_11 = { ff15???????? e9???????? 488d15a5c10000 4881c21c010000 }
		$sequence_12 = { 448b842438090000 8b8424f4080000 488b4c2448 4803c8 }
		$sequence_13 = { c684249f03000020 c68424a003000021 c68424a103000055 c684249000000001 c68424910000003a c684249200000000 }
		$sequence_14 = { 0fb700 85c0 7426 488b442430 0fb700 83f82d }
		$sequence_15 = { b92f000000 e8???????? 41b824000000 488d153bd90000 b939000000 }

	condition:
		7 of them and filesize <196608
}
