rule win_cabart_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.cabart."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cabart"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83c420 ff7508 ffd6 8bf8 8d85d8fbffff 50 ffd6 }
		$sequence_1 = { ebe2 85ff 7507 68bc0b0000 ebd7 }
		$sequence_2 = { ff15???????? 57 8d45f4 50 6a3f 56 }
		$sequence_3 = { 68???????? e8???????? 83c40c 3bc7 740d 6800800000 }
		$sequence_4 = { 2bf8 33c0 6689847de0fdffff 395d10 7415 }
		$sequence_5 = { ffd6 68???????? 89442414 ffd6 8bf8 85db }
		$sequence_6 = { 68???????? ff7508 33db 895dfc }
		$sequence_7 = { be00020000 ff35???????? 68???????? 56 ff35???????? ff15???????? }
		$sequence_8 = { e8???????? 8b0f 668b5441fa 66899500fcffff 668b5441fc }
		$sequence_9 = { a3???????? ffd6 5f 5e 5d a3???????? 5b }

	condition:
		7 of them and filesize <32768
}
