rule win_royal_dns_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.royal_dns."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.royal_dns"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bd6 c1fa05 8b149580502500 83e61f c1e606 }
		$sequence_1 = { 6a0d 58 5d c3 8b04cd84372500 5d }
		$sequence_2 = { 84c9 745c 80f93f 0f879e010000 0fb6d9 43 }
		$sequence_3 = { 884804 8b54b7fc 8a85a0fcffff 884205 c785acfcffff01000000 }
		$sequence_4 = { 68ff070000 8d85fdf5ffff 6a00 bb???????? 50 c785f8f5ffff02000080 c785f0f5ffff00000000 }
		$sequence_5 = { 52 ffd6 57 8d85f0fdffff 50 ffd6 68???????? }
		$sequence_6 = { 8b8df8fbffff 8b4508 6a10 51 6a00 53 8d95fcfbffff }
		$sequence_7 = { e8???????? 6a06 89430c 8d4310 8d893c342500 }
		$sequence_8 = { 32c0 eb04 8a4405b4 6a0c }
		$sequence_9 = { e8???????? 8b4d10 8b55e8 8b45e4 }

	condition:
		7 of them and filesize <204800
}
