rule win_floxif_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.floxif."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.floxif"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83c404 50 8d4d84 e8???????? 83f8ff 0f85ac000000 6a00 }
		$sequence_1 = { 80a0405d021000 40 41 41 }
		$sequence_2 = { 8b55e0 8d440afc 50 8d4dc0 51 e8???????? }
		$sequence_3 = { 85c0 0f8677010000 c745a800000000 eb09 8b45a8 83c001 }
		$sequence_4 = { f6c201 7416 8088????????10 8a9405ecfdffff 8890405d0210 eb1c }
		$sequence_5 = { c645f2ac c645f392 c645f4b0 c645f5ab c645f6b4 }
		$sequence_6 = { c6458f00 c64590e0 c64591ee c64592ec c64593eb c64594e8 c64595e8 }
		$sequence_7 = { c705????????01000000 50 a3???????? e8???????? 8db60c0f0210 bf???????? a5 }
		$sequence_8 = { 50 8b4df0 e8???????? 8b4df0 8b55f0 8b410c 2b4204 }
		$sequence_9 = { e9???????? 33d2 8a15???????? 83fa01 7514 c6458801 8d4df0 }

	condition:
		7 of them and filesize <352256
}
