rule win_webc2_head_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.webc2_head."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_head"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d7c2428 f3a5 895c2410 88542410 8b542410 8bc2 }
		$sequence_1 = { 8b542410 8bc2 c1e802 83e03f a4 7c0b 83f840 }
		$sequence_2 = { eb02 b03d 8b742410 8bcb 83e103 8806 }
		$sequence_3 = { 8d4c2418 8d942444080000 03f0 51 50 52 55 }
		$sequence_4 = { f7e1 d1ea a4 8d049500000000 8d0c52 89442418 894c2438 }
		$sequence_5 = { 8b048540cb4000 8d04c8 8b0b 8908 8a4d00 }
		$sequence_6 = { 80f941 89442414 7c0d 80f95a 7f08 0fbee9 }
		$sequence_7 = { 8dbc248c010000 896c2428 f3ab 8d442434 }
		$sequence_8 = { 8d9e38994000 803b00 8bcb 742c }
		$sequence_9 = { 6a06 55 c7442430804f1200 ffd7 bf???????? 83c9ff 33c0 }

	condition:
		7 of them and filesize <106496
}
