rule win_unidentified_069_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.unidentified_069."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_069"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 893d???????? 5f 5e c3 55 8d6c2488 81ec94000000 }
		$sequence_1 = { 6a08 5b 668b041f 43 43 837de8ff 6689852effffff }
		$sequence_2 = { 83e4f8 81ec18030000 53 57 6a03 5f }
		$sequence_3 = { 85c0 0f848a000000 57 e8???????? 83c8ff 8d4c2438 }
		$sequence_4 = { 6a2c 8d75d0 58 e8???????? ff7508 33f6 56 }
		$sequence_5 = { 66833b00 0f855cffffff 5b 8d75dc e8???????? }
		$sequence_6 = { 57 ffd3 83f8ff 0f84f8000000 8bcf }
		$sequence_7 = { 3b750c 72d3 8b4508 8945f4 8d45f8 50 6a01 }
		$sequence_8 = { 56 85c0 740c e8???????? 33c0 5e 5d }
		$sequence_9 = { 5e 5b c9 c20400 8b06 53 55 }

	condition:
		7 of them and filesize <434176
}
