rule win_nightsky_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.nightsky."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nightsky"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 41b840000800 ff15???????? 4c8bf0 4885c0 74e0 488b4d80 4c8bfb }
		$sequence_1 = { 4c23c8 48ffc2 483bd3 0f8269ffffff 488b5c2408 488b742410 488b7c2418 }
		$sequence_2 = { 498bc9 48c1e910 0fb6d1 498bc9 48c1e918 460fb68422e0b20400 420fb68c21e0b00400 }
		$sequence_3 = { b808000000 48f7e5 490f40c0 488bc8 e8???????? 488bf0 4885db }
		$sequence_4 = { 4181f3b3697961 6698 66400fb6f5 490fb7c4 41ffcb 4080cf30 4c03d9 }
		$sequence_5 = { 8841ff 4d85db 740b c6013d 48ffc1 49ffc0 eb0e }
		$sequence_6 = { ba10000000 e8???????? 498bcc e8???????? 4c8b642430 48c7432007000000 48896b18 }
		$sequence_7 = { 03c9 48c1e80d 48c1ea18 83e00f 83e20f 0b8c87306d0400 }
		$sequence_8 = { 488d0d0fda0000 480f45cf 48894b48 e8???????? eb17 4885ff 488d0dead90000 }
		$sequence_9 = { 4c63d2 488bd9 498bc2 458bf1 48c1f806 488d0d5c110200 }

	condition:
		7 of them and filesize <19536896
}
