rule win_ngioweb_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.ngioweb."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ngioweb"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b4604 897808 eb15 894f08 8b06 89780c 893e }
		$sequence_1 = { 394518 89b39c000000 c783a800000001000000 8983b0000000 7412 50 6884000000 }
		$sequence_2 = { ffd0 85c0 7554 ff75fc 53 }
		$sequence_3 = { 66c745ae6300 66c745ac5400 668975aa 66895dc4 e8???????? 33c0 }
		$sequence_4 = { 668b460c 895f04 8d5f08 53 668907 ff7608 }
		$sequence_5 = { 3bc7 7574 689f860100 6810270000 8d4508 50 }
		$sequence_6 = { 53 8b5d24 68b9ed740a 56 e8???????? ff7518 ff7514 }
		$sequence_7 = { ff75f0 ff15???????? ff15???????? 8b45e8 eb02 33c0 5f }
		$sequence_8 = { 8bc3 5b 5d c21400 57 8b7c2408 85ff }
		$sequence_9 = { 770b 0fb7c0 668b4445d8 668906 46 46 49 }

	condition:
		7 of them and filesize <204800
}
