rule win_megacortex_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.megacortex."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.megacortex"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { f7d9 1bc9 23c1 8d4aff 8945cc 8d45cc }
		$sequence_1 = { eb69 56 8d8dfcfcffff e8???????? ff460c 8d8d48fcffff 6a01 }
		$sequence_2 = { f7d9 1bc9 23c8 8bc3 03d1 8d5dd4 0355d8 }
		$sequence_3 = { c645fc01 83fa10 722f 8b8dccfdffff 42 8bc1 81fa00100000 }
		$sequence_4 = { 2bc6 8b16 83e202 f7d9 1bc9 23c8 51 }
		$sequence_5 = { e8???????? 83c408 85c0 0f8587010000 8b4514 85ff 7454 }
		$sequence_6 = { e9???????? 6a04 b8???????? e8???????? 33db bfff7f0000 895df0 }
		$sequence_7 = { 894204 83790400 7503 895340 6a08 51 }
		$sequence_8 = { 8975fc 50 e8???????? 83c40c 5f 5e 5b }
		$sequence_9 = { e8???????? 8d45f0 3bf0 0f857affffff 8bc3 8b4df4 64890d00000000 }

	condition:
		7 of them and filesize <1556480
}
