rule win_webmonitor_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.webmonitor."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webmonitor"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 00e8 17 42 0048a5 }
		$sequence_1 = { 06 000b 3a58ff 1b03 fd 006cff1e }
		$sequence_2 = { ff01 04e0 fd 0512002413 }
		$sequence_3 = { 3a58ff 2503fd006c ff1e e00e 000e }
		$sequence_4 = { 6c 68ff080800 8a3401 a3???????? 0800 }
		$sequence_5 = { 000d???????? 04e4 fd 0468 ff05???????? }
		$sequence_6 = { ff05???????? 000d???????? 04b8 fe04f4 }
		$sequence_7 = { ffe1 ba???????? b9???????? ffe1 }
		$sequence_8 = { 00e8 dd7000 008bf98b5d1c 8d4de4 }
		$sequence_9 = { 00e8 f61c00 008bd9895df0 8b451c }
		$sequence_10 = { 0108 eb5a 8b4508 83ceff }
		$sequence_11 = { 0108 8b442410 891e 894604 }
		$sequence_12 = { 00d1 6848007269 48 00856948008b }
		$sequence_13 = { 00d1 6848004069 48 00d1 }
		$sequence_14 = { 000f b681 fc b84500ff24 }
		$sequence_15 = { 00856948008b ff558b ec 83ec0c }

	condition:
		7 of them and filesize <1867776
}
