rule win_exaramel_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.exaramel."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.exaramel"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d45ec c745ec00000000 50 ff7508 57 e8???????? }
		$sequence_1 = { e8???????? ff75f8 e8???????? 8b06 83c410 }
		$sequence_2 = { b801000000 68f0030000 0f42f0 8d45f4 50 57 }
		$sequence_3 = { 8b01 51 8b4008 ffd0 a1???????? }
		$sequence_4 = { 6bf630 8b04bd60dd4100 f644302880 741f e8???????? }
		$sequence_5 = { 50 ff15???????? 85c0 7527 56 6a00 }
		$sequence_6 = { 85f6 7425 8d4e02 51 e8???????? 8b4d0c }
		$sequence_7 = { ff15???????? 85c0 740a 6a01 e8???????? 83c404 }
		$sequence_8 = { ff35???????? c705????????00000000 c705????????01000000 c705????????00000000 c705????????03000000 ff15???????? 8b4dfc }
		$sequence_9 = { ffd0 894508 8b7de4 85ff 741a 8b75dc 8b1d???????? }

	condition:
		7 of them and filesize <294912
}
