rule win_mirrorkey_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.mirrorkey."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mirrorkey"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0f57c0 0f1145d8 ff15???????? c70016000000 ff15???????? 8d45d4 50 }
		$sequence_1 = { 895914 0fb77806 85ff 7414 8d4b10 8b4104 0301 }
		$sequence_2 = { ff15???????? 83c40c c744241000000000 33c0 c644242c00 8944242d 8d742433 }
		$sequence_3 = { 8bf9 8b7508 8d45a4 50 }
		$sequence_4 = { 83c004 8b7dfc 83ff01 7f87 5f }
		$sequence_5 = { 730b 68???????? ff15???????? 894610 837e1410 }
		$sequence_6 = { 897508 2bda ebaa 8d5aff 83c704 eba2 }
		$sequence_7 = { 8d4dd8 50 e8???????? 8d4d8c e8???????? 837de808 7d15 }
		$sequence_8 = { 6a00 51 89542414 ff15???????? 83c408 83f8ff }
		$sequence_9 = { 53 8b5d0c 894dfc 8b4d08 56 }

	condition:
		7 of them and filesize <117760
}
