rule win_locky_auto_alt_5
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.locky."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.locky"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 51 51 8b00 6a00 8d4d0c 51 ff750c }
		$sequence_1 = { 760a 68???????? e8???????? a1???????? 2b05???????? 6a1c }
		$sequence_2 = { 50 c745f8???????? e8???????? 8d85f0fdffff 50 }
		$sequence_3 = { 99 83e207 8d3c02 33d2 42 c1ff03 663bca }
		$sequence_4 = { 99 5e f7fe 8bf0 81fe48922409 760a 68???????? }
		$sequence_5 = { 6a00 ff15???????? 85c0 751e ff15???????? c745f8???????? }
		$sequence_6 = { 8907 8bc7 c9 c20400 ff15???????? 8945fc }
		$sequence_7 = { 7314 8b4e1c 8b431c 3bc8 7c0a }
		$sequence_8 = { 5b c21000 e9???????? 8bff 55 8bec 56 }
		$sequence_9 = { 03d8 8b442408 f7e1 03d3 5b c21000 e9???????? }
		$sequence_10 = { 66ab e9???????? 8d12 e9???????? }
		$sequence_11 = { ebcf 90 8d36 90 }
		$sequence_12 = { 5e c21000 8bff 55 8bec 33c0 8b4d08 }
		$sequence_13 = { 6a61 e9???????? 90 58 }
		$sequence_14 = { 6a63 e9???????? 90 8d36 }
		$sequence_15 = { 66ab e9???????? 58 90 e9???????? 90 }
		$sequence_16 = { 66ab 90 e9???????? 8d00 }

	condition:
		7 of them and filesize <1122304
}
