rule win_mail_o_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.mail_o."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mail_o"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff15???????? 83a3980e0000fd 4889bb800e0000 488bcb 4889bb800e0000 e8???????? 488b8b60100000 }
		$sequence_1 = { ffc7 4883c302 493bde 7cd7 488b8c24a0000000 ba01000000 448d42fe }
		$sequence_2 = { eb2e 488d15518b1500 488bcf e8???????? 85c0 7405 830b02 }
		$sequence_3 = { e8???????? 8bf8 85c0 7563 488d15563e1700 488bcb e8???????? }
		$sequence_4 = { f30fe6d2 8bd7 e8???????? 03ef 85db 7ea1 2bdf }
		$sequence_5 = { 7cda 488b4f20 488bd6 e8???????? 4885c0 0f8459020000 418bec }
		$sequence_6 = { e9???????? 4183fd00 743e 492bed 4d8bc5 488bd5 488bcf }
		$sequence_7 = { e8???????? b8ffffffff e9???????? 448b8c24a0000000 4183f901 746a 4c8d0578650900 }
		$sequence_8 = { bfffffffff e9???????? f7432000010000 4889742440 740f 488bd3 488d0da3050000 }
		$sequence_9 = { 7442 488bce 4c8d2defdb0b00 0f1f4000 6666660f1f840000000000 410fb61408 48ffc1 }

	condition:
		7 of them and filesize <5985280
}
