rule win_red_gambler_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.red_gambler."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.red_gambler"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 807e01a2 7535 807e02c3 752f 68???????? 68???????? ff15???????? }
		$sequence_1 = { 68???????? c745ece80f13fc ffd6 a3???????? }
		$sequence_2 = { 68ff000000 8d8df0fcffff 51 ff15???????? 85c0 }
		$sequence_3 = { 3bf1 72bf 5e 33c0 5b }
		$sequence_4 = { e8???????? 8bf8 83c404 83ffff 74e1 57 8d4c244c }
		$sequence_5 = { 8d4c2414 51 6a40 6a07 }
		$sequence_6 = { 68???????? 68???????? ffd6 5e 85c0 7505 }
		$sequence_7 = { 894dec 8955f0 8945f4 ff15???????? }
		$sequence_8 = { 2b2a bee7eee947 7c26 0e }
		$sequence_9 = { 8d4d98 51 ff15???????? 8d5598 52 8d8598fdffff }
		$sequence_10 = { 7456 7b78 cd50 d46e }
		$sequence_11 = { bc340e65bc 691fd8727fcf 14cf fd }
		$sequence_12 = { 9e e779 9e 54 }
		$sequence_13 = { 51 ff15???????? 83c414 6a00 6a00 8d9598fbffff }
		$sequence_14 = { ff15???????? 6800010000 8d8d98fdffff 51 8d9598feffff 52 }
		$sequence_15 = { 52 8d8598fdffff 50 68???????? }
		$sequence_16 = { 3c3d 9e e7bd e600 3e3e25162f062d }
		$sequence_17 = { 6a00 6a00 8d9598fbffff 52 68???????? 6a00 6a00 }
		$sequence_18 = { 50 4c 48 44 40 6c }
		$sequence_19 = { 6800010000 8d8dfcfdffff 51 6a00 }
		$sequence_20 = { 68???????? 8d8d98fbffff 68???????? 51 ff15???????? 83c414 }
		$sequence_21 = { 7c0e 07 642827 3ccf }
		$sequence_22 = { 8d9598feffff 52 ff15???????? 8d8594fbffff 50 8d4d98 51 }
		$sequence_23 = { 6800010000 8d85fcfeffff 50 6a00 ff15???????? }
		$sequence_24 = { 2f 74be 6f 665b }
		$sequence_25 = { 68???????? ff15???????? 8b7508 c7465c486b4000 83660800 }
		$sequence_26 = { 6888130000 ffd7 6800010000 8d95fcfeffff }
		$sequence_27 = { 55 8bec 8b4508 ff34c5d0814000 }
		$sequence_28 = { 8bf8 ffd3 8bd8 ffd7 8b3d???????? 6aff ffd7 }
		$sequence_29 = { 83f805 7d10 668b4c4310 66890c4580974000 40 ebe8 }
		$sequence_30 = { 6a5c 8d8dfcfeffff 51 ff15???????? }
		$sequence_31 = { 8bec 8b4508 33c9 3b04cd10804000 }

	condition:
		7 of them and filesize <327680
}
