rule win_turla_silentmoon_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.turla_silentmoon."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.turla_silentmoon"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 88442453 a1???????? 89442430 a0???????? 53 56 88442444 }
		$sequence_1 = { 8b4508 85c0 0f84f9010000 8938 5e 5b 8be5 }
		$sequence_2 = { 51 6800001000 53 56 ff15???????? 83f801 }
		$sequence_3 = { b950000000 e8???????? 83c404 6a08 b990000000 e8???????? }
		$sequence_4 = { 8b94bd28feffff 8d441001 8b55f0 8955d4 8b94bd28feffff 8955d8 8b55f0 }
		$sequence_5 = { 3bd1 7c9a 0fb608 3bd1 7e66 83be5c02000008 7c2f }
		$sequence_6 = { 48 83f803 0f878a000000 ff248588344000 8bc3 e8???????? }
		$sequence_7 = { 85ff 0f8f82fcffff 5f 5b }
		$sequence_8 = { 7e0a 8b4df0 8b7dd8 33c0 f3ab 8145d808040000 }
		$sequence_9 = { 741f 8b4508 85c0 7406 c700faffffff c787c4130000faffffff 5e }

	condition:
		7 of them and filesize <204800
}
