rule win_pkybot_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.pkybot."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pkybot"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 33f6 8b4704 0590000000 894620 85db 7405 }
		$sequence_1 = { 837e0400 59 59 75dc 832600 }
		$sequence_2 = { 85c0 740c 8b400c 8b00 8b00 8945f4 eb1a }
		$sequence_3 = { 51 50 e8???????? 6a04 8d45e0 }
		$sequence_4 = { 85c0 7407 46 8a06 84c0 79eb }
		$sequence_5 = { 6801010000 56 e8???????? 56 e8???????? }
		$sequence_6 = { 56 a3???????? c705????????01000000 e8???????? }
		$sequence_7 = { ff7518 57 ff15???????? 56 ff7514 ff7510 ff750c }
		$sequence_8 = { 8b4e04 21413c c741300d000000 897938 5f }
		$sequence_9 = { 8b00 8945f4 eb1a 56 ff15???????? }

	condition:
		7 of them and filesize <204800
}
