rule win_sidewalk_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.sidewalk."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sidewalk"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 4c8d4dd7 418b09 418bc0 c1e002 4d8d4904 4863d0 41ffc0 }
		$sequence_1 = { 4403e8 4133db 418bcd c1c307 }
		$sequence_2 = { 4403df 458bc3 4433c0 418bc5 }
		$sequence_3 = { 884202 884a03 4183f810 7ccc }
		$sequence_4 = { 48ffc1 488d040a 483bc6 7ce2 4883c640 4883c340 4883ef40 }
		$sequence_5 = { 0bc8 0fb642fe c1e108 0bc8 41890c10 488d5204 }
		$sequence_6 = { 41890c10 488d5204 4983e901 75d4 4863457f }
		$sequence_7 = { 4403c9 458bf1 4433f0 41c1c608 }
		$sequence_8 = { 418bc7 33c3 c1c207 c1c00c 4403c8 }
		$sequence_9 = { 7d15 8a040f 3201 41880408 48ffc1 488d040a }
		$sequence_10 = { 8945ef 8bc2 33c6 c1c010 }
		$sequence_11 = { 4433f2 c1c710 4403df 41c1c610 }
		$sequence_12 = { 4533d1 4403ee 41c1c210 418bc3 }
		$sequence_13 = { 89750b 4489750f 44897d03 448965ff }
		$sequence_14 = { 4403df 41c1c610 4503e6 4403cb }
		$sequence_15 = { 41c1c208 4503fa 418bdf 33d8 }

	condition:
		7 of them and filesize <237568
}
