rule win_vobfus_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.vobfus."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vobfus"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b5508 8b92e8000000 8b82840b0000 50 }
		$sequence_1 = { 8b92e8000000 8b825c150000 50 50 }
		$sequence_2 = { 55 8bec 8b5508 8b92e8000000 8b823c1d0000 50 }
		$sequence_3 = { 8b8260140000 50 50 8b10 ff5204 }
		$sequence_4 = { 8b5508 8b92e8000000 8b827c1f0000 50 }
		$sequence_5 = { 8b5508 8b92e8000000 8b826c110000 50 }
		$sequence_6 = { 8b5508 8b92e8000000 8b8238030000 50 }
		$sequence_7 = { 8b5508 8b92e8000000 8b82801e0000 50 }
		$sequence_8 = { f2e8fae6d5f6 d2b5f2bb8ff3 ae 73f3 aa 5c f6ac4ff8b54ffb }
		$sequence_9 = { 6c 74ff 801800 0808 0006 }
		$sequence_10 = { 3bce 6c 5e 3249c1 ad 42 }
		$sequence_11 = { ce 8ca4b11e13b793 73aa fa 77ba 6f }
		$sequence_12 = { 78ff 0d50004900 3e3cff 46 }
		$sequence_13 = { f2ed ec f3ed ebf2 ed ec }
		$sequence_14 = { 3dae8602f8 0853ac 866cedad b909dfd18c 9d 7454 }
		$sequence_15 = { f2ed ec f2ed ec f2ed ec }
		$sequence_16 = { da4209 1be6 4d b2bc 031a a80b }
		$sequence_17 = { 7cc8 dc7acd e291 d2e8 }
		$sequence_18 = { 6f d86f93 c8ed9459 ef 60 }
		$sequence_19 = { 1400 48 0008 78ff }
		$sequence_20 = { 5c f6ac4ff8b54ffb c058fcca 61 }
		$sequence_21 = { 0808 0006 3401 41 06 1005???????? 0100 }
		$sequence_22 = { 3e3cff 46 14ff 0470 fe0a }
		$sequence_23 = { 0c4e 696a5455b8a72f c8c46952 10043b 51 }

	condition:
		7 of them and filesize <409600
}
