rule win_touchmove_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.touchmove."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.touchmove"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { cc 4883ec48 488364243000 8364242800 41b803000000 488d0d38520000 4533c9 }
		$sequence_1 = { 0f843f040000 48833d????????00 0f8431040000 488d9520230000 488bcb ff15???????? }
		$sequence_2 = { 8bcb e8???????? e9???????? 488b442450 488d0d8bdc0000 488b04c1 41f644070840 }
		$sequence_3 = { 83e11f 48c1f805 486bc958 48030cc2 eb07 488d0d14f90000 f6410820 }
		$sequence_4 = { 442bd2 41ffc0 4181e007000080 7d0a 41ffc8 4183c8f8 41ffc0 }
		$sequence_5 = { 4c8bef 49c1fd05 4c8d35d4db0000 83e31f 486bdb58 4b8b04ee 0fbe4c1808 }
		$sequence_6 = { 4533c9 458bc6 ba00000080 488d8d904d0000 ff15???????? 488bd8 4883f8ff }
		$sequence_7 = { ff15???????? 85c0 7577 c744246800010000 488d442468 4889442428 488d8580480000 }
		$sequence_8 = { 488905???????? ff15???????? 48833d????????00 488905???????? 0f8477040000 48833d????????00 }
		$sequence_9 = { 8bf8 8bd0 b940000000 ff15???????? }

	condition:
		7 of them and filesize <224256
}
