rule win_strongpity_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.strongpity."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.strongpity"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6aff ff771c 56 ff15???????? 837df800 7416 6a04 }
		$sequence_1 = { 53 56 ff15???????? 85c0 7427 53 }
		$sequence_2 = { eb0f 50 56 e8???????? 59 59 }
		$sequence_3 = { 75f8 ff75d0 68???????? ff36 e8???????? 8b45d4 }
		$sequence_4 = { 6a6f 668945d4 58 6a6e 5a 6a74 }
		$sequence_5 = { 7417 ba00010000 8bc8 c60100 41 83ea01 75f7 }
		$sequence_6 = { ff75f4 68???????? 8d0441 50 e8???????? 8b4608 83c418 }
		$sequence_7 = { 6a02 59 03c1 50 e8???????? }
		$sequence_8 = { 5e 5d 83c40c c3 396f18 }
		$sequence_9 = { 5e 5d 5b c3 837c240800 56 }
		$sequence_10 = { 5e 5d 83c408 c3 33db }
		$sequence_11 = { 5e 5d 5b 83c420 c3 8b442424 68???????? }
		$sequence_12 = { 5e 5d 5b 83c410 c3 837c242c00 }
		$sequence_13 = { 5e 5d 8919 33c0 5b 59 }
		$sequence_14 = { 57 8b38 8b8f30870000 8baf28010000 }
		$sequence_15 = { 5e 5d 8bc3 5b 83c410 c3 8b464c }

	condition:
		7 of them and filesize <999424
}
