rule win_iisniff_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.iisniff."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.iisniff"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b8c240c000100 56 8d842414000100 50 }
		$sequence_1 = { 50 e8???????? 83c404 89b424f4000000 }
		$sequence_2 = { e9???????? 83bc248001000010 8b84246c010000 7307 8d84246c010000 8b4c2418 }
		$sequence_3 = { 6a03 68000000c0 68???????? ff15???????? 6a02 }
		$sequence_4 = { 83ec08 56 8b35???????? 57 8b3d???????? 85f6 7505 }
		$sequence_5 = { 8b5708 83c404 8d4c240c 51 8bd8 8b8780000000 }
		$sequence_6 = { 8944242c 50 e8???????? 0fb7c0 59 89442430 }
		$sequence_7 = { 752b 8b4c2418 8b4904 8b440c20 8d4c0c18 83c802 397928 }
		$sequence_8 = { 0fb6c0 50 8d842430010000 50 8d44241c 50 e8???????? }
		$sequence_9 = { e8???????? 8b4f08 8b9780000000 83c404 }
		$sequence_10 = { 6a01 8d8c2470010000 e8???????? 56 }
		$sequence_11 = { 85c0 0f85c4030000 3935???????? 0f8661010000 a1???????? 8b00 }
		$sequence_12 = { c7461c00000000 56 c6460c00 e8???????? 83c404 ff0d???????? 8b450c }
		$sequence_13 = { 29750c 03de 0130 eb17 0fb603 8b17 50 }
		$sequence_14 = { eb16 8b45cc ff704c 8b45c8 4e 0fbe0406 50 }

	condition:
		7 of them and filesize <1441792
}
