rule win_cookiebag_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.cookiebag."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cookiebag"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0f8e39050000 8a442437 bf???????? 88442424 83c9ff 33c0 33ed }
		$sequence_1 = { 51 8b4c2414 55 e8???????? 84c0 7412 8b442418 }
		$sequence_2 = { 51 e8???????? 83c404 eb1d 8b4608 8b7604 3bf3 }
		$sequence_3 = { 50 53 52 e8???????? 8bce e8???????? 8b4c2428 }
		$sequence_4 = { 83c1fe 51 e8???????? 83c404 8b4c242c 897c243c 3bcf }
		$sequence_5 = { e8???????? 68???????? e8???????? 83c404 8bd8 8dbe14010000 6a01 }
		$sequence_6 = { 895c2428 e8???????? 84c0 7427 8b7c2418 8bcd }
		$sequence_7 = { 85c0 7454 8b87dc000000 85c0 764a 8b44240c }
		$sequence_8 = { e8???????? 83c414 b001 5f 5e c20400 5f }
		$sequence_9 = { 6a01 8d4c241c c7442444ffffffff e8???????? 8b4c2438 64890d00000000 }

	condition:
		7 of them and filesize <311296
}
