rule win_powerloader_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.powerloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.powerloader"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bd0 e8???????? 85ff 740c }
		$sequence_1 = { e8???????? 0fb6d8 84c0 7514 ff15???????? }
		$sequence_2 = { 8bf2 32db e8???????? 3bc7 7349 }
		$sequence_3 = { 33d2 ff15???????? 83f81f 7323 }
		$sequence_4 = { 0fb6d8 84c0 7514 ff15???????? }
		$sequence_5 = { ff15???????? 83f81f 7323 ff15???????? }
		$sequence_6 = { 7441 8b5c2430 85db 741d }
		$sequence_7 = { e8???????? 8b7c2430 85ed 740d }
		$sequence_8 = { e8???????? eb22 33c9 66666666660f1f840000000000 }
		$sequence_9 = { e8???????? eb22 33c9 66666666660f1f840000000000 0fb6840c30010000 }

	condition:
		7 of them and filesize <155648
}
