rule win_gup_proxy_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.gup_proxy."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gup_proxy"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d442424 50 687e660480 57 }
		$sequence_1 = { 8b4d08 33c0 3b0cc528804100 7427 40 }
		$sequence_2 = { 8b0c8d10974100 c644390400 85f6 740c 56 e8???????? 59 }
		$sequence_3 = { 83c10c 8b048510974100 03c1 50 }
		$sequence_4 = { c7461000000000 837e1410 7204 8b0e eb02 8bce }
		$sequence_5 = { c1e706 8b0c8d10974100 c644390400 85f6 740c 56 e8???????? }
		$sequence_6 = { c744245400000000 c644244400 720c ff74242c e8???????? 83c404 ff742414 }
		$sequence_7 = { c74424580f000000 c744245400000000 c644244400 720c ff74242c }
		$sequence_8 = { 894de4 83f905 7d10 668b444b0c 6689044d5c9f4100 41 }
		$sequence_9 = { 03d8 0fb6420e 03c8 0fb6420d c1e108 }

	condition:
		7 of them and filesize <247808
}
