rule win_zeroaccess_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.zeroaccess."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeroaccess"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff15???????? 85c0 7408 ff15???????? eb02 }
		$sequence_1 = { 6a04 68???????? 6a10 68???????? 68060000c8 ff7308 }
		$sequence_2 = { 6a02 68???????? ff75f8 ff15???????? }
		$sequence_3 = { 48 83c9ff c744242804000000 48 }
		$sequence_4 = { 8b45fc 3bf8 730e 2bc7 e8???????? }
		$sequence_5 = { 6a01 8d45f4 50 ff7608 ff15???????? }
		$sequence_6 = { 740c bf03000040 eb05 bf010000c0 85ff }
		$sequence_7 = { 3bc1 7604 83c8ff c3 }
		$sequence_8 = { ff15???????? 85c0 7407 b8e3030000 }
		$sequence_9 = { c3 8d4104 83caff f00fc110 750a }
		$sequence_10 = { 6a10 68???????? 68060000c8 ff7708 ff15???????? 85c0 }
		$sequence_11 = { 85c0 756e 8d6840 ba6c090000 33c9 ff15???????? }
		$sequence_12 = { 8d4904 ffca 75f4 8b2f 44 }
		$sequence_13 = { 41 83e13c 41 83c104 ff15???????? }

	condition:
		7 of them and filesize <172032
}
