rule win_unidentified_095_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.unidentified_095."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_095"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ffc8 6641833c465c 7505 6641892c46 4c8bbc24e8000000 }
		$sequence_1 = { 85c0 7553 488bcf ff15???????? 488d4c2430 }
		$sequence_2 = { 488bd0 48d3ca 4933d0 4b8794fe90440200 eb2d }
		$sequence_3 = { 48c7c102000080 897c2420 ff15???????? 85c0 740c 8bc8 ff15???????? }
		$sequence_4 = { 488d1519de0000 488d0df2dd0000 e8???????? 488d1516de0000 488d0d07de0000 e8???????? 488b4308 }
		$sequence_5 = { 4881c490000000 5d c3 4053 4883ec20 488bd9 }
		$sequence_6 = { 660f28c1 4c8d0dfb9e0000 f20f101d???????? f20f100d???????? f20f59da }
		$sequence_7 = { 85c0 0f8502010000 837c243c04 7516 }
		$sequence_8 = { eb19 488d3d3a440100 eb10 488d3d41440100 eb07 488d3d20440100 4883a4248000000000 }
		$sequence_9 = { 75ed 488bcb 85d2 7507 e8???????? eb08 498bd1 }

	condition:
		7 of them and filesize <339968
}
