rule win_8t_dropper_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.8t_dropper."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.8t_dropper"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c644240c00 f3ab 66ab aa bf???????? 83c9ff }
		$sequence_1 = { f7d1 49 c6440c0c52 c6440c0d75 }
		$sequence_2 = { 50 e8???????? 8bf0 83c408 85f6 741b 56 }
		$sequence_3 = { 68???????? 6a02 50 8b442418 68???????? 50 ff15???????? }
		$sequence_4 = { 8d4c2408 51 683f000f00 50 }
		$sequence_5 = { 6801000080 ff15???????? bf???????? 83c9ff }
		$sequence_6 = { 50 ff15???????? 85c0 7559 8b4c2408 }
		$sequence_7 = { c6440c0e6e 8d4c2408 51 683f000f00 }
		$sequence_8 = { e8???????? 83c40c c3 8b442408 83f801 }
		$sequence_9 = { f7d1 49 51 68???????? 6a02 50 8b442418 }

	condition:
		7 of them and filesize <147456
}
