rule win_adhubllka_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.adhubllka."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.adhubllka"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 8d8d60ffffff e8???????? 0f108560ffffff be18000000 0f1185c0feffff }
		$sequence_1 = { 0f104590 0f118540ffffff 0f1045a0 0f118550ffffff e8???????? 83c404 8d8d60ffffff }
		$sequence_2 = { 894d9c 8b4dbc 89458c 8b45c4 897d98 8b7dc0 }
		$sequence_3 = { 7410 f745d800000002 7407 b801000000 eb02 33c0 }
		$sequence_4 = { 03c2 898534ffffff 33c7 c1c008 898520ffffff 03c1 8b4ddc }
		$sequence_5 = { 0fb605???????? c1e108 0bc8 0fb605???????? c1e108 0bc8 }
		$sequence_6 = { e8???????? 83c404 0f57c0 660f138424501a0000 6a02 }
		$sequence_7 = { 8d8d60ffffff e8???????? 8d8d60ffffff e8???????? 0f108560ffffff be04000000 0f118510ffffff }
		$sequence_8 = { 0f1f440000 8b5cbc48 53 ff15???????? 83f801 }
		$sequence_9 = { ffb590fdffff ff15???????? 85c0 0f8481fdffff 56 e8???????? }

	condition:
		7 of them and filesize <253952
}
