rule win_ragnarok_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.ragnarok."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ragnarok"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c1e908 0fb6c9 c1e208 0fb689105c4300 33d1 8b4de8 }
		$sequence_1 = { 83ec08 53 56 57 6a1e ff35???????? e8???????? }
		$sequence_2 = { 33348d10584300 8b4dec 8b149510544300 0fb6c9 33348d104c4300 }
		$sequence_3 = { 55 8bec 83ec18 53 56 8b7510 8bc6 }
		$sequence_4 = { 8b4dfc 0fb6c9 0fb689104b4300 c1e108 33f9 8b4dfc c1e910 }
		$sequence_5 = { 51 ff35???????? ffd6 6a1a ff35???????? 8bd8 e8???????? }
		$sequence_6 = { f3a5 8bca 8945f8 83e103 f3a4 3b450c 7ca5 }
		$sequence_7 = { c1c009 f7d1 234db0 03c7 8945a4 8b45a0 2345b4 }
		$sequence_8 = { 660fd60f 8d7f08 8b048dd4314100 ffe0 f7c703000000 7413 8a06 }
		$sequence_9 = { 2d80000000 742b 83e840 741b 83e840 }

	condition:
		7 of them and filesize <483328
}
