rule win_flusihoc_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.flusihoc."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.flusihoc"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 57 6a40 8d442428 6a00 50 c744242c44000000 e8???????? }
		$sequence_1 = { 8d7c2428 50 f3a5 c684246401000000 e8???????? 83c40c }
		$sequence_2 = { 8b542414 52 ffd6 6a0a }
		$sequence_3 = { ffd6 6a0a ff15???????? ebb1 }
		$sequence_4 = { ff15???????? 8b4c2410 51 ffd6 8b542414 }
		$sequence_5 = { 33c0 888c045e010000 8a4c042c 40 80f92f }
		$sequence_6 = { 3d68010000 7505 fe06 fe4e17 83f834 }
		$sequence_7 = { 7505 fe06 fe461e 3d68010000 }
		$sequence_8 = { ffd3 8b442410 6aff 50 ff15???????? }
		$sequence_9 = { 84c0 7420 ff15???????? 83c8ff }
		$sequence_10 = { 50 f3a5 c684246402000000 e8???????? 68d6000000 }
		$sequence_11 = { 6a01 6a02 ff15???????? 6a10 8d4c2414 }
		$sequence_12 = { 6a00 6a00 ff15???????? 8b35???????? 6860ea0000 ffd6 ebf7 }
		$sequence_13 = { ffd6 ebf7 3b0d???????? 7502 f3c3 e9???????? 8bff }
		$sequence_14 = { 3db7000000 7510 56 ff15???????? 33c0 }
		$sequence_15 = { 6a01 6a00 ff15???????? 8bf0 ff15???????? 3db7000000 7510 }

	condition:
		7 of them and filesize <319488
}
