rule win_bootwreck_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.bootwreck."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bootwreck"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 59 d558 6e 82c178 0e 2a5cce35 45 }
		$sequence_1 = { e9???????? ff3424 6802f2412c 9c 876c2444 9c 681ef2f505 }
		$sequence_2 = { 6a02 e8???????? 33db 3bc3 7412 ffd0 0fb7c0 }
		$sequence_3 = { 660fb3c7 89c7 f9 f8 f5 84f0 83c404 }
		$sequence_4 = { bed27fe028 a4 ab 5b 6212 672c13 1abaeb624f13 }
		$sequence_5 = { 90 e8???????? 89442408 9c 660fb6c2 660fbec2 0f9ac4 }
		$sequence_6 = { 85c0 881424 9c 60 66c70424320b 8d64242c 0f84e23a0300 }
		$sequence_7 = { 25ffffff7f 66c1eb0d 6687f3 80f72b 60 0345fc 8d642444 }
		$sequence_8 = { c6442414c9 c6442408a4 ff742430 c23400 ff3424 895e24 9c }
		$sequence_9 = { 70af 9c 236202 3376ad 9add1461e82b4a 97 1e }

	condition:
		7 of them and filesize <10821632
}
