rule win_paladin_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.paladin."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.paladin"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c20800 8d5d04 50 52 }
		$sequence_1 = { ffd7 8b4614 6aff 50 ffd7 8b4e10 }
		$sequence_2 = { 0faff0 83c61f c70728000000 c1fe03 83e6fc 894704 0faff1 }
		$sequence_3 = { 53 55 56 8bf1 57 b918000000 33c0 }
		$sequence_4 = { 33c0 8a41ff 8d1440 8d1492 8d1492 8d1cd0 33d2 }
		$sequence_5 = { 687f030000 6a00 68???????? 8bf0 }
		$sequence_6 = { 33c0 8dbc24a0000000 33d2 899c249c000000 83c40c 89942484000000 f3ab }
		$sequence_7 = { 81c468020000 c20400 53 c645002e bb01000000 eb04 8b742414 }
		$sequence_8 = { 8b4518 83f804 7427 83f802 7422 83f806 741d }
		$sequence_9 = { 83f80d 0f8661010000 eb04 8b6c2410 }

	condition:
		7 of them and filesize <106496
}
