rule win_woolger_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.woolger."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.woolger"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 83f814 750a be???????? e9???????? 83f81b }
		$sequence_1 = { 83ec54 6a40 8d45b0 6a00 50 c745ac44000000 e8???????? }
		$sequence_2 = { 33c5 8945fc 33c0 668945d4 }
		$sequence_3 = { 6685c0 8d85fcfeffff 50 0f95c3 ff15???????? 8b4f08 }
		$sequence_4 = { 52 ff15???????? 83f801 0f858d000000 }
		$sequence_5 = { 6a00 68???????? ff15???????? 68???????? 6a01 6a00 }
		$sequence_6 = { 66a5 8dbdfcf8ffff 4f 8a4701 47 84c0 }
		$sequence_7 = { 6a00 8d8dd4f4ffff 51 ffd6 85c0 75db }
		$sequence_8 = { 83c414 81ffb80b0000 5f 7c40 e8???????? e8???????? }
		$sequence_9 = { 3da2000000 0f8403010000 3da3000000 0f84f8000000 3da4000000 0f84e6000000 3da5000000 }

	condition:
		7 of them and filesize <196608
}
