rule win_laturo_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.laturo."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.laturo"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b842438050000 486bc038 488b0d???????? 4803c8 488bc1 4889442430 8b842440050000 }
		$sequence_1 = { 57 4883ec30 4c8bda 488d356747ffff 4183e30f 488bfa }
		$sequence_2 = { 8b8481f0240000 4803c1 ffe0 488b8424a8000000 0fb60c24 884801 0fb6442401 }
		$sequence_3 = { 4c8d0de4910000 f20f5cca f2410f590cc1 660f28d1 }
		$sequence_4 = { e8???????? 4c8d0d3d730100 4c8d05c6000000 488d15f7380100 }
		$sequence_5 = { 4c8d4c2420 41b840000000 488b542438 488b4c2430 ff15???????? 85c0 750a }
		$sequence_6 = { 90 4883ec28 803d????????00 754c 488d0d80040100 }
		$sequence_7 = { 48896810 48897018 48897820 4156 4157 4533f6 4c8d3d23800000 }
		$sequence_8 = { 80fac2 757e 3bf7 1bd2 42 8955f8 eb74 }
		$sequence_9 = { 66894210 e9???????? 8b4218 84c9 7412 83c808 }
		$sequence_10 = { 46 83c028 3bf2 72eb 5e 8bc3 }
		$sequence_11 = { f6c110 7410 807dfa06 0f95c0 }
		$sequence_12 = { 8bc8 894df4 0f85d8010000 807dff05 8975f0 }
		$sequence_13 = { 8b45e4 8b0c8530430110 8b45e8 f644012880 7446 0fbec3 }
		$sequence_14 = { 6a00 50 890a ff15???????? 5f 5e c3 }
		$sequence_15 = { 7420 6bc618 57 8db8383f0110 57 ff15???????? }

	condition:
		7 of them and filesize <253952
}
