rule win_microcin_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.microcin."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.microcin"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 50 56 ff15???????? 85c0 0f45f7 }
		$sequence_1 = { 442bc3 4803d6 4533c9 ff15???????? 85c0 75d9 488b742438 }
		$sequence_2 = { ff15???????? 488bcb ff15???????? 448bc0 }
		$sequence_3 = { 57 4154 4156 4157 488dac2400fbffff 4881ec00060000 488b05???????? }
		$sequence_4 = { e8???????? 83c40c 8d85f8feffff 6804010000 50 ff15???????? 8d85f8feffff }
		$sequence_5 = { 488b09 418bf8 488bf2 33db }
		$sequence_6 = { ff15???????? 8b3d???????? 8d85e0feffff 50 }
		$sequence_7 = { 488bcb 664489642438 488bf0 ff15???????? }
		$sequence_8 = { 68ffff0000 56 8b35???????? ffd6 }
		$sequence_9 = { 85c0 7e18 80bc35a8feffff3a 741f 8d85a8feffff 46 50 }
		$sequence_10 = { c6840d8002000033 488d8d80020000 ff15???????? 4863c8 c6840d8002000079 }
		$sequence_11 = { ff15???????? 8b1d???????? 8d85a8feffff 50 ffd3 }
		$sequence_12 = { ff15???????? 4863c8 c6840d7002000062 488d8d70020000 ff15???????? 4863c8 }
		$sequence_13 = { ff15???????? 85c0 7426 8b400c }
		$sequence_14 = { 33f6 50 ffd3 85c0 7e18 }
		$sequence_15 = { 488d4c2460 ff15???????? 4863c8 807c0c5f5c 7413 488d4c2460 ff15???????? }
		$sequence_16 = { 41bc14030000 4c8d0574130100 488bcd 418bd4 e8???????? 33c9 85c0 }
		$sequence_17 = { 83c108 51 ff15???????? 8b4dfc }
		$sequence_18 = { 7370 696465726167656e 742e 657865 }
		$sequence_19 = { 6e 6d 656e 7400 }
		$sequence_20 = { 8b4510 8b8c8d78feffff 890c90 ebc8 e9???????? }
		$sequence_21 = { 7647 498bcd e8???????? 4c8d05b7120100 41b903000000 }
		$sequence_22 = { fa fa fa fa fa fa }
		$sequence_23 = { 8b4df0 e8???????? 8d45f8 50 6a00 }
		$sequence_24 = { 6828010000 8d85ccfeffff 6a00 50 }
		$sequence_25 = { 418d7c24e7 85c0 752a 4c8d0502130100 8bd7 498bcd }
		$sequence_26 = { 4c8d056c120100 498bd4 488bcd e8???????? 85c0 7541 4c8bc3 }
		$sequence_27 = { 636373 7673 6873742e65 7865 }
		$sequence_28 = { ff15???????? 8b45f4 8b4824 894dfc 8b55f4 83c208 }
		$sequence_29 = { 8945fc eb42 8b45f8 33d2 }
		$sequence_30 = { 8bd9 488d0d950c0100 ff15???????? 4885c0 7419 488d15730c0100 488bc8 }
		$sequence_31 = { 488d15f8110100 41b810200100 488bcd e8???????? e9???????? 4533c9 4533c0 }
		$sequence_32 = { 8b8504ffffff 898574feffff 8b4d0c 8b91fc020000 8b4508 0390f0040000 8b4d10 }
		$sequence_33 = { 488bcd e8???????? 85c0 751a 488d15f8110100 41b810200100 }
		$sequence_34 = { 8b55fc 83c208 52 ff15???????? 8b45fc c7400421000000 }
		$sequence_35 = { 33c9 4889742420 e8???????? cc 4c8d056c120100 }
		$sequence_36 = { 83ec08 894df8 c745fc00a40000 6a40 6800100000 6800a40000 6a00 }
		$sequence_37 = { 49 53 53 56 43 }
		$sequence_38 = { 8b4c2414 33cc e8???????? 8be5 5d c21000 57 }
		$sequence_39 = { 0115???????? 1515151503 1515151515 1515041515 1515050607 0809 }
		$sequence_40 = { 8d85e8feffff 50 ff95e4feffff 59 59 837d1c00 7513 }
		$sequence_41 = { 8b8431f4dfffff 44 2bd8 45 2b9c31f8dfffff 45 895c2404 }
		$sequence_42 = { 6a00 8d442448 50 ff15???????? 85c0 7420 }
		$sequence_43 = { 8b4c2408 49 8b542410 e8???????? 85c0 74db 89c0 }
		$sequence_44 = { f7f7 8365ec00 85c0 0f8e94010000 8365f000 8b7e44 }
		$sequence_45 = { 89f1 48 8d5510 e8???????? 90 e8???????? bab3c4b3c4 }
		$sequence_46 = { 6a00 8d85b0feffff 50 56 }
		$sequence_47 = { 6a00 56 c785b4feffff00000000 ff15???????? 50 56 }
		$sequence_48 = { 8d44245c 50 ff15???????? 33c0 5f }
		$sequence_49 = { c744241030000000 c744241403000000 c7442418d0114000 c744241c00000000 c744242000000000 89742424 c744242800000000 }

	condition:
		7 of them and filesize <417792
}
