rule win_owlproxy_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.owlproxy."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.owlproxy"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 488905???????? 4885c0 7420 488d1511fd0000 488bcb ff15???????? 488bc8 }
		$sequence_1 = { ff15???????? 3de5030000 7407 3d47270000 7528 03df 3bde }
		$sequence_2 = { 8bd3 498bce 4d8b0f 4889442420 e8???????? 488d0575340100 4c3bf8 }
		$sequence_3 = { 488bcb 488905???????? ff15???????? 488d1527580100 483305???????? 488bcb 488905???????? }
		$sequence_4 = { 443af8 750b 48ffc7 48ffc3 }
		$sequence_5 = { 4889442438 488bf9 488b4908 488bda 4c8d442420 488d542428 }
		$sequence_6 = { 85c0 7521 448b07 488b4b08 }
		$sequence_7 = { 483305???????? 488bcb 488905???????? ff15???????? 488d15cd570100 483305???????? 488bcb }
		$sequence_8 = { 442bc3 4c8bcb 488bd3 488d8c2470010000 e8???????? 49891e 49897e08 }
		$sequence_9 = { 90 48837c247010 720a 488b4c2458 e8???????? 48c74424700f000000 4c897c2468 }

	condition:
		7 of them and filesize <475136
}
