rule win_poscardstealer_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.poscardstealer."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.poscardstealer"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d85f4fdffff 50 57 e8???????? 33c9 8d85f4fdffff c785ecedffff07000000 }
		$sequence_1 = { 56 8d45d4 50 8d4db8 e8???????? 6a01 }
		$sequence_2 = { c645fc00 3bf7 7409 56 e8???????? }
		$sequence_3 = { e8???????? 83c404 8b45d4 397de8 7303 8d45d4 8b4de4 }
		$sequence_4 = { 8bb580edffff 2bb57cedffff c1fe02 3bfe 7426 8b857cedffff 8d14b500000000 }
		$sequence_5 = { 837d1c10 c745e80f000000 c745e400000000 c645d400 720c 8b4d08 51 }
		$sequence_6 = { 89430c 8d4310 8d896c614200 5a 668b31 668930 }
		$sequence_7 = { 8d8d48ffffff e8???????? 898544ffffff 83f8ff 746f 6aff 50 }
		$sequence_8 = { 66898dd8edffff 837e1408 731c 8b5610 }
		$sequence_9 = { e8???????? 6a01 53 68???????? 8d4d9c c645fc03 e8???????? }

	condition:
		7 of them and filesize <362496
}
