rule win_hoplight_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.hoplight."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hoplight"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 488b4c2460 e8???????? 8b442428 488d0d5e680200 }
		$sequence_1 = { 488b5260 8b0481 894208 488b842480000000 }
		$sequence_2 = { 8b442424 25ff000000 8bc0 488d0d87740200 }
		$sequence_3 = { 4889542420 4d8bc8 488b442440 4c8bc0 }
		$sequence_4 = { 4c8bb42498040000 488b8d80030000 4833cc e8???????? }
		$sequence_5 = { 488d4c2460 e8???????? 488b842470020000 488b4060 }
		$sequence_6 = { 4833c4 48898424f8000000 c744242800000000 488b842410010000 }
		$sequence_7 = { 4c8d05883c0300 488bd0 488b4c2450 e8???????? }

	condition:
		7 of them and filesize <765952
}
