rule win_webc2_kt3_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.webc2_kt3."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_kt3"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8a92c0c84000 089021d34000 40 3bc7 76f5 41 }
		$sequence_1 = { ff15???????? 85c0 0f843a010000 83bdf0fbffff00 0f86a4000000 }
		$sequence_2 = { 836dd001 837dd000 742c 836dd001 }
		$sequence_3 = { 0345f8 c60000 8b4de8 51 ff15???????? 8b55e8 0fbe02 }
		$sequence_4 = { 8955a8 66c745c80000 c745cc00000000 66c745ca0000 c745c401010000 8b4508 8945d0 }
		$sequence_5 = { e8???????? 8945fc 837dfc00 7d05 83c8ff eb25 837dfc00 }
		$sequence_6 = { 7527 8b55fc 0fbe4202 83f82d 751b }
		$sequence_7 = { 51 ff15???????? 8945f0 837df000 7511 8b55f8 52 }
		$sequence_8 = { 8b5508 83c234 83c9ff 33c0 }
		$sequence_9 = { 8bec 83ec30 53 56 57 8b4508 8945e0 }

	condition:
		7 of them and filesize <114688
}
