rule win_pseudo_manuscrypt_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.pseudo_manuscrypt."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pseudo_manuscrypt"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0f8473ffffff 8bd6 8bcf e8???????? 85c0 0f8f62ffffff 53 }
		$sequence_1 = { 668906 e8???????? 8b45fc 83c404 8bfb 3b18 75bd }
		$sequence_2 = { 33db 8d857cfdffff 53 50 53 683f010f00 53 }
		$sequence_3 = { 6a00 6a00 6a00 6a18 ffd6 6a00 6a00 }
		$sequence_4 = { 8bec 56 8bb17c010000 85f6 742a 8b4508 33d2 }
		$sequence_5 = { 6a04 68ffff0000 53 ffd6 0bc7 5f 5e }
		$sequence_6 = { 57 8945fc 8d140b 8bc8 0f44d3 52 e8???????? }
		$sequence_7 = { 7554 5f 33c0 5e 8b4dfc 33cd e8???????? }
		$sequence_8 = { 89442474 8d842480000000 6804010000 50 c744246c01010000 ff15???????? 68???????? }
		$sequence_9 = { 8d85d0fdffff 50 56 ff15???????? 85c0 742c 53 }

	condition:
		7 of them and filesize <753664
}
