rule win_saigon_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.saigon."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.saigon"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 7508 ff15???????? 8bd8 4c8d5c2450 8bc3 498b5b20 498b6b28 }
		$sequence_1 = { 4889442440 488364243800 488364243000 4533c0 488bd3 33c9 }
		$sequence_2 = { ff15???????? 33ed 488bcb 85c0 }
		$sequence_3 = { 7459 f60301 742c 418bcf 488bd0 4903cc e8???????? }
		$sequence_4 = { 488b0d???????? 4c8bc7 33d2 8bd8 ff15???????? eb1e }
		$sequence_5 = { 4156 4157 4883ec60 4c8bea 488d50c8 4d8bf9 e8???????? }
		$sequence_6 = { ffd0 85c0 790e 8bc8 }
		$sequence_7 = { 4c8d8584020000 488d8c2460060000 448bcb 418bd6 e8???????? }
		$sequence_8 = { 33d2 8d440036 448bc0 448be0 ff15???????? }
		$sequence_9 = { 8d4f01 448bcf 4c8bc6 894c2428 33c9 33d2 }

	condition:
		7 of them and filesize <147456
}
