rule win_herpes_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.herpes."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.herpes"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ffd7 68???????? ffb6f0010000 89863c010000 ffd7 68???????? ffb6f0010000 }
		$sequence_1 = { 6a02 6a00 6a00 6800000040 8d95f4fdffff 52 ff15???????? }
		$sequence_2 = { 894dd0 c745c804000000 ffd6 85c0 755c 8b1d???????? ffd3 }
		$sequence_3 = { 8d8d24faffff 51 57 ff15???????? 85c0 0f84e2000000 8b1d???????? }
		$sequence_4 = { 33c9 3b04cd10c84100 7413 41 83f92d 72f1 8d48ed }
		$sequence_5 = { 50 6a01 8d45cc 50 56 ff15???????? 894590 }
		$sequence_6 = { 8dbd88fcffff e8???????? 84c0 745a 8b0d???????? 8d85c0fcffff 50 }
		$sequence_7 = { 8b0d???????? 8d85c0fcffff 50 51 e8???????? c645fc0b 8b15???????? }
		$sequence_8 = { e8???????? eb15 3bc3 7511 8b45b8 895dc8 }
		$sequence_9 = { 83c404 ff15???????? 85c0 7418 6804010000 8d8c24e00a0000 }

	condition:
		7 of them and filesize <319488
}
