rule win_himan_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.himan."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.himan"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 330c9d94886e00 8b58f0 33cb 8bdf c1eb10 81e3ff000000 895c2438 }
		$sequence_1 = { 8bd6 c1ea10 81e2ff000000 c1ed18 8b1495bcc26e00 3314adbcc66e00 8b2c9dbcbe6e00 }
		$sequence_2 = { 81e1ff000000 c1eb08 8b0c8d94906e00 81e3ff000000 330c9d948c6e00 8bde c1eb18 }
		$sequence_3 = { 8b75f4 8bd1 8d7dfc c1e902 }
		$sequence_4 = { 8d8dbcfbffff 51 ffd3 8bf0 46 8d0436 83c003 }
		$sequence_5 = { 55 56 57 b910000000 33c0 8d7c246c }
		$sequence_6 = { c1ea02 83e23f a4 7c0b 83fa40 7d06 8a541428 }
		$sequence_7 = { 8b542444 8d0c00 8b442410 51 53 6a01 }
		$sequence_8 = { 50 ff15???????? 8d4c246c 68???????? }
		$sequence_9 = { c21800 8b4514 50 ff15???????? 33c0 8da5b0f3ffff }

	condition:
		7 of them and filesize <139264
}
