rule win_mrac_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.mrac."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mrac"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8a45fe 8b0c8d804b4500 88441129 8b0b 8bc1 c1f806 83e13f }
		$sequence_1 = { 6a11 888424080d0000 e8???????? 3442 8d8c24f00c0000 6a12 888424090d0000 }
		$sequence_2 = { c684245b0600000b c684245c0600001c c684245d0600001f c684245e06000016 c684245f06000001 c68424600600001a c684246106000016 }
		$sequence_3 = { 8b8424600c0000 0417 3465 8884247b0c0000 8b8424600c0000 0418 346e }
		$sequence_4 = { 88441104 42 83fa2a 72ec 5e c6412e00 8d4104 }
		$sequence_5 = { 3465 888424d7010000 8b8424c0010000 0414 3462 888424d8010000 8b8424c0010000 }
		$sequence_6 = { 88842429120000 e8???????? 3449 8d8c2408120000 6a1b 8884242a120000 e8???????? }
		$sequence_7 = { 888424490a0000 e8???????? 346e 8d8c24340a0000 6a0f 8884244a0a0000 e8???????? }
		$sequence_8 = { 88842463020000 8b842450020000 0410 3420 88842464020000 8b842450020000 0411 }
		$sequence_9 = { 88842478060000 e8???????? 3467 8d8c2464060000 6a0e 88842479060000 e8???????? }

	condition:
		7 of them and filesize <745472
}
