rule win_mydoom_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.mydoom."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mydoom"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0f94c2 83f842 0f94c0 09d0 ba00000000 a801 0f8531010000 }
		$sequence_1 = { 49 c744241000000000 8d85c4fdffff 8944240c 894c2408 }
		$sequence_2 = { 891c24 e8???????? 85c0 743c 8b85d8feffff 89442404 891c24 }
		$sequence_3 = { 891c24 e8???????? 83ec04 c744240402000000 }
		$sequence_4 = { 85c0 89c3 7413 89f6 8dbc2700000000 ff149df8354200 }
		$sequence_5 = { 8d9dc8f9ffff 891c24 e8???????? 8d8568f9ffff 89442424 89742420 }
		$sequence_6 = { 83ec58 895df4 8975f8 897dfc 8b7510 0fb74514 668945e6 }
		$sequence_7 = { 89e5 56 53 83ec10 8b750c 83fe01 }
		$sequence_8 = { 890424 e8???????? e8???????? 8db406fc2f0000 0fb745e6 }
		$sequence_9 = { 85d0 7547 85f6 750c 8b0d???????? 85c9 7546 }

	condition:
		7 of them and filesize <114688
}
