rule win_starsypound_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.starsypound."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.starsypound"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6801010000 e8???????? 53 6a01 6a02 e8???????? }
		$sequence_1 = { 50 e8???????? 83c40c 85c0 7e2b eb08 }
		$sequence_2 = { 85c0 7e2b eb08 6a32 ff15???????? 8b4500 6a00 }
		$sequence_3 = { 6a10 51 55 89442424 e8???????? }
		$sequence_4 = { 6a18 e8???????? 8bb42424040000 8bd8 }
		$sequence_5 = { 51 6801010000 e8???????? 53 6a01 6a02 }
		$sequence_6 = { 6a00 50 8d4c2424 56 }
		$sequence_7 = { e8???????? 83c418 83feff 0f84d9feffff b93f000000 33c0 8d7c2458 }
		$sequence_8 = { 7470 8b3d???????? 8d542410 68???????? }
		$sequence_9 = { 5e 5d 5b 81c4dc030000 c3 8d542430 66c74424140200 }

	condition:
		7 of them and filesize <40960
}
