rule win_newcore_rat_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.newcore_rat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.newcore_rat"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b08 8b11 50 8b4204 ffd0 8d4c2414 e8???????? }
		$sequence_1 = { 898670300000 e8???????? 5f 5d b801000000 }
		$sequence_2 = { 51 8d4c243c e8???????? 8d4c2414 e8???????? 8b542448 52 }
		$sequence_3 = { 50 8d4c245e 51 6689442460 e8???????? 83c40c 6a30 }
		$sequence_4 = { 6a00 6a00 8d542478 52 6a00 ff15???????? 85c0 }
		$sequence_5 = { 8b442450 e9???????? 6830020000 8d442458 6a00 50 }
		$sequence_6 = { 8b8610100000 85c0 740d 50 ffd7 c7861010000000000000 }
		$sequence_7 = { 5b c21000 8d9344020000 68???????? 52 e8???????? 8bf0 }
		$sequence_8 = { 83c40c 03f9 014c2414 eb04 8b5c240c 014c242c b81f85eb51 }
		$sequence_9 = { 68???????? 8d9424ac060000 e8???????? 83c408 53 8d8c24a8060000 }

	condition:
		7 of them and filesize <581632
}
