rule win_simplefilemover_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.simplefilemover."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.simplefilemover"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { f3a5 e8???????? 81c420020000 85c0 }
		$sequence_1 = { 33c0 e9???????? 6820020000 ff15???????? }
		$sequence_2 = { 8bf3 8bfc f3a5 e8???????? }
		$sequence_3 = { 81c420020000 85c0 7407 68???????? eb05 68???????? ff15???????? }
		$sequence_4 = { 83c40c 6a04 8d8d58faffff 51 8d9558daffff 52 e8???????? }
		$sequence_5 = { 7fd4 ffb524020000 66c745ac0200 ff15???????? 668945ae 8d8512020000 50 }
		$sequence_6 = { 68???????? 8d8554daffff 50 e8???????? 83c40c 6a04 8d8d58faffff }
		$sequence_7 = { 8b8d24daffff 2b8d08daffff 898d24daffff 8b9508daffff }
		$sequence_8 = { 4b 81cb00ffffff 43 8b6c2424 81e3ff000000 8a1c03 }
		$sequence_9 = { ff15???????? 59 ff7508 e8???????? 53 ff15???????? 59 }
		$sequence_10 = { 52 e8???????? 83c40c 6a00 6a08 8d8554daffff 50 }
		$sequence_11 = { 8d85b0ddffff 50 e8???????? 8d45dc 57 50 }
		$sequence_12 = { 8b74241c 57 8a8800010000 8a9001010000 33ff 884c2408 3bf7 }
		$sequence_13 = { 0f8c54ffffff 8a4c242c 5d 5b 5f 889000010000 888801010000 }
		$sequence_14 = { 895dd8 895df8 895dd4 ff15???????? }
		$sequence_15 = { 8b4c2410 81e1ff000000 8a1c01 885c241c }
		$sequence_16 = { 5f 5e 5b c3 8b542414 53 52 }
		$sequence_17 = { 663d5c00 7503 8bfa 46 }
		$sequence_18 = { 5e 83c410 c3 5f 888800010000 }
		$sequence_19 = { 68???????? 8b9540daffff 8d84556cdaffff 50 e8???????? 83c40c }
		$sequence_20 = { e8???????? 83c408 6a00 6a00 6a04 }
		$sequence_21 = { 47 897c2418 0fbfff 3bfb 0f8c54ffffff 8a4c242c }

	condition:
		7 of them and filesize <57344
}
