rule win_navrat_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.navrat."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.navrat"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c745dc726f736f c745e066745c57 c745e4696e646f c745e877735c43 c745ec75727265 c745f06e745665 c745f47273696f }
		$sequence_1 = { c745e4696e646f c745e877735c43 c745ec75727265 c745f06e745665 }
		$sequence_2 = { c745e877735c43 c745ec75727265 c745f06e745665 c745f47273696f }
		$sequence_3 = { 7707 0fbec0 83e847 c3 8d48d0 80f909 7707 }
		$sequence_4 = { 884702 85f6 7407 8b7608 83461804 }
		$sequence_5 = { 85f6 7407 8b7608 83461804 }
		$sequence_6 = { c745e066745c57 c745e4696e646f c745e877735c43 c745ec75727265 c745f06e745665 c745f47273696f }
		$sequence_7 = { 3c2f 0f95c0 fec8 2440 fec8 c3 }
		$sequence_8 = { ff15???????? 8bf0 f7de 1bf6 f7de 56 }
		$sequence_9 = { e8???????? 68???????? e8???????? 0fb705???????? }

	condition:
		7 of them and filesize <352256
}
