rule win_sys10_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.sys10."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sys10"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b44240c 85c0 7405 8b5618 8910 8b4620 }
		$sequence_1 = { 8b06 50 e8???????? 8b442418 }
		$sequence_2 = { 83c418 e9???????? 8b963c020000 8b06 52 50 e8???????? }
		$sequence_3 = { 6810270000 ff15???????? 33c0 59 }
		$sequence_4 = { 51 6800400000 52 50 e8???????? 8bf8 83c410 }
		$sequence_5 = { 8b13 52 ffd7 8b4304 }
		$sequence_6 = { 50 6844020000 51 52 }
		$sequence_7 = { 6a00 6a03 68???????? 68???????? 51 }
		$sequence_8 = { c20c00 8b442410 c70044020000 b801000000 }
		$sequence_9 = { 3df4010000 7305 b8f4010000 8b0d???????? 8b15???????? }

	condition:
		7 of them and filesize <286720
}
