rule win_treasurehunter_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.treasurehunter."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.treasurehunter"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 75f9 2bf0 e8???????? 8bd0 }
		$sequence_1 = { 53 56 8b35???????? 8bd9 8b4d08 57 }
		$sequence_2 = { 8bf8 e8???????? 68???????? 57 e8???????? }
		$sequence_3 = { 8bd9 8b4d08 57 8955fc e8???????? 8bce 8bf8 }
		$sequence_4 = { 57 8bf9 8bca e8???????? 8b7508 }
		$sequence_5 = { 56 50 8903 ff15???????? 8b4dfc }
		$sequence_6 = { 7e0b 4a e8???????? 0fafc6 5e c3 }
		$sequence_7 = { e8???????? b9???????? a3???????? e8???????? 5f 5e a3???????? }

	condition:
		7 of them and filesize <229376
}
