rule win_webc2_qbp_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.webc2_qbp."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_qbp"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 81ec24010000 56 57 c685f8feffff00 b940000000 }
		$sequence_1 = { 83f808 7c67 8b4dfc 33d2 668b917a830000 52 }
		$sequence_2 = { 7d13 0fbf45f8 8b4dec 668b5508 6689944138770000 }
		$sequence_3 = { 8b4df0 e8???????? 8be5 5d c20400 55 8bec }
		$sequence_4 = { 8b45fc 25ffff0000 660fb68848644000 51 8b4df8 e8???????? 8b5508 }
		$sequence_5 = { 8b45f8 668b4dfc 66898c504a300000 eb1e }
		$sequence_6 = { 0fbf4dfc 0fbf5508 8b45e8 8b75e8 }
		$sequence_7 = { 03909c830000 52 e8???????? 83c40c }
		$sequence_8 = { 66050100 668945f4 e9???????? 66c745f80000 66c745f43a01 eb18 }
		$sequence_9 = { 2c08 8b4dfc 88817c830000 8b55fc 33c0 8a827c830000 }

	condition:
		7 of them and filesize <630784
}
