rule win_alreay_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.alreay."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alreay"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b742450 2bc6 f7d8 1bc0 259adaffff 5f 5e }
		$sequence_1 = { 8d442414 45 52 50 892d???????? e8???????? 8bf0 }
		$sequence_2 = { c1e21c 89442420 8954241c 8bc3 8bd5 e8???????? 8b4c2420 }
		$sequence_3 = { 8ac1 f6d0 8a543418 8a5c3448 22d0 22d9 0ad3 }
		$sequence_4 = { 89742424 7fa9 5f 5e 5d b801000000 5b }
		$sequence_5 = { eb31 0fbf942454010000 8d442434 52 8d4c2414 50 8d542420 }
		$sequence_6 = { 894e0c 8901 8b4c241c 8b460c 51 56 895804 }
		$sequence_7 = { 33c3 8b5c2424 03dd 03c3 8b5c2414 8dac03d6c162ca 8b442464 }
		$sequence_8 = { 8b8f98000000 89af90000000 83c901 899f94000000 898f98000000 8b879c000000 89879c000000 }
		$sequence_9 = { 3d2c010000 7d1f 8d8664860000 50 e8???????? 8bd8 83c404 }

	condition:
		7 of them and filesize <1867776
}
