rule win_heloag_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.heloag."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.heloag"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6889130000 68???????? 8b4810 51 e8???????? 83f8ff }
		$sequence_1 = { 8d95e0feffff 83e103 f3a4 bf???????? }
		$sequence_2 = { 90 90 90 90 8d45e8 50 }
		$sequence_3 = { 8b3d???????? 6a00 6a01 6a02 e8???????? }
		$sequence_4 = { 8b3d???????? 6a01 ffd7 8d4df0 51 ffd6 }
		$sequence_5 = { ffd6 ebb8 8b15???????? 8b4210 }
		$sequence_6 = { 66ab 85f6 aa 0f849c000000 b940000000 }
		$sequence_7 = { 33c0 8dbdddfeffff 8d95dcfeffff f3ab aa 83c9ff }
		$sequence_8 = { ff15???????? 84c0 7420 8b7d04 }
		$sequence_9 = { 3bc5 7505 a1???????? 50 }
		$sequence_10 = { 49 51 53 68???????? 8d4c2420 ff15???????? }
		$sequence_11 = { 742d 8b7604 85f6 7506 8b35???????? 8b7b04 }
		$sequence_12 = { 85c0 7505 a1???????? 8b4c242c }
		$sequence_13 = { 8b4e0c 894b0c 8a48ff fec1 8848ff eb3c }
		$sequence_14 = { 8b11 8bcf 52 6a00 50 ff15???????? }
		$sequence_15 = { 741f 8b7c2418 8bcb 8bd1 53 }

	condition:
		7 of them and filesize <401408
}
