rule win_elirks_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.elirks."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.elirks"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8d4c2414 51 68???????? 8bf0 ff15???????? }
		$sequence_1 = { 85c0 7417 8b44241c 01442414 03f0 2bf8 e9???????? }
		$sequence_2 = { 51 8d44241c e8???????? 8b8e04600000 83c404 }
		$sequence_3 = { 83c102 66c7012d00 83c102 66c7012d00 83c102 83ef03 83c603 }
		$sequence_4 = { 68???????? 8d442430 e8???????? 83c40c }
		$sequence_5 = { 7fe8 85ff 0f84a1010000 85ff 7e25 }
		$sequence_6 = { c1f803 0faf4608 894614 6a68 }
		$sequence_7 = { 52 ff15???????? 8bd8 83fbff 895c2410 7546 }
		$sequence_8 = { 8d8c2490060000 51 6804010000 ff15???????? 8d9e0c600000 53 6a00 }
		$sequence_9 = { 750b 57 e8???????? 83c404 5e c3 }

	condition:
		7 of them and filesize <81920
}
