rule win_dmsniff_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.dmsniff."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dmsniff"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff7508 e8???????? 89c7 6a00 }
		$sequence_1 = { 57 be19000200 8d45fc 50 56 }
		$sequence_2 = { 40 803c0100 75f9 6a01 50 }
		$sequence_3 = { f7e7 8945f0 50 e8???????? 89c3 81e3ff000000 89de }
		$sequence_4 = { eb03 31c0 40 5f 5e c9 }
		$sequence_5 = { 89c7 6a00 6a00 56 53 57 }
		$sequence_6 = { 83c41c 89c7 09ff 7507 31c0 }
		$sequence_7 = { 31c9 8b442408 8a140e 881408 803c0e00 }
		$sequence_8 = { eb3a ff7518 ff7514 ff751c 6a00 }
		$sequence_9 = { 6a00 68???????? e8???????? 89c7 09ff }

	condition:
		7 of them and filesize <131072
}
