rule win_thunderx_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.thunderx."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.thunderx"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { b9???????? 83f801 0f45ca 51 8d8d30ffffff e8???????? }
		$sequence_1 = { 0f847b010000 8d442410 895c2410 50 56 895c241c ff15???????? }
		$sequence_2 = { 57 53 56 897e10 e8???????? 83c40c 881c37 }
		$sequence_3 = { 68???????? 8d4dd4 e8???????? c645fc01 3b75e4 7713 }
		$sequence_4 = { f7f9 8bce 6bd01c e8???????? 8b45fc 6bcb1c 893d???????? }
		$sequence_5 = { ff35???????? ff15???????? 8b75ec 85f6 74d3 85c0 74cf }
		$sequence_6 = { be???????? c645fc07 56 8bd0 8d8d18ffffff e8???????? 59 }
		$sequence_7 = { 85c0 7412 8b7d98 8b459c eb10 8d4de4 e8???????? }
		$sequence_8 = { 8b442424 81c70000a000 13c3 89442424 3b442414 0f8c49ffffff }
		$sequence_9 = { b8???????? e8???????? 803d????????00 7478 33ff 897dfc }

	condition:
		7 of them and filesize <319488
}
