rule win_pinchduke_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.pinchduke."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pinchduke"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 6a01 895dd4 895dd8 895ddc c645e030 895de1 }
		$sequence_1 = { 9b d93c24 9b 58 50 80e4f3 80cc08 }
		$sequence_2 = { 85d2 7416 8d4c50fe 2bf0 57 668b3c0e 668939 }
		$sequence_3 = { 83c40c 8d857bffffff 50 8d4dc4 e8???????? 8d8d7bffffff e8???????? }
		$sequence_4 = { 50 ff15???????? 3bc3 89456c 0f84cc020000 }
		$sequence_5 = { 8945fc e8???????? 83c410 ff75fc 56 ff15???????? 56 }
		$sequence_6 = { 64a118000000 3e8b4030 3e0fb64002 890424 8b0424 59 c3 }
		$sequence_7 = { 6a00 ff7510 ff75fc ffd6 85c0 7404 33c0 }
		$sequence_8 = { 85d2 75f5 8bc7 5f 5e c3 8b4c240c }
		$sequence_9 = { e8???????? 8d85e4f7ffff 50 e8???????? 83ec0c 8bcc 50 }

	condition:
		7 of them and filesize <223680
}
