rule win_bohmini_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.bohmini."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bohmini"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c744241000000000 8944240c ff15???????? 8b542404 }
		$sequence_1 = { 85f6 7599 8b35???????? 85f6 7415 8b442420 }
		$sequence_2 = { 8944241c a1???????? 894c2420 8a0d???????? }
		$sequence_3 = { 885c0410 40 83f820 7ce7 8b1d???????? 33f6 8d7c245c }
		$sequence_4 = { 81c200080000 895010 a1???????? 8b1d???????? 8b15???????? 8b4810 03cb }
		$sequence_5 = { ffd7 33f6 e9???????? 6a00 6880000000 }
		$sequence_6 = { 6800040000 50 53 ff15???????? 50 }
		$sequence_7 = { 48 8a16 8bef 0fbed9 3bd3 7531 84c9 }
		$sequence_8 = { 55 51 e8???????? 8d049b 8b3d???????? 83c418 }
		$sequence_9 = { 75c4 57 ff15???????? 8b542414 52 ff15???????? }

	condition:
		7 of them and filesize <139264
}
