rule win_flagpro_auto_alt_3
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.flagpro."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.flagpro"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8bc3 55 8d2c3f 55 68???????? 8d1409 52 }
		$sequence_1 = { 89b42494000000 899c2490000000 889c2480000000 39ac24b0000000 7210 8b94249c000000 }
		$sequence_2 = { 396c2458 720d 8b4c2444 51 e8???????? 83c404 895c2458 }
		$sequence_3 = { 33d2 c68424984501000f 83bc241c01000010 c744245807000000 c744245400000000 6689542444 }
		$sequence_4 = { 895c2474 89742470 c644246000 396c2458 720d 8b4c2444 }
		$sequence_5 = { 803c083d 0f8470010000 3b4b14 7609 }
		$sequence_6 = { eb02 8bc5 8b6c2424 c6043800 45 83fd03 896c2424 }
		$sequence_7 = { e9???????? 8b542408 8d8274bafeff 8b8a70bafeff }
		$sequence_8 = { 8b44241c 8d542434 895c2434 8b08 52 50 8b4148 }
		$sequence_9 = { 83c404 51 e8???????? 83ec18 }

	condition:
		7 of them and filesize <1411072
}
