rule win_alureon_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.alureon."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alureon"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b4dfc 8b07 8d440802 50 ff75f0 }
		$sequence_1 = { 6a60 32c0 59 6a2c }
		$sequence_2 = { 8b5710 49 03d3 4c 3912 }
		$sequence_3 = { 0fb603 0fb65301 23c6 c1e004 c1ea04 0bc2 8a4405bc }
		$sequence_4 = { 8b48fc 83c028 f3a4 8b78f8 0fb74b06 03fa ff45f8 }
		$sequence_5 = { 756d 33f6 56 8d45f0 }
		$sequence_6 = { 83c228 48 03f5 41 ffc0 f3a4 }
		$sequence_7 = { 03d3 48 8bce 48 }
		$sequence_8 = { 83c424 68???????? 68???????? 885dff ff15???????? 50 ff15???????? }
		$sequence_9 = { ff742408 ff30 e8???????? 85c0 59 59 }
		$sequence_10 = { ff7028 8bf0 e8???????? 59 50 ff742418 }
		$sequence_11 = { 8b35???????? 51 bfff010000 03c3 }
		$sequence_12 = { 53 8d442418 50 6a15 }
		$sequence_13 = { ff15???????? 385dff 0f85d3000000 8d45e8 50 683f000f00 53 }
		$sequence_14 = { 50 53 68???????? 8d8424ec000000 50 ff15???????? }
		$sequence_15 = { 68???????? 8d842400040000 56 50 ff15???????? 68b6100000 }

	condition:
		7 of them and filesize <278528
}
