rule win_bistromath_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.bistromath."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bistromath"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c744242c00000000 eb0b 8bce e8???????? 8944242c 8b44240c 33f6 }
		$sequence_1 = { 8bcb 23550c 234d10 0bd1 750f 0bf3 7506 }
		$sequence_2 = { c704b0???????? 8b4748 8b75d8 894108 ff4748 8b4108 8945c0 }
		$sequence_3 = { ff461c 8b55f8 89548804 8b55d4 66c704885d00 c644880300 89548808 }
		$sequence_4 = { 8bce e8???????? 837c242800 0f85e2000000 8b442418 8b480c f6412c20 }
		$sequence_5 = { e8???????? 8b4df0 83c408 85c9 7421 8b7108 83ff01 }
		$sequence_6 = { 8b8a00020000 0101 eb3e 3b9a0c010000 721e 3b9a10010000 7316 }
		$sequence_7 = { 8d04dd04000000 894df8 8b4df4 50 e8???????? 83c404 8945fc }
		$sequence_8 = { 730a 0fb6c0 8954811c fe4113 c681b800000000 c781c000000000000000 8b91d8000000 }
		$sequence_9 = { e8???????? 8b45f8 c7473400000000 894738 5f 5e 5b }

	condition:
		7 of them and filesize <33816576
}
