rule win_udpos_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.udpos."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.udpos"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 0353f8 8b7dfc 8d943a9979825a 8b7df8 8975fc c1c802 894df0 }
		$sequence_1 = { e8???????? 83c418 89b5dcfbffff ff15???????? 50 57 68ffff1f00 }
		$sequence_2 = { 52 ffd6 8d8550f7ffff 50 8d8de0f8ffff 51 }
		$sequence_3 = { 8935???????? 53 e8???????? 83c404 8b95e4fbffff 52 ff15???????? }
		$sequence_4 = { c70000000000 8b4220 51 50 }
		$sequence_5 = { e8???????? 83c40c 8d95f8fdffff 52 8d85fcfdffff 50 ff15???????? }
		$sequence_6 = { e8???????? 8b15???????? 83c418 52 8d85e0f8ffff 50 ffd6 }
		$sequence_7 = { 68???????? e8???????? 68???????? ff15???????? 8b7508 c7465ca8ac4000 }
		$sequence_8 = { 85c0 7e14 8bff 660fbe1431 6689944d18f8ffff 41 }
		$sequence_9 = { 8bf0 51 56 c785d0fdffff2c020000 ff15???????? }

	condition:
		7 of them and filesize <163840
}
