rule win_daserf_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.daserf."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.daserf"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8945cc ff15???????? 8945d0 8d45b4 }
		$sequence_1 = { b808380000 e8???????? 53 56 }
		$sequence_2 = { 81eb7ee5b031 81c30d782341 81c3db5d1091 81eb73ad763b 054ce1128c 81c3cc3c3014 }
		$sequence_3 = { 81c3ad482863 81eb8c570d21 2d21583cc4 2da932ed1b 81c3f8ff2857 81eb46159323 }
		$sequence_4 = { 81eb4e0e3377 87c0 81ebfb04024c 87ff 2dfaa67876 }
		$sequence_5 = { 81c394c7d041 81eb6afed62a 81c3bed1834b 81eb826387e9 81c3d7e98170 2d844df6b2 }
		$sequence_6 = { 50 ffd6 ffb56814ffff 8d85bc4fffff 50 }
		$sequence_7 = { 2d4936916d f7d1 f7d1 2d99d06187 f7d1 f7d1 }
		$sequence_8 = { 8bc9 81c3c9920a05 95 89ac2400f2ffff }
		$sequence_9 = { 7500 81c3e109e0f6 8bc0 0537d68276 9b 81c38da225f6 87c9 }
		$sequence_10 = { eb0e ff75fc ffd7 3bf3 7403 56 }
		$sequence_11 = { 81c327f27a10 7500 81ebc884a519 7500 81eb3a0de80d 87db 81c3b119330a }
		$sequence_12 = { 2d4abc1884 90 2dea9bf526 7500 }
		$sequence_13 = { 81ebf74ea63a f7d1 f7d1 81eb199760ae 9b }
		$sequence_14 = { 2d966cdd4c 2d81c26ac5 81c32b73f252 81c32bef6e96 81c3b4dacce0 }
		$sequence_15 = { 81eb075e2ddb 9b 81c35a11e727 97 89bc2440f5ffff }

	condition:
		7 of them and filesize <245760
}
