rule win_crylocker_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.crylocker."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crylocker"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? 8b4c2438 8bf0 8b44243c 6a00 50 }
		$sequence_1 = { c744243800000280 c744243c000001e0 c744244008020000 c744244400bab34b 895c241c }
		$sequence_2 = { 394c243c 0f8711ffffff 5f 5b }
		$sequence_3 = { 7520 8b4c2424 6a00 6a00 }
		$sequence_4 = { 55 57 ff15???????? 8b4c241c 03f0 }
		$sequence_5 = { 6a00 57 e9???????? e8???????? 85c0 7458 }
		$sequence_6 = { 85c0 7937 6a01 6814010000 }
		$sequence_7 = { 52 e8???????? e8???????? e8???????? 8b0d???????? 8d442420 }
		$sequence_8 = { 56 e8???????? 8b442414 6a64 }
		$sequence_9 = { 8bd8 51 895c2428 e8???????? 8b15???????? 83c408 }

	condition:
		7 of them and filesize <139264
}
