rule win_nimbo_c2_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.nimbo_c2."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nimbo_c2"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 48895808 4883c428 5b 5e c3 53 4883ec20 }
		$sequence_1 = { 488d51fb b9fdff0000 4839d0 0f8fae000000 0fb6543e10 8a4c0614 41c1e018 }
		$sequence_2 = { 488d0530feffff 4c8d442427 31d2 4889442430 488b442428 48895c2438 488b4810 }
		$sequence_3 = { 4883ec28 488b01 4e8b64c010 4889ce 4889d7 4c89c3 488b06 }
		$sequence_4 = { 7208 8b5224 395328 7e17 0fbae00d 488b13 7307 }
		$sequence_5 = { 48891d???????? 488d9ff0000000 4c8915???????? 48c705????????08000000 48c705????????08000000 66c705????????1903 }
		$sequence_6 = { 488b4cc210 48ffc0 4c8b01 488b4908 43884c0410 ebe5 488d4c2430 }
		$sequence_7 = { 85c0 789c 4c8d6b06 4c89e1 4c89ea e8???????? 4989c4 }
		$sequence_8 = { 4885c9 0f848b000000 f6421101 0f8581000000 8a4210 450fb6c0 }
		$sequence_9 = { e8???????? eb10 488b13 4c89e1 e8???????? e9???????? 4c89e8 }

	condition:
		7 of them and filesize <1076224
}
