rule win_nymaim2_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.nymaim2."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nymaim2"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 8b7de8 ff4514 6a04 890a 59 014dfc }
		$sequence_1 = { c645fc0c e8???????? b8???????? c3 6a51 8d4ddc e8???????? }
		$sequence_2 = { c9 c20800 56 8bf1 8b4604 c706???????? 85c0 }
		$sequence_3 = { 80fa30 7c05 80fa39 7ee8 5e c3 }
		$sequence_4 = { ff7650 8945fc ff750c 50 e8???????? 8b86a0000000 8b7df8 }
		$sequence_5 = { 53 56 8bf1 57 68fd030000 8d4dc0 e8???????? }
		$sequence_6 = { 897df0 397df0 8d4d08 0f95c3 834dfcff e8???????? 8b4df4 }
		$sequence_7 = { a5 a5 50 a5 e8???????? 8d75e0 8d7dc0 }
		$sequence_8 = { ff15???????? 6a19 99 59 f7f9 8bc2 83c061 }
		$sequence_9 = { e8???????? 85c0 59 7535 33ff 3975e8 7e2e }

	condition:
		7 of them and filesize <753664
}
