rule win_ldr4_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.ldr4."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ldr4"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { ff742410 6a00 ff742414 ff742414 6a00 6a00 ffd0 }
		$sequence_1 = { e8???????? 8bfb 85db 0f855d020000 8d44242c 50 e8???????? }
		$sequence_2 = { 81fee5030000 740c 8b7d08 56 ff7514 e8???????? 5f }
		$sequence_3 = { 6a00 6a00 ffd0 eb02 33c0 85c0 750f }
		$sequence_4 = { 3bc6 7d34 ff15???????? 8bd8 83fbff 7508 ff15???????? }
		$sequence_5 = { ffd7 5f 8b4508 5e c9 c20c00 55 }
		$sequence_6 = { 89480c 8b45fc 897808 8b45fc }
		$sequence_7 = { 33c0 c20400 56 57 6a08 }
		$sequence_8 = { 53 894604 ff15???????? 894508 83f80e 7616 8d8f28d20010 }
		$sequence_9 = { 8d4d14 51 6a54 ff7614 ffd0 814d0800008000 c74514bb010000 }

	condition:
		7 of them and filesize <117760
}
