rule win_nokoyawa_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.nokoyawa."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nokoyawa"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { 488b4c2440 488d0441 4889442438 c744242c00000000 8b44242c 488b4c2440 488b542438 }
		$sequence_1 = { c1e205 0bd1 8bca 8b942410010000 03d1 8bca badcbc1b8f }
		$sequence_2 = { 488b442430 488b4868 e8???????? 488b442430 488b4848 e8???????? 488b4c2430 }
		$sequence_3 = { 8b542410 c1e205 0bd1 8bca 8b94245c010000 03d1 8bca }
		$sequence_4 = { 448bc0 33d2 488b4c2438 e8???????? 4c8d4c2440 4c8b442438 }
		$sequence_5 = { 8944240c 33c0 85c0 0f8541ffffff b804000000 486bc003 b904000000 }
		$sequence_6 = { 85c0 740d 488b0424 48ffc0 48890424 ebe2 8b0424 }
		$sequence_7 = { b904000000 486bc90d 33440c20 b904000000 486bc902 }
		$sequence_8 = { 23c8 8bc1 8b4c2404 33c8 8bc1 8b4c240c }
		$sequence_9 = { 0bc1 89442410 33c0 85c0 0f8528ffffff b804000000 486bc00c }

	condition:
		7 of them and filesize <92160
}
