rule win_agent_btz_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.agent_btz."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.agent_btz"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c74608ffffffff f644240801 7409 56 e8???????? 83c404 8bc6 }
		$sequence_1 = { ffd6 8d54240c 52 ffd7 }
		$sequence_2 = { ffd3 85c0 75d8 5f 5e 5b }
		$sequence_3 = { ff15???????? b800000f00 8b4df4 64890d00000000 }
		$sequence_4 = { c706???????? c7460c00000000 895e08 895e04 }
		$sequence_5 = { b805000f00 8b4df4 64890d00000000 5f 5e }
		$sequence_6 = { 895e08 895e04 c7461000000000 895e14 }
		$sequence_7 = { 56 6a00 68???????? 8935???????? }
		$sequence_8 = { 8b4608 c706???????? 85c0 7413 }
		$sequence_9 = { 83f8ff 740e 50 ff15???????? c74608ffffffff f644240801 }
		$sequence_10 = { 8d542408 52 c744240c30000000 c744241003000000 }
		$sequence_11 = { 6801010000 ff15???????? 85c0 7415 }
		$sequence_12 = { 51 6a00 6819000200 6a00 68???????? }
		$sequence_13 = { 6a0a 68???????? 6a01 6a00 }
		$sequence_14 = { 50 68???????? 6a01 68???????? e8???????? 83c410 }
		$sequence_15 = { 6a01 6a04 6a01 68???????? }
		$sequence_16 = { 68???????? 6a01 e8???????? 50 e8???????? 83c41c }
		$sequence_17 = { 89461c 3dea000000 740b 3de5030000 }
		$sequence_18 = { 7511 e8???????? 83c020 50 e8???????? }
		$sequence_19 = { 6a01 68???????? e8???????? 83c414 5f 5e }
		$sequence_20 = { 50 e8???????? 83c408 6800010000 e8???????? }
		$sequence_21 = { 0fb605???????? 66890d???????? 0fb60d???????? 660fafca 6603c8 }
		$sequence_22 = { 59 6a69 66894de8 59 }
		$sequence_23 = { 5e 8bc3 5b c9 c3 83c8ff eb11 }
		$sequence_24 = { c684248d00000065 c684248e00000050 c684248f00000072 c68424900000006f c684249100000063 c684249200000065 }
		$sequence_25 = { c68424900000006f c684249100000063 c684249200000065 c684249300000073 c684249400000073 c684249500000057 c684249600000000 }
		$sequence_26 = { c684248800000043 c684248900000072 c684248a00000065 c684248b00000061 c684248c00000074 c684248d00000065 c684248e00000050 }
		$sequence_27 = { 57 53 897dfc 897e1c }
		$sequence_28 = { 59 6a65 668945f0 66894dec 59 6a25 58 }
		$sequence_29 = { 59 6a70 66894dea 59 }
		$sequence_30 = { c684241601000074 c684241701000045 c684241801000072 c684241901000072 c684241a0100006f c684241b01000072 }
		$sequence_31 = { ebd2 c78424a000000068000000 c78424dc00000001000000 33c0 66898424e0000000 }
		$sequence_32 = { c684249600000000 c684241001000047 c684241101000065 c684241201000074 c68424130100004c c684241401000061 }
		$sequence_33 = { 59 6a70 66894de4 8bc8 }
		$sequence_34 = { 51 6a05 ff75fc 897df0 }
		$sequence_35 = { c684241201000074 c68424130100004c c684241401000061 c684241501000073 c684241601000074 c684241701000045 c684241801000072 }
		$sequence_36 = { 6a00 6a27 6a02 6a00 6a01 }
		$sequence_37 = { 8d8505feffff 50 e8???????? 83c40c }
		$sequence_38 = { c645d316 c645d43a c645d53b c645d63b }
		$sequence_39 = { c645cb30 c645cc27 c645cd3b c645ce30 }
		$sequence_40 = { 488b4338 33d2 488bce 448d4220 }
		$sequence_41 = { 488b4608 488b0e 48894628 488b4638 4c8d4c2450 448bc3 488bd7 }
		$sequence_42 = { 4533c9 488bd6 ff90c8010000 8bf8 85c0 }
		$sequence_43 = { 488b4638 488b0e 4c8d442450 4533c9 }
		$sequence_44 = { 488bf0 c70005000000 85db 7415 4c8b4f38 }
		$sequence_45 = { 488b0f 48894108 488b0f 488b4108 48894128 488b0f }
		$sequence_46 = { 83c904 c1e803 448bc9 440fafc8 }
		$sequence_47 = { 488bcf c744242088130000 e8???????? 488b5738 }
		$sequence_48 = { 488b0f 488901 488b07 488338ff }
		$sequence_49 = { 488bce 8bd8 ff92e8010000 488b6c2458 8bc3 488b5c2450 }
		$sequence_50 = { 488b0f 894130 eb06 488b07 896830 }
		$sequence_51 = { 488b07 896830 33c0 488b5c2458 }
		$sequence_52 = { 8d8594faffff 50 68???????? ff15???????? }
		$sequence_53 = { 013d???????? 8b04b5100b4200 0500080000 3bc8 }
		$sequence_54 = { 0304b5100b4200 59 5e eb05 }
		$sequence_55 = { 001cbe 40 0023 d18a0688078a 46 }
		$sequence_56 = { 030c85100b4200 eb02 8bcb f6412480 }
		$sequence_57 = { 0304b5100b4200 59 eb02 8bc3 }
		$sequence_58 = { 0304b5100b4200 59 eb05 b8???????? }
		$sequence_59 = { 0304b5100b4200 beffff0000 59 59 }

	condition:
		7 of them and filesize <5577728
}
