rule win_webbytea_auto_alt_2
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2024-10-31"
		version = "1"
		description = "Detects win.webbytea."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webbytea"
		malpedia_rule_date = "20241030"
		malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
		malpedia_version = "20241030"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c68424f100000072 c68424f200000065 c68424f300000061 c68424f400000074 }
		$sequence_1 = { ff15???????? 85c0 7444 41b904000000 }
		$sequence_2 = { 8901 488d542430 488b4c2420 ff15???????? }
		$sequence_3 = { c7042400000000 eb08 8b0424 ffc0 890424 8b442438 }
		$sequence_4 = { ffc0 488b8c2488020000 8901 488d542430 488b4c2420 ff15???????? 85c0 }
		$sequence_5 = { 8b00 ffc0 488b8c2488020000 8901 488d542430 488b4c2420 }
		$sequence_6 = { 8b542438 891481 488b842488020000 8b00 ffc0 488b8c2488020000 8901 }
		$sequence_7 = { ffc0 488b8c2488020000 8901 488d542430 488b4c2420 ff15???????? }
		$sequence_8 = { 4803c8 488bc1 48c744243000000000 c744242800000000 }
		$sequence_9 = { ffc0 890424 8b442438 390424 }

	condition:
		7 of them and filesize <552960
}
