rule win_fakerean_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.fakerean."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fakerean"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c9 c3 55 8bec 8b11 83c8ff 85d2 }
		$sequence_1 = { ff7508 e8???????? 83c40c 83f8ff 7432 8b4df0 6bc018 }
		$sequence_2 = { e9???????? 83fe7b 0f8512ffffff 8b9358010000 8bc7 e8???????? ffb354010000 }
		$sequence_3 = { 8b01 57 6a64 57 6a64 ff35???????? 51 }
		$sequence_4 = { 50 ff5128 897dfc e9???????? 83f801 7511 393d???????? }
		$sequence_5 = { 6a32 58 e8???????? 837d1001 59 8945fc 755b }
		$sequence_6 = { 83c274 52 68???????? ff15???????? e8???????? 99 }
		$sequence_7 = { 751e a1???????? 80b8004c000000 7510 6a05 ff35???????? ff15???????? }
		$sequence_8 = { ff15???????? 8b4508 8b7f04 8b4d10 682000cc00 ff7514 49 }
		$sequence_9 = { 56 57 8d7034 8975fc }

	condition:
		7 of them and filesize <4071424
}
