rule win_agendacrypt_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.agendacrypt."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.agendacrypt"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c3 8b45f0 8d4408ff 68???????? 6a28 50 e8???????? }
		$sequence_1 = { e9???????? 89f9 31d2 e8???????? 89c3 00db 89d8 }
		$sequence_2 = { c784240c0e000004000000 660fd69424100e0000 888c241d0e0000 ff7308 895c2428 ff33 8d8424a80d0000 }
		$sequence_3 = { c1c007 c1c215 89f1 8b75f0 31d0 89fa 894de4 }
		$sequence_4 = { f20f118c248c010000 0f8455030000 8b942478010000 8bbc2480010000 f20f100d???????? 0f57c0 89b4242c010000 }
		$sequence_5 = { e8???????? 83c414 837c242000 7463 8b442428 f20f10442420 89442418 }
		$sequence_6 = { ff30 6a00 ff31 e8???????? 83c43c 5e 5f }
		$sequence_7 = { c1e206 c5edfec3 8d9c24e0000000 c1e706 c5fd7f442440 01f8 01fe }
		$sequence_8 = { eb43 c1e006 83c302 31d2 09f0 895df0 89c1 }
		$sequence_9 = { f20f5ec2 81c634010000 89f0 f7d8 0f48c6 3d35010000 73dc }

	condition:
		7 of them and filesize <3340288
}
