rule win_vsingle_auto
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-07-11"
		version = "1"
		description = "Detects win.vsingle."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vsingle"
		malpedia_rule_date = "20230705"
		malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
		malpedia_version = "20230715"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { c6458e00 c6458f00 c6459000 c6459100 c6459200 c6459346 c645949b }
		$sequence_1 = { 0345a0 3945c8 0f83fe000000 8b4dc8 }
		$sequence_2 = { e8???????? 0faff8 03f7 56 8d950cffffff }
		$sequence_3 = { c68524f7ffff00 6800080000 6a00 8d8d25f7ffff 51 e8???????? 83c40c }
		$sequence_4 = { 89450c c745fc00000000 837d0800 745c 837d0c00 }
		$sequence_5 = { 8945f8 8b4df8 83e901 894df8 837df803 7750 }
		$sequence_6 = { 8b4508 0345fc 8b4d0c 8a1411 885002 e9???????? 837d1002 }
		$sequence_7 = { 8d8dacf7ffff 898d80f7ffff 8b9580f7ffff 83c201 899560f7ffff }
		$sequence_8 = { b801000000 6bc803 b804000000 d1e0 034508 be01000000 6bf603 }
		$sequence_9 = { 8b9584f7ffff 8a02 88858ff7ffff 838584f7ffff01 80bd8ff7ffff00 75e2 }

	condition:
		7 of them and filesize <940032
}
