rule win_rockloader_auto_alt_1
{
	meta:
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		date = "2023-12-06"
		version = "1"
		description = "Detects win.rockloader."
		info = "autogenerated rule brought to you by yara-signator"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rockloader"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"
		os = "windows"
		filetype = "executable"

	strings:
		$sequence_0 = { e8???????? dc1d???????? dfe0 f6c441 740f }
		$sequence_1 = { e8???????? 85c0 74b4 c6002c 40 837d0c00 7404 }
		$sequence_2 = { 8a06 3c22 750c ff7508 8bc6 e8???????? }
		$sequence_3 = { 8b45f4 8945e8 8d45f8 50 8d45e4 }
		$sequence_4 = { eb05 68???????? e8???????? 8bf8 8bc7 }
		$sequence_5 = { e8???????? 33f6 53 8975f8 }
		$sequence_6 = { 3975f4 7e55 53 8b45f8 }
		$sequence_7 = { ff4608 8b7f08 85ff 7452 8b4508 }
		$sequence_8 = { d9ee 53 56 dd55ec d9e8 33f6 }
		$sequence_9 = { 8975f8 db45f8 8365f800 dec1 dd5ddc 9b }

	condition:
		7 of them and filesize <98304
}
